### ISSUE TITLE
[css-paint-api] Allow paint function arguments, properties, or both?

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#100]
Example with just properties:

```
.foo {
  --bar: 5;
  background-image: paint(foo), paint(foo);
}

registerPaint(class {
  static inputProperties = ['--bar', 'color'];
  void paint(ctx, geom, styleMap) {
    // --bar & color both available here.
  }
});
```

Pros:
- Can use `color`.

Cons:
- Can't use same function to get different result (like `linear-gradient`).

Example with just input arguments

```
.foo {
  --bar: 5;
  background-image: paint(foo, var(--bar)), paint(foo, 10);
}

registerPaint(class {
  static inputArguments = ['&lt;number&gt;'];
  void paint(ctx, geom, styleMap) {
    // --bar & color both available here.
  }
});
```

Pros:
- Can use same function with different arguments.

Cons:
- Can't access native properties like `color`.

**Comment by bfgeek** [comment]
.foo {
  --my-color: red;
  color: var(--my-color);
  background-image: paint(foo, var(--my-color));
}

**Comment by bfgeek** [comment]
background-image: paint(foo, var(--qux as --bar))

registerPaint(
 ... inputProperties = ['--bar'];

**Comment by bfgeek** [comment]
paint(foo, 0deg, red);

**Comment by bfgeek** [comment]
The HoudiniTF F2F resolved to add both for paint lvl1.

**Comment by bfgeek** [comment]
It turns out this is hard to spec. This requires defining a grammar for what the paint image function can accept (to be fully flexible).

For example:
```js
registerPaint('foo', class {
  static inputArgumentSyntax = '<number>? <length>';
})
```

This is going to be difficult to co-erce to a typed representation. It is ambiguous, and we might get it wrong. I.e. for the above example:
```css
.foo { background-image: paint(foo 0) }
```

A better way of doing this, is with a future parser API thingy. For example:
```
paint() = paint( <ident> <declaration-value>? )
```

```js
registerPaint(class {
  void paint(ctx, geom, styleMap, inputTokens) {
    const lengthTypedOM = inputTokens.parseLength(); // Pops tokens which is a length off.
    if (!lengthTypedOM) {
      // Fail.
    }
    const numberTypedOM = inputTokens.parseNumber(); // Etc.
  }
});
```
^ This would be very powerful for authors.

I think we should leave this out for FPWD, but leave it as an open issue, to wait until Parse API could support this.

**Comment by bfgeek** [comment]
Updated issue in: 7677ff9cf0d22c173e53ed51385c14db94faf554 .

**Comment by tabatkins** [comment]
This would have the same restrictions on grammar that we have for typed custom properties, with the same ambiguity-resolving behavior.

**Comment by shans** [comment]
New approach: will provide an argument syntax to paint registration. This will match the things that are allowed in properties & values, including '*', which is a token-stream. NOTE: This should be exposed as a string rather than a stream of tokens. By default will be nothing (no arguments).
