### ISSUE TITLE
registerPaint shouldn't invoke the constructor immediately

### ISSUE THREAD

**Issue by RByers** [w3c/css-houdini-drafts#102]
`registerPaint` takes a constructor function and [immediately invokes it](https://drafts.css-houdini.org/css-paint-api/#dom-renderworkletglobalscope-registerpaint).  If this is really what we want, then it might as well just take an instance, not a constructor (strictly more flexible).

Talking to @esprehn, he says the point of taking a constructor was to allow the class to maintain state (eg. caches) which the UA gets to control the lifetime of (eg. discarding when there's nothing present in the document or maybe visible on the page that will use the painter).  That makes a lot of sense.

But if that's what we want to allow, the spec should probably be written that way now, since it's not necessarily compatible (eg. developers could depend on `registerPaint` invoking the constructor, and it not getting invoked at other times).

**Comment by esprehn** [comment]
I think we might want to say the stuff you pass into paint() is constructor arguments, so doing:

paint(foo, 100, 200) creates an instance with (100, 200), and all usages with the same arguments are shared?

Instances live as long as there's at least one usage in the sheet, then they're available for GC.

**Comment by RByers** [comment]
What do you mean "one usage in the sheet"?  Having a style rule that applies to no elements will still create an instance?  What if the only elements are `display: none`?

**Comment by esprehn** [comment]
Sorry, one usage in the page, not the sheet.

**Comment by upsuper** [comment]
If any argument is animating, do we want to create a new instance and destroy it each frame?

**Comment by bfgeek** [comment]
Changed that a class is just constructed once in "draw a paint image". As @upsuper we probably don't want for a particular set of arguments as its bad if animating.

Fixed in d4a272ee6927ac3c1228779e3502a78d0a60a53e . 

Probably want to revisit how many classes at some stage for paint functions, but closing this direct issue for now.
