### ISSUE TITLE
[css-typed-om] remove `toGray()`

### ISSUE THREAD

**Issue by svgeesus** [w3c/css-houdini-drafts#1027]
In [4.6 CSSColorValue objects](https://drafts.css-houdini.org/css-typed-om/#colorvalue-objects), the method `CSSGray toGray();` should be removed, because [CSSWG resolved to drop the CSS Color 4 `gray()` function](https://github.com/w3c/csswg-drafts/issues/4621#issuecomment-572183475)

**Comment by tabatkins** [comment]
Oh, whoops, I guess I just didn't catch that it'd been removed. The removal definitely predates me adding this text. Deleted, thanks.
