### ISSUE TITLE
[css-typed-om] Fill out TODO in `toColor(colorspace)`

### ISSUE THREAD

**Issue by svgeesus** [w3c/css-houdini-drafts#1031]
In [4.6 CSSColorValue objects](https://drafts.css-houdini.org/css-typed-om/#colorvalue-objects), the `toColor(colorspace)` method states:

> 3. Convert this into a color in the colorspace specified by colorspace, and return a new CSSColor object with **TODO**.

This should be expanded out, at least to the basic level of detail of the other `toFoo` methods on the same object.

Suggested minimal text (still lacking references to how to actually do this):

> into a color in the specified colorspace, and return a new `CSSColor` object with its `colorspace`, `parameter value`s, and `alpha` internal slots set appropriately to represent that color.

**Comment by svgeesus** [comment]
I added a new [Converting between predefined RGB color spaces](https://drafts.csswg.org/css-color-4/#predefined-to-predefined) section to CSS Color 4, because expecting people to concatenate 
"Converting predefined color spaces to Lab" and "Converting Lab to predefined color spaces" while dropping the redundant steps is maybe a bit much (bad Chris)

https://github.com/w3c/csswg-drafts/commit/9bfab915093cb946c06f7aedc6bfa938b5a2ca47

So that would be a suitable reference for the conversion here.

**Comment by svgeesus** [comment]
Where is the fixed-up definition? Type OM as [only one commit in 2021](https://github.com/w3c/css-houdini-drafts/commits/main/css-typed-om/Overview.bs), in January.

**Comment by tabatkins** [comment]
ARGH MY LOCAL REPO WAS STILL PUSHING TO MASTER

Sorry, fixed, main is updated and pushed now.

**Comment by svgeesus** [comment]
Closed by

 - https://github.com/w3c/css-houdini-drafts/issues/1070
