### ISSUE TITLE
[css-typed-om] Move ".colorspace" to the color superclass, readonly

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#1036]
In <https://github.com/w3c/css-houdini-drafts/issues/1034#issuecomment-840494082>, Lea points out that it's annoying to figure out what the colorspace of a color object is. 

We already have precedent in Typed OM for helping with this - the math function subclasses expose their function name as a property as well, precisely to avoid this annoying hacky work.

Seems like the most straightforward fix is to move ".colorspace" to the `CSSColorValue` superclass, as a readonly property that's automatically set to the corresponding function name, and then make it writable on `CSSColor`.

(Conveniently, the CSSWG just resolved to drop the "lab" predefined color space for color(), so there's no clashes anymore. "rgb" (for `rgb()`) and "srgb" (for `color(srgb)`) will be *close*, but they're distinct.)

**Comment by tabatkins** [comment]
If we have this, then it also gives us an identifier we can use to make the `toX()` function generic, rather than having specialized names. That is, we can write `.to("rgb")` to get a `CSSRGB` object, or `to("rec2020")` to get a `CSSColor` object set to the rec2020 color space.

This would solve another problem Lea pointed out in the comment linked above, *and* would make it more consistent with the `.to()` function in CSSNumericValue, which is a nice bonus.

**Comment by svgeesus** [comment]
> If we have this, then it also gives us an identifier we can use to make the `toX()` function generic, rather than having specialized names. That is, we can write `.to("rgb")` to get a `CSSRGB` object, or `to("rec2020")` to get a `CSSColor` object set to the rec2020 color space.

That would be much better, yes.

It should be noted that the domain and range are unbounded, so that there is no hidden clipping or gamut mapping, when converting from one space to another (i.e. you can convert back without loss).

**Comment by svgeesus** [comment]
> Seems like the most straightforward fix is to move ".colorspace" to the `CSSColorValue` superclass, as a readonly property that's automatically set to the corresponding function name, and then make it writable on `CSSColor`.

So, the only object that allows this type of colorspace conversion is `CSSColor`?

And, there is both `.to("rgb")` and `.to("srgb"` which both do the same conversion, but give you different types of object?

**Comment by tabatkins** [comment]
> So, the only object that allows this type of colorspace conversion is CSSColor?

No, it would be on `CSSColorValue`, the superclass, where the `.toX()` methods currently live.

> And, there is both .to("rgb") and .to("srgb") which both do the same conversion, but give you different types of object?

Yup.

**Comment by LeaVerou** [comment]
I support this change and think it's an improvement over the current API, though `to("srgb")` and `to("rgb")` performing the same conversion but returning different object is pretty weird.
