### ISSUE TITLE
PHP `mysqli_connect()` error on Editor's Drafts

### ISSUE THREAD

**Issue by bramus** [w3c/css-houdini-drafts#1048]
Don't know where to report this, but here seems like a good place. When going to [the Editor's Draft of the “CSS Properties and Values API Level 1“](https://drafts.css-houdini.org/css-properties-values-api-1/) for example, I am currently being greeted by a PHP `mysqli_connect()` error 

<img width="1018" alt="Screenshot 2021-07-29 at 16 40 20" src="https://user-images.githubusercontent.com/213073/127512412-ba3b28aa-ef8f-479b-add6-55e0cfb23598.png">

**Comment by plinss** [comment]
Fixed
