### ISSUE TITLE
[css-typed-om] CSSTransformValue.is2D should be removed

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#1052]
Based on the CSSWG resolution in https://github.com/w3c/csswg-drafts/issues/3305#issuecomment-545532745 the `is2D` attribute of [`CSSTransformValue`](https://drafts.css-houdini.org/css-typed-om/#transformvalue-objects) should probably be removed.

Note that the edits for that resolution for individual transform properties have been made, but the edits for the `transform` property have not yet been made.

**Comment by tabatkins** [comment]
As far as I can tell, it needs to remain; while the individual transform properties are specified to "downgrade to 2d" when there's no non-trivial 3d component, the transform *functions* still retain 3d-ness even when trivial, so we still need the bool.
