### ISSUE TITLE
rename LengthValue.from{Value,Dictionary} to an overloaded from method

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#106]
1. I don't think we should be exposing the term "dictionary" to authors, as it's really just an internal spec term.

2. We can safely overload these two methods.

So how about having:

````
interface LengthValue {
  ...
  static LengthValue from(double value, LengthType type);
  static LengthValue from(CalcDictionary dictionary);
};
````

**Comment by heycam** [comment]
For that matter, any reason not to rename `parse` to `from` too?  It's just another way of providing the data required to construct a `LengthValue`.

**Comment by shans** [comment]
https://github.com/w3c/css-houdini-drafts/commit/5af56ec516461df98cc69eb92bafd12cf2093bc2
