### ISSUE TITLE
Should StylePropertyMap.set() wrap out-of-range values in a calc()?

### ISSUE THREAD

**Issue by cdumez** [w3c/css-houdini-drafts#1081]
Blink's implementation of StylePropertyMap.set() seems to have logic inside StylePropertyMap.set() to wrap out-of-range values in a `calc()` so that the operation succeeds instead of throwing.

For example. setting the `width` property to `-3%` would set it to `calc(-3%)`. This behavior is also covered by quite a few web-platform-tests (`css/css-typed-om/the-stylepropertymap/properties/width.html` for example).

However, I wasn't able to find any reference to this in the specification. Should this behavior get specified? Or should the tests get updated?

**Comment by smfr** [comment]
cc @tabatkins

**Comment by cdumez** [comment]
Actually, I did find spec text for this finally:
https://drafts.css-houdini.org/css-typed-om-1/#create-an-internal-representation

> If any component of property’s CSS grammar has a limited numeric range, and the corresponding part of value is a [CSSUnitValue](https://drafts.css-houdini.org/css-typed-om-1/#cssunitvalue) that is outside of that range, replace that value with the result of wrapping it in a fresh [CSSMathSum](https://drafts.css-houdini.org/css-typed-om-1/#cssmathsum) whose [values](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssmathsum-values) internal slot contains only that part of value.
