### ISSUE TITLE
[css-typed-om] Eagerly simplification in Typed OM

### ISSUE THREAD

**Issue by DevSDK** [w3c/css-houdini-drafts#1091]
css-values-4 [mentions](https://www.w3.org/TR/css-values-4/#calc-simplification) eagerly simplifying values and expressions. However, this seems unaddressed in the css-typed-om.

If a calc tree is constructed via Typed OM, do we need to eagerly simplify it for, eg, serialization?

**Comment by tabatkins** [comment]
No; it makes no mention of it because it doesn't happen. Simplification only happens as part of the CSS value computation process (specified -> computed -> used, etc).
