### ISSUE TITLE
[css-properties-values-api] Rule validity doesn't match implementations

### ISSUE THREAD

**Issue by emilio** [w3c/css-houdini-drafts#1098]
Implementations and tests blatantly disagree with the spec even in simple cases.

https://drafts.css-houdini.org/css-properties-values-api-1/#the-syntax-descriptor says:

> The [syntax](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-syntax) descriptor is required for the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule to be valid; if it’s missing, the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule is invalid.

https://drafts.css-houdini.org/css-properties-values-api-1/#inherits-descriptor:

> The [inherits](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-inherits) descriptor is required for the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule to be valid; if it’s missing, the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule is invalid.

https://drafts.css-houdini.org/css-properties-values-api-1/#initial-value-descriptor:

> If the value of the [syntax](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-syntax) descriptor is the [universal syntax definition](https://drafts.css-houdini.org/css-properties-values-api-1/#universal-syntax-definition), then the [initial-value](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-initial-value) descriptor is optional. If omitted, the [initial value](https://drafts.csswg.org/css-cascade-5/#initial-value) of the property is the [guaranteed-invalid value](https://drafts.csswg.org/css-variables-2/#guaranteed-invalid-value).
>
> Otherwise, if the value of the [syntax](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-syntax) descriptor is not the [universal syntax definition](https://drafts.css-houdini.org/css-properties-values-api-1/#universal-syntax-definition), the following conditions must be met for the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule to be valid:
>
> * The [initial-value](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-initial-value) descriptor must be present.
> * The [initial-value](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-initial-value) descriptor’s value must [parse successfully](https://drafts.css-houdini.org/css-properties-values-api-1/#consume-a-syntax-definition) according to the grammar specified by the [syntax definition](https://drafts.css-houdini.org/css-properties-values-api-1/#syntax-definition).
> * The [initial-value](https://drafts.css-houdini.org/css-properties-values-api-1/#descdef-property-initial-value) must be [computationally independent](https://drafts.css-houdini.org/css-properties-values-api-1/#computationally-independent).
>
> If the above conditions are not met, the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule is invalid.

Yet both Blink (and WebKit probably by copying whatever Blink implemented) disagree with it in trivial cases. E.g. [this](https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/11822) logs 0 per spec, but `1` in WebKit and Blink.

This is annoying because this affects a lot of interop 2023 tests. We have a implementation of this and as I was reviewing this to potentially enable it I found that all the tests are just broken.

Am I missing something? "rule is invalid" only has one meaning in my book, which is that the whole rule should be dropped, just like an `@font-face` and the

> Unknown descriptors are invalid and ignored, but do not invalidate the [@property](https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property) rule.

Makes me think that the spec agrees with my interpretation on what "validity" means here.

I _think_ this is ultimately a spec bug, as in https://github.com/w3c/csswg-drafts/issues/1682 it was decided to be consistent for `@counter-style` and `@font-face`.

cc @tabatkins @lilles @andruud

**Comment by andruud** [comment]
This was briefly discussed at some point. If I remember correctly, the behavior we intended was that "invalid" in most cases here means "does not lead to a property registration". But I can not find the discussion now. :(

**Comment by cdoublev** [comment]
Also noticed by @romainmenke in https://github.com/w3c/csswg-drafts/issues/9175 because an "invalid" `@property` still makes a following `@import` invalid.

Basically, it seems that people does not want a rule to be removed because its block contents is "invalid", right?

**Comment by tabatkins** [comment]
I don't recall having that discussion either (but that doesn't mean it didn't occur - my memory is notoriously faulty). Happy to either fix the spec to match impls or leave it and let impls get fixed, tho. I don't think I care too much how it goes, but making the actual rule invalid in simple grammatical failures like this *is* the more common behavior, and is what is generally meant by "X is invalid" across our specs.

Per blame, this text does come directly from @andruud (<https://github.com/w3c/css-houdini-drafts/commit/a5cd596795624c596911ecb7efda5de0f3652d89>) and was early in their spec-writing career, so it was likely just some loose wording.

**Comment by andruud** [comment]
> was early in their spec-writing career

Yeah, maybe I was just confused at the time.

> "rule is invalid" only has one meaning in my book, which is that the whole rule should be dropped

OK, then let's change WPTs to reflect that and I'll adjust our implementation.

**Comment by fred-wang** [comment]
One thing I forgot to mention is about the interpretation of invalid `inherits` values. It seems they should be dropped, so the descriptor would be missing and the full `@property` rule becomes invalid (similar to what the spec describes for the `syntax` descriptor). But the spec is not explicit about that and existing tests assume it would take value `false`.

**Comment by cdoublev** [comment]
> align the spec with `@counter-style` and `@font-face`, but I'm not sure what was the conclusion here

It does not seem usefull to preserve the rule in the CSSOM if it is invalid and cannot become later valid, since its attributes are read-only, as I noted it in https://github.com/w3c/csswg-drafts/issues/9417.

But if later people ask for updating these attributes via CSSOM, I think there would be a compat issue.

  > But the spec is not explicit about that and existing tests assume it would take value false.

And people seem to want `true` as the initial value (cf. #994), which would have to be defined in the descriptor definition table. Currently, it is `n/a (see prose)`.

**Comment by foolip** [comment]
FYI, I've filed https://github.com/web-platform-tests/interop/issues/587 about the test changes affecting Interop 2023. We have no CI enforcement that Interop 2023 tests aren't changed, but we do review any changes. Filing test change proposals before the changes are made is appreciated.

**Comment by emilio** [comment]
As per the above, it was discussed on another interop issue. Let's change this since implementations should start matching the spec shortly.
