### ISSUE TITLE
[css-properties-values-api] Add <string> as a supported syntax name

### ISSUE THREAD

**Issue by lilles** [w3c/css-houdini-drafts#1103]
We should add `"<string>"` as a valid syntax for custom property registration:

https://www.w3.org/TR/css-properties-values-api-1/#supported-names

Chrome got a [bug report](https://crbug.com/1466452) that `"<string>"` was expected to work for registered custom properties to be used in the content property.

**Comment by tabatkins** [comment]
Oh, huh, that's a weird omission. Yes, absolutely we should allow strings.

**Comment by SebastianZ** [comment]
For reference, Mozilla already [added parsing `<string>` today](https://bugzilla.mozilla.org/show_bug.cgi?id=1846635).

Sebastian
