### ISSUE TITLE
[css-typed-om-1] Combining a number and the division of two dimensions of the same type

### ISSUE THREAD

**Issue by cdoublev** [w3c/css-houdini-drafts#1117]
Should `min(1px / 1px, 1)` be valid?

Please forgive me if I am mistaken:

  - the type of `1px / 1px` is `[ length → 0 ]` and matches `<number>`
  - the type of `1` is `[]` and matches `<number>`
  - the result from determining the type of `min(1px / 1px, 1)` is a failure

Maybe step 6 of [*add two types*](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-add-two-types) should be:

```diff
- 6. If all the entries of type1 with non-zero values are contained in type2 with the same value, and vice-versa
+ 6. If all the entries of type1 with non-zero values are contained in type2 with the same value, and vice-versa, or if type1 and type2 only have entries with zero values or no entries
```

**Comment by tabatkins** [comment]
I'm not sure I understand. The text already covers this case - all the types with non-zero values (there are none) in type1 are also present in type2, and vice versa.

**Comment by cdoublev** [comment]
I guess *all* here is similar to `emptyList.every()` returning `true`, which is not natural to me. Sorry!
