### ISSUE TITLE
[css-typed-om-1] Republish WD

### ISSUE THREAD

**Issue by svgeesus** [w3c/css-houdini-drafts#1124]
The [ED of Typed OM](https://drafts.css-houdini.org/css-typed-om/) is dated  4 March 2024 while [the /TR version](https://www.w3.org/TR/css-typed-om-1/) is 10 April 2018.

I added the missing changes section:

 - https://github.com/w3c/css-houdini-drafts/issues/1046
 
 Let's publish an update.
 
 @tabatkins OK?
 
 @astearns Agenda+ to get a resolution (Houdini repo does not have the Async labels)

**Comment by astearns** [comment]
@svgeesus can we use https://wiki.csswg.org/spec/publish as the resolution?

**Comment by tabatkins** [comment]
Yes, I'm happy to do more publications for this.

(And I'm also happy to see you with so much activity on these specs; unfortunately I'm having to spend my time elsewhere right now so I can't match that right now. Next month, tho, I'll be able to be more present for these related topics.)

**Comment by svgeesus** [comment]
Publication requested 19 Mar, expected 21 Mar.

**Comment by svgeesus** [comment]
[Published 21 Mar 2024](https://www.w3.org/TR/2024/WD-css-typed-om-1-20240321/)
