### ISSUE TITLE
[css-properties-values-api] 2.8 Shadow DOM implies @property rules should work from shadow tree

### ISSUE THREAD

**Issue by Kaiido** [w3c/css-houdini-drafts#1128]
[2.8 Shadow DOM](https://drafts.css-houdini.org/css-properties-values-api/#shadow-dom) currently reads 

> All registrations, whether they appear in the outermost document **or within a shadow tree**, interact in a single global registration map for the [Document](https://dom.spec.whatwg.org/#document).

Which seems to imply that it's possible to make such a registration from a shadow tree. There is even a test for this: https://github.com/web-platform-tests/wpt/blob/master/css/css-properties-values-api/at-property-shadow.html 
However in https://github.com/w3c/css-houdini-drafts/issues/846 it's been decided that it shouldn't work from shadow DOM, at least for now. Implementations [seem to agree](https://wpt.fyi/results/css/css-properties-values-api/at-property-shadow.html) on this.  

Should the specs and test be edited?

**Comment by zrhoffman** [comment]
> Should the specs and test be edited?

The current discussion is in w3c/csswg-drafts#10541.

**Comment by Kaiido** [comment]
Oh, sorry I missed it moved to csswg-drafts. Thanks for the link.
