### ISSUE TITLE
[css-properties-and-values-api] consider making some PropertyDescriptor members required

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#115]
I don't think it make sense to call `registerProperty` with a `PropertyDescriptor` that lacks a `name`, `syntax` or `initialValue`. Should we make these three members `required`?

**Comment by heycam** [comment]
And maybe `inherits` can have a default value of `true`.

**Comment by shans** [comment]
I'd almost prefer inherits default to false, for perf reasons.

**Comment by shans** [comment]
syntax could default to '*' (which matches custom properties L1). initialValue to '' maybe?

**Comment by heycam** [comment]
Syntax defaulting to `"*"` is OK, I guess, although I think nearly all uses of `registerProperty` will be for providing a syntax.  An empty string is invalid for all custom properties, so I don't think it's so useful to specify `""` as an initialValue default.

**Comment by shans** [comment]
but invalid *is* the default for L1 custom properties..

**Comment by heycam** [comment]
That is true.  If we want to allow initial values to be invalid then we should remove the requirement that it be valid. :-)  Perhaps we only allow it for `"*"` syntax...
