### ISSUE TITLE
Put together a explainer doc for what the parser api should be able to accomplish

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/css-houdini-drafts#116]
Based on a short discussion, put together an explainer doc of what different use cases the parser API should be able to achieve.

Notes from the discussion today:

- The desire would be to provide access to the component values
- TypedOM will have a .parse() method which will take a string and convert it to a styleValue subclass
- Being able to extend the parser in a manner where the grammar is correct but the browser's error handling throws it away
- Offer the capabilty to switch on/off various amount of error handling

**Comment by gregwhitworth** [comment]
Ok, I pushed the basic explainer. I plan to give actual examples of each, and what I would like returned so that we can determine if @shans TypedOM .parse() will accomplish what we need or where it needs to be extended. Additionally it would be good to get @tabatkins opinion on the basic functionality of utilizing the parser since he has a deep understanding of the possible implications of this, if any.

**Comment by gregwhitworth** [comment]
@philipwalton we do have the usecase you want above - I think it would be good to put it into the explainer with a decent example.

**Comment by philipwalton** [comment]
@gregwhitworth sorry for losing track of this issue; is this still relevant now that https://github.com/WICG/CSS-Parser-API#use-cases is published?

**Comment by gregwhitworth** [comment]
@philipwalton Yeah I think this can be closed.
