### ISSUE TITLE
[css-properties-and-values-api] exception thrown by unregisterProperty

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#119]
Should `unregisterProperty` throw SyntaxError when the string passed is not a valid custom property name (just like `registerProperty` does)?

**Comment by upsuper** [comment]
It could just throw `NotFoundError`?

**Comment by heycam** [comment]
Yes, that would be a better exception (for both methods).

**Comment by shans** [comment]
This was already in the spec!
