### ISSUE TITLE
[Global] and [Exposed] IDL

### ISSUE THREAD

**Issue by zcorpan** [w3c/css-houdini-drafts#120]
`WorkletGlobalScope` needs `[Global=Worklet,Exposed=Worklet]` and all other stuff needs `[Exposed=Worklet]`, I believe.

cc @heycam @bfgeek

**Comment by heycam** [comment]
It's been too long since I looked at how `[Exposed]` works; nothing needs to be done in the IDL side to allow that.

**Comment by bfgeek** [comment]
I think I fixed this with: e422068ecb32478c81f4ee7e48d3a8351cf39fb7 .

I was following the style of https://html.spec.whatwg.org/multipage/workers.html#workerglobalscope .

`WorkletGlobalScope` only gets `Exposed=Worklet`.

Final global scopes (`FakeWorkletGlobalScope`) get `Global=(FakeWorklet,Worklet),Exposed=FakeWorklet`
