### ISSUE TITLE
[css-properties-and-values-api] should initial values be allowed to have variable references?

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#121]
What would it mean for a custom property's initial value to have a variable reference in it?  It doesn't sound useful.  Should it make `registerProperty` throw an exception?

**Comment by shans** [comment]
in general, values that can't be directly represented as computed values seem weird. For example, specifying '4em' as an initial value would mean that:

(1) if the property is not inherited then it would need to compute 4em for every element
(2) if the property *is* inherited then the root would compute a result for 4em and the result would
be inherited down the tree.

**Comment by shans** [comment]
See also #122

**Comment by tabatkins** [comment]
Fixed in 321c596.
