### ISSUE TITLE
[css-properties-and-values-api] relative <length> values in initial value

### ISSUE THREAD

**Issue by heycam** [w3c/css-houdini-drafts#122]
If you register a custom property with syntax `<length>` and with an initial value of `"2em"`, what is the computed value of that initial value?  Would it be resolved against the font-size of every element that has that custom property set to initial?  For a non-inherited custom property that could easily be every element in the document.

I don't think any built-in properties have initial values that are relative to other properties, and it feels a little strange, although I am not sure if it is truly problematic.

**Comment by tabatkins** [comment]
I think we should probably reject non-absolute units in initial values.  You can always smuggle it in via a keyword, which is done in multiple places in CSS.

**Comment by fantasai** [comment]
Yes, that is how it would work if you did that. No opinion on whether it should be allowed.

**Comment by shans** [comment]
We're going to limit computed value to absolutes for now. There seems to be too much potential for confusion about what relative values would actually do.

**Comment by tabatkins** [comment]
Fixed in 321c596; I defined what "computationally idempotent" actually means.
