### ISSUE TITLE
[worklets] consider "omit" for the CORS setting?

### ISSUE THREAD

**Issue by domenic** [w3c/css-houdini-drafts#128]
"anonymous" passes credentials same-origin, but by default (e.g. for module workers, and for fetch()) we're trying to go with no credentials these days. If you want to allow customization of this in the future, you can do it with the Worklet import method, similar to https://github.com/whatwg/html/pull/608

Also, minor nit: in https://github.com/whatwg/html/commit/7a0ce073a8fbade8f44d0e2d4c709ad7cf3ee312 I changed the algorithm slightly so instead of "for the CORS setting attribute" you should say "for the credentials mode".

**Comment by bfgeek** [comment]
This was fixed a while ago to default to "omit", and now accepts an option to set the credentials.
