### ISSUE TITLE
[worklets] import() with no arguments does not do what you think it does

### ISSUE THREAD

**Issue by domenic** [w3c/css-houdini-drafts#129]
> If there are no arguments, return without doing anything. Abort these steps.

This will never be hit, because the argument was not declared as optional, so doing `myWorklet.import()` will be equivalent to `myWorklet.import("undefined")`. Which, IMO, is fine; I'd just remove this step and let them get the error trying to import that file.

**Comment by bfgeek** [comment]
Fixed in a2144b9980c9704163966e5e1a01bad6b82c7fce .
