### ISSUE TITLE
[css-paint-api] Shaders instead of scripts

### ISSUE THREAD

**Issue by ghost** [w3c/css-houdini-drafts#130]
Hello. I suggest make very original feature: CSS background shaders. And shaders of OpenGL ES 3.0. Also, I suggest forbid use vertex shaders, only fragment. If this is theme of CSS4, please, merge this suggestion to CSS4 (or CSS4.1). 

Syntax: 

```
  background-image: custom( /* Forgot CSS custom filter (shaders) syntax */ );
```

Features: 
- Same syntax as CSS custom filters
- Shaders used for painting 
- Not require JS
- Much faster
- Much powerfull

**Comment by tabatkins** [comment]
We don't take issues from ghosts.
