### ISSUE TITLE
[css-paint-api] Explicitly state that PaintRenderingContext2D should be transparent by default.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#134]
Instead of being default blank/white.

**Comment by tabatkins** [comment]
Specifically, state that until it gets a successful paint, it represents an [invalid image](https://drafts.csswg.org/css-images/#invalid-image). That takes care of the default rendering, *and* hooks into the error machinery for other things (like using a fallback color via image() before the first paint).

**Comment by bfgeek** [comment]
\o/

**Comment by bfgeek** [comment]
Added in f7c8a38f487a7d719573cccf085f3e312b09c852.
