### ISSUE TITLE
[css-properties-values-api] Allow custom property descriptors with a CSS @-rule

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/css-houdini-drafts#137]
The incredible flexibility of CSS Variables / Custom Properties introduces limitations compared to regular properties. By default they:
- cannot be interpolated in animations & transitions
- disable any parser-based type checking when used as a `var()`
- cannot have a default value, fallbacks must be specified each time a `var()` is used

The [CSS Properties Values API](https://drafts.css-houdini.org/css-properties-values-api/) addresses all these limitations, but requires script to run to do so.  This will cause async issues (CSS having to be re-parsed after script runs) and is no use at all in cases where scripts are disabled for security reasons (e.g., SVG-as-image).

While the general argument for using JS APIs for Houdini has been discussed in #86, I think property declarations are a special case.  This isn't about declaring functionality that needs to be represented as script functions; it's merely declaring a data object.  An @-rule of descriptors and values seems a perfect fit:

``` css
@property --highlight-color {
  syntax: "<color>";
  initial-value: red;
  inherits: true;
}

@property --gap-spacing {
  syntax: "<length-percentage>";
  initial-value: 1em;
  inherits: false;
}
```

It would of course be preferable to always have `@property` rules earlier in the CSS parsing sequence than any declarations using those properties.  However, since it is also going to be possible to set property declarations asynchronously with the API, I don't think this would need to be an enforced syntax rule, just a performance recommendation.

The effects of this declaration would be the same as for a declaration via the API.  E.g., If `initial-value` isn't specified, it would get the "nothing" initial value described in [CSS Custom Properties](https://drafts.csswg.org/css-variables/#defining-variables), with the resulting implication for `var()` function fallbacks.  

The API currently advises throwing an error if the provided initial value doesn't match the provided syntax.  For a `@property` declaration, I would recommended simply dropping the non-conforming initial value declaration.  This could allow multiple declarations with standard CSS fallback methods, e.g., for new functions that might not be recognized:

``` css
@property --highlight-color {
  syntax: "<color>";
  initial-value: red;
  initial-value: lighten(maroon);
  inherits: true;
}
```

**Comment by FremyCompany** [comment]
Thanks Amelia for bringing this in.

I am 100% in favor of this. In fact, I am 100% in favor of removing the JavaScript API and replace it by this CSSOM API (or, alternatively, have the JavaScript API create such a declaration for you, and append it to some special author stylesheet). 

The reason I am 100% in favor of this change is that, if we want to allow the CSS Parser to understand new CSS syntax constructions, it will be impossible to do that via script properly, we will need to do this in the CSS file. I believe we should therefore be coherent and move every CSS extension declaration in the CSS file itself.

**/!\ Potential issue**
A point your proposal does not touch is what happens if multiple declarations cover the same property. I think it should be an error whose effect is that none of the declarations are applied, if any of the declarations is different from the other (as in, only perfect duplicates are allowed). Authors must ensure they don't include multiple conflicting declarations in their stylesheets. User agents should warn when dropping such conflicting declarations in their console.

A possible variant would be that only mission-critical fields would cause the drop (so, while "syntax" and "inherits" must be the same, the "initial-value" can vary, in which case the initial-value defined last would win).

What do you think?

**Comment by AmeliaBR** [comment]
Regarding duplicates: why not adopt the usual CSS "last rule wins" approach?  That's what happens with [overloaded `@keyframes` rules](https://drafts.csswg.org/css-animations-1/#keyframes).  Note that the _entire_ @-rule would be replaced, no attempt to merge two different versions.

As far as integrating the API with declarative syntax:  I think it would be preferable to still have an API option, but it would definitely need to be integrated in a CSSOM-friendly way.  This could effectively mean creating an extra system stylesheet of generated `@property` rules (at the end of the cascade, so having precedence).

A few more issues:

- Would an `@property` rule in a CORS-protected stylesheet affect stylesheets from a different domain (or vice versa)?

- What other API calls are needed? E.g., it would be useful to include a way to retrieve all registered property declarations (whether registered via CSS or JS) & a way to delete or modify them (or maybe just over-ride them with a new rule, to avoid issues if the original is CORS-protected).

- Should this API also be able to retrieve (read-only) property declarations for native properties? Could be useful for building dev tool extensions.

**Comment by tabatkins** [comment]
Yup, a declarative syntax is definitely in the cards, more or less matching what you have here. We'll prove it out in the JS library first, making sure we're not missing anything, then backfill it so you can use typed custom properties in Animations and the like without having to invoke JS.

**Comment by AmeliaBR** [comment]
Thanks for the update @tabatkins. So this would be a CSS Custom Properties Level 2 feature?

I'll have to do a more careful read-through of the Houdini spec to identify any fussy issues; I really want this to move along fast! CSS Variables without animation & transitions are very limited for many of the SVG paramaterization uses I'd like to see.  (And for UX theming, too, of course.)

**Comment by tabatkins** [comment]
> So this would be a CSS Custom Properties Level 2 feature?

Most likely, yeah, unless we feel like we've nailed it for sure real quick.

> CSS Variables without animation & transitions are very limited for many of the SVG paramaterization uses I'd like to see. (And for UX theming, too, of course.)

Don't I know it!

To hit some of your other issues:

> Would an @property rule in a CORS-protected stylesheet affect stylesheets from a different domain (or vice versa)?

Yeah, should work just fine.  The only thing we do differently for cross-origin sheets is hide their precise text; we apply their effects just like normal.

> What other API calls are needed? E.g., it would be useful to include a way to retrieve all registered property declarations (whether registered via CSS or JS) & a way to delete or modify them (or maybe just over-ride them with a new rule, to avoid issues if the original is CORS-protected).

You can just walk the sheets to find ones that show up in same-origin or CORS'd sheets.  This doesn't help you with cross-origin (non-CORS'd), but eh, same is true of every other CSS feature.

You can override declarations by just putting in another one, after the one you want to override, regardless of where it came from.  (That is, last will always win, with full overriding, not cascading individually.  Same as, for example, `@counter-style`.)

> Should this API also be able to retrieve (read-only) property declarations for native properties? Could be useful for building dev tool extensions.

Don't think we need any special API beyond the existing OM-walking.  (Or if we do, we need it in a generic sense anyway, so it's not specific to this proposal.)

**Comment by vitaliy-bobrov** [comment]
I've published PostCSS plugin that transforms custom property declaration in CSS file to JavaScript `CSS.registerProperty`.
https://www.npmjs.com/package/postcss-register-custom-props

**Comment by LeaVerou** [comment]
Now that it's been 2.5 years since we last discussed this, the Properties and Values API has been tested by more developers, and it doesn’t look like we've missed anything huge, any chance we could revisit this? Perhaps in the upcoming TPAC F2F?

I've lost count of how many authors have asked me about this in the last year or so that custom properties have increased in popularity.

**Comment by chharvey** [comment]
The only thing I would suggest is change `initial-value` to `initial` and change `inherits` to `inherited`. Simply because (1) `initial` is shorter, and (2) the property itself is either inherited or not; it does not inherit anything.

**Comment by FremyCompany** [comment]
@chharvey We try to use the same name as the existing houdini function, which at this points are already frozen. https://drafts.css-houdini.org/css-properties-values-api/

**Comment by tabatkins** [comment]
Yeah, using the exact same name as `registerProperty()` (modulo the camelCase to kebab-case conversion) is a hard requirement.

**Comment by Snugug** [comment]
Hey! It looks like this declarative syntax isn't in the current version of the draft (Nov 9, 2018) but looks like y'all agreed to add it on October 25th. Curious what the delta is. I really love this syntax!

**Comment by andruud** [comment]
@Snugug I'll propose [something](https://github.com/andruud/css-houdini-drafts/commit/05f34766efb4ef9fc5f5b18c71c3d25196c36f53) soon ... ish.

**Comment by Snugug** [comment]
@andruud saw your PR! 🎉! Question about using this new syntax, specifically around creating properties with specific allowable idents. I've got the following registered property:

```js
CSS.registerProperty({
  name: '--theme-color',
  syntax: 'blue|green|red|yellow|grey',
  inherits: true,
  initialValue: 'blue',
});
```

Would that then convert in to 

```css
@property --theme-color {
  syntax: blue|green|red|yellow|grey;
  inherits: true;
  initial-value: blue;
}
```

Or would the separate possible idents be space separated, or be in quotes? What about the initial value? Should that be in quotes?

**Comment by andruud** [comment]
@Snugug What @AmeliaBR originally suggested, and what I proposed in the PR, would be:

```
@property --theme-color {
  syntax: "blue|green|red|yellow|grey";
  inherits: true;
  initial-value: blue;
}
```

I.e. the `syntax` is parsed as a string, requiring quotes (I assume, haven't read every word of css-syntax). The `initial-value` is parsed as a token stream, just like custom property declarations. In your example `blue` is correct, without quotes.

**Comment by LeaVerou** [comment]
> And what if the syntax contains quotes? How are they escaped?

Same as everywhere else in CSS, with a slash.

**Comment by AmeliaBR** [comment]
> > And what if the syntax contains quotes? How are they escaped?
> 
> Same as everywhere else in CSS, with a backslash.

Or by using a different quote type (single vs double).

But, as [currently defined](https://drafts.css-houdini.org/css-properties-values-api/#supported-syntax-strings), there is no valid syntax string that contains internal quotes, unless they were escaped inside a keyword token. To represent a quoted string value, you'd use `"<string>"`. E.g., a syntax matching the `quotes` property would be declared with `syntax: "none | [ <string> <string> ]+"`.

**Comment by Pachecomariarub** [comment]
Ayuda
