### ISSUE TITLE
[css-typed-om] add detailed descriptions of the rest of the methods on StylePropertyMap

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#148]

**Comment by nainar** [comment]
@tabatkins

**Comment by shans** [comment]
This comprises the following list:
* get a value from a StylePropertyMap
* set a value on a StylePropertyMap
* getAll
* has
* delete

**Comment by nainar** [comment]
The last one in this list was pull request 451. Closing this issue now.
