### ISSUE TITLE
[css-typed-om] Describe that StylePropertyMaps are not live objects

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#149]

**Comment by nainar** [comment]
@tabatkins

**Comment by jyc** [comment]
What does this mean? If a CSS declaration or inline style is otherwise modified (say, through JS), does the specified or inline StylePropertyMap update? What happens if we then call StylePropertyMap::append, for example? Do we append to the declaration or inline style based on its current value while appending to the StylePropertyMap's value based on what it was created with? What does the iterator give us for that property?

**Comment by jyc** [comment]
Found a definition of "live object" here: https://dom.spec.whatwg.org/#concept-collection-live .
Is this the correct definition? If so, and these are not live objects and therefore do not "operate on the actual underlying data, not a snapshot of the data," what is the point of mutable StylePropertyMpas?

**Comment by shans** [comment]
To clarify, this is saying that StylePropertyMaps won't update based on style changes from other sources:

```
var map = el.styleMap;
map.get('height') // for argument's sake, CSSSimpleLength(100, 'px')
el.style.height = '200px';
map.get('height') // will still return CSSSimpleLength(100, 'px')
```

It might actually be reasonably simple to support live maps for specified objects but for computed styles this gets quite expensive, and it seems best to be consistent.

**Comment by shans** [comment]
feedback from jyc on irc: this should probably be true only for computed maps, not specified maps.

**Comment by tabatkins** [comment]
Ah, that's probably fine. I was getting a little confused why .set() worked but wasn't live - there's clearly still a communication channel there.  (This doesn't really need to be "live", per se, it's just that .get() goes and gets the value off of the element.)

So yeah, the Readonly version is non-live.

**Comment by dbaron** [comment]
Resolved to be live [for specified](https://log.csswg.org/irc.w3.org/houdini/2016-09-22/#e727261) and [for computed](https://log.csswg.org/irc.w3.org/houdini/2016-09-22/#e727285) style maps.

**Comment by shans** [comment]
The only map that's left is the inline map. We didn't specifically talk about this during the spetember f2f but it seems it should be live too. OK for me to close this issue as invalid?
