### ISSUE TITLE
[css-typed-om] Spec up ColorValue

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#159]

**Comment by nainar** [comment]
@tabatkins

**Comment by shans** [comment]
This should probably be a different class for each of the broad color types, along with converters between the different classes.

**Comment by kenchris** [comment]
Maybe it should not be prefixed with CSS and it would probably make sense using the same across Web and Node.js and many APIs needs to deal with color. Maybe this could even go into JS proper at some point. @anssiko

**Comment by grorg** [comment]
I can't imagine that ES-whatever would accept a proposal for a Color type. I can't think of any other language that has that as a primitive (maybe PostScript?).

It's probably better to focus on just the CSS OM use case.

**Comment by nainar** [comment]
After discussing this with Tab the suggestion is to adopt the strategy [here](https://github.com/w3c/csswg-drafts/commit/85434cb3e0cfa862045ef5178e1720b9ad593d1f#diff-1b39a8c21cc4d6d69673bf20b5226d33) which adds different classes for all the different ways we can represent color, for example hsl, rgba, lab, etc in Typed OM 1.

In Typed OM 2 we can look at adding extensible functions/objects which was also part of this change.

**Comment by nainar** [comment]
@dbaron and @gregwhitworth WDYT here?

**Comment by gregwhitworth** [comment]
@nainar in the link you provided, I see a ton of deleted spec text, with some additional JS lines of JS. Am I supposed to read the deleted spec text as your proposal for L1 of TypedOM? Sorry for the confusion.

**Comment by tabatkins** [comment]
Yeah, the section that was deleted there.  (To see it in-spec, check out that commit's parent, then run bikeshed on it.)  Proposal is to spec up a CSSColorValue abstract base class (like CSSNumericValue, only to group some related methods), and then individual classes corresponding to each of the color functions, with easy inter-conversion between them.

(Since everything but device-cmyk() has a colorspace associated with it, interconversion is pretty simple.)

**Comment by plinss** [comment]
...or click the history icon (rewinding clock) on the draft server home page to see the complete list of a draft's pushes and click the date/time link to see any previous version as generated by bikeshed at the time.
e.g.: https://drafts.css-houdini.org/history/css-typed-om/

Or just use a dated url to see a draft at any particular time, e.g.:
https://drafts.css-houdini.org/date/2016-09-13T00:33:42/css-typed-om/
or
https://drafts.css-houdini.org/date/2016-09-13/css-typed-om/

No need to run bikeshed locally on previous versions (the dated/history urls also give you the output that the version of bikeshed and the spec database generated at the time, as opposed to running a current bikeshed on an old spec).

**Comment by nainar** [comment]
Moving this to Level 2 since this needs speccing and feedback and is risky.

**Comment by mnpenner** [comment]
I hate to be that guy, but it's been two years. Any updates you guys can share with us?

**Comment by svgeesus** [comment]
Perfectly reasonable to ask what is up!

There was [good discussion](https://github.com/w3c/css-houdini-drafts/issues/989#issuecomment-667228353) at the [June 2020 virtual face to face meeting](https://wiki.csswg.org/planning/virtual-summer-2020) which was mostly in the context of [color conversion code in Type OM](https://github.com/w3c/css-houdini-drafts/issues/989). Here are [the minutes](https://lists.w3.org/Archives/Public/public-houdini/2020Aug/0002.html).

**Comment by svgeesus** [comment]
So [ColorValue]() now appears to be well specced-out.

Close?
