### ISSUE TITLE
[isolated-workers] Specify what happens when a script in an isolated worker throws an error.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#16]
We need to be ability to report this error to a monitoring server or similar.

There should be an "onerror" handler on the main script handle for the worker(s).

For example:

```
// IsolatedWorkerGlobalScope
throw new Error('hi!');
```

```
// main execution context.
window.paintWorker.addEventListener('error', function(event) {
  // Do something with the error here. Report to a monitoring server or similar.
});
```

**Comment by bfgeek** [comment]
One really large issue here, is that this suddenly creates a communication channel back to the main thread. This API will be abused to check if for example something has been painted (except that if an exception was thrown -- it wasn't painted).

Is there a good way to mitigate this, and still provide error reporting?

**Comment by padenot** [comment]
There need to be communication channels back to the main thread regardless, is that not planned ?

**Comment by bfgeek** [comment]
For style/layout/paint in particular if you expose a communication channel from isolatedWorker -> mainJavascript you have exposed additional information which isn't currently exposed to developers.

For example for custom paint, you can now determine which items the UA has actually* painted. Is this a bad thing? Not sure.

At TPAC I want to talk to a bunch of people about this issue, and see if its ok or not.

Other specs, I.e. audio worker could extend IsolatedWorkerGlobalScope to incorporate a postMessage interface.
I.e.
```
AudioGlobalScope : IsolatedWorkerGlobalScope {
  void postMessage(Object message);
  void registerAudioNode(DOMString name, Function nodeCtor);
};
```

[*] for some definition of actually.

**Comment by padenot** [comment]
Right. Sorry I was not aware of this particularity of style/layout/paint, we totally can implement that down the inheritance tree, hopefully having an interface that share the very common task of sending back info to the main thread.

**Comment by bfgeek** [comment]
No worries. I'm not sure if it's a real issue yet, but my gut feeling is that it probably is.

With feedback from other vendors we'll be able to decide if back communication channel is able to happen or low-bandwidth back communication channel.

**Comment by bfgeek** [comment]
So I'm going to close this as it doesn't seem needed at the moment - audio have set up their communication channel. We may want an out-of-band channel for the houdini worklets (something similar to report-uri for CSP) at some point - so we'll revisit once needed.

At the moment errors will just be logged to the console.
