### ISSUE TITLE
Reconsile with Frozen Realms

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#177]
https://github.com/FUDCo/frozen-realms seems quite similar to a Worklet. We should probably not have two fairly isolated realm concepts in the platform.

**Comment by shans** [comment]
Frozen realms introduce a bunch of restrictions (frozen globals, etc.) that mean most/all existing JS libraries won't run, right? That makes them a pretty bad fit for Houdini.

**Comment by shans** [comment]
No further update on this so I'm going to close it.
