### ISSUE TITLE
[css-paint-api] Spec what happens when inputProperties contains an invalid property?

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#179]
I believe ignore?, as author might be using for progressive upgrade, i.e.

```js
registerPaint('foo', class {
  static inputProperties = ['--qr-code', 'qr-code']; // Supports a native property at some stage.

});
```

**Comment by tabatkins** [comment]
Yeah, I think just ignore the unknown property; you can test what's in your dict and act accordingly.

**Comment by bfgeek** [comment]
Added note that unknown properties are ok in 93440c0851c8a8e56951254bc4b65293b1a38675.
