### ISSUE TITLE
[css-paint-api] Spec what happens when inputProperties contains a shorthand.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#180]
So the typed-om isn't going to support shorthands...
https://drafts.css-houdini.org/css-typed-om/#mapping-of-properties-to-accepted-types

We should drop these similar to an invalid property? + console.warn('Shorthands aren't supported').

**Comment by tabatkins** [comment]
Nooooope, we need to revisit that decision. If we don't support shorthands, we *will* break things in the future.  Properties later becoming shorthands is an accepted type of property evolution (like properties later becoming list-valued, etc).

This is one of the reasons the DOM Level 2 Style API was a failure - it returned `null` for shorthands, which means that previously-working code broke when their API calls suddenly started returning `null` as browsers supported newer versions of specs.

(I'll open a thread on the OM specifically.)

**Comment by bfgeek** [comment]
Added note in 93440c0851c8a8e56951254bc4b65293b1a38675 that shorthands are ok.
