### ISSUE TITLE
Typed OM *must* support shorthands

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#181]
This is one of the reasons the DOM Level 2 Style API was a failure - it returned null for shorthands, which means that previously-working code broke when their API calls suddenly started returning null as browsers supported newer versions of specs.  Properties starting out simple and later expanding and becoming shorthands is an accepted mode of property evolution in CSS that has happened several times in the past.

**Comment by shans** [comment]
Agreed.

Do you think we can leave this until level 2? For now shorthands would return CSSTokenStreamValues (i.e. our catch-all unsupported value) so they wouldn't be null, and we can work out a better object representation later?

**Comment by tabatkins** [comment]
CSSTokenStreamValue isn't a catchall; you can't currently upgrade from it into anything else, because you lose the `iterable<>`.  But we could just expose them as raw CSSStyleValues, sure.

As long as we have a good upgrade story, such that (a) existing shorthands can be given real types in the future, without breaking anything, and (b) existing longhands can be made into shorthands later, then I'm happy.  It looks like this will work, so 👍 .

**Comment by shans** [comment]
CSSTokenStreamValue not being upgradeable is a good point.

Do you think it's worth having an explicit CSSUnsupportedStyleValue, or is just using raw CSSStyleValues sufficient?

**Comment by tabatkins** [comment]
I don't think an explicit "unsupported value" would do anything different than just CSSStyleValue.  No sense adding complexity when it's not warranted.

**Comment by upsuper** [comment]
> (a) existing shorthands can be given real types in the future, without breaking anything

It isn't clear to me how does the spec achieve this currently?

**Comment by shans** [comment]
For example, 'border' doesn't have an explicit type yet. So right now, given:

<style>
#el {
  border: 40px solid red;
}
</style>

el.styleMap.get('border') will return a CSSStyleValue that contains a cssText string value of "40px solid red".

When we do spec up a CSSStyleValue subclass for the border shorthand, e.g.

interface CSSBorderValue : CSSStyleValue {
  CSSBorderSideValue left;
  CSSBorderSideValue right;
  CSSBorderSideValue top;
  CSSBorderSideValue bottom;
};

or whatever, then any code that fetches the 'border' key out of the style map and expects it to be a raw CSSStyleValue will continue to work unaltered.
