### ISSUE TITLE
[css-paint-api] How I can draw videos?

### ISSUE THREAD

**Issue by acterhd** [w3c/css-houdini-drafts#183]
Hello. I have question. How I can draw videos on CSS Paint API? I mean `<video>` content on CSS background.

**Comment by upsuper** [comment]
Probably via the same interface as drawing image somehow, but I have no idea how that can be specified.

Alternatively, just use some kind of animated image formats there, then we don't need any new interface.

**Comment by acterhd** [comment]
Better implement ImageDecoder API!

**Comment by tabatkins** [comment]
We want to address this eventually, but it's almost certain to be deferred to a future level; handling videos in a Worklet context will be non-trivial.

I'll go ahead and close this for now.
