### ISSUE TITLE
Do any StyleValue subclasses other than LengthValue need a 'from' method?

### ISSUE THREAD

**Issue by rjwright** [w3c/css-houdini-drafts#185]

**Comment by tabatkins** [comment]
LengthValue just has constructors, not a static `.from()`, right?

Anyway, yeah, all the dimension classes need to have the same constructor/whatever shape.

**Comment by shans** [comment]
Note: all the dimension classes need calc variants, which means we'll need static .from() methods too.

**Comment by shans** [comment]
We don't need .from() methods unless there are multiple subclasses of an abstract type base (like LengthValue). So for example CSSAngleValue doesn't need .from() methods.

However we should make sure that there are constructors available for string and calc variants everywhere.

**Comment by shans** [comment]
CSSNumericValues are now the base of lengths, angles, etc. and have a standard .to() method, so this issue no longer applies.
