### ISSUE TITLE
[css-worklets] [css-typed-om] CSSResourceValues constructed within Worklets should have state "unloaded".

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#186]
Not sure which spec this needs to be in.

**Comment by shans** [comment]
@bfgeek do we need language in typed OM to deal with this?

**Comment by nainar** [comment]
@bfgeek oi!

**Comment by nainar** [comment]
Given that when you construct a CSSResourceValue on the main thread it's initial state is unloaded that is all the typed OM spec needs. 

Any worker specific logic should be on the Paint Worklet end of the spec no?

Marking as so for now. Feel free to change if needed.

**Comment by bfgeek** [comment]
Seeing as this type doesn't exist anymore closing :-P

We'll have to make sure we deal with this when we add it again.
