### ISSUE TITLE
[css-typed-om] CSSTokenStream values need to computed to other values in some cases

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#192]
Spec currently says that compute to another CSSTokenStream, just with all the variables resolved. This is true for custom properties, but when any other property is a CSSTokenStream, the computed value is whatever types that property normally has.

**Comment by shans** [comment]
It's not even true for custom properties that have a registered type.

**Comment by shans** [comment]
I think the spec actually doesn't say this at all. I rewrote the section to be a lot clearer though.

**Comment by shans** [comment]
@tabatkins ptal at attached pull request

**Comment by shans** [comment]
Closed via #296
