### ISSUE TITLE
[css-paint-api] Make prexfixes allowed.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#194]

**Comment by upsuper** [comment]
What is the reason reverts the decision in #184?

**Comment by tabatkins** [comment]
The WG argued that there was no technical reason behind this restriction.  The fact that WebAnim has the exact same restriction was not convincing enough. :/

**Comment by bfgeek** [comment]
Fixed in: 1688f3212c6867dcd44a5057d5c205d6848657de.
