### ISSUE TITLE
[css-properties-values-api] <length> value looks too much like an HTML element, confusing for authors

### ISSUE THREAD

**Issue by tantek** [w3c/css-houdini-drafts#197]
The use of "&lt;length&gt;" in the properties and values syntax looks confusingly too much like an HTML tag. We don't like it, and would like to consider alternatives. Input welcome.

**Comment by shans** [comment]
The "<length>" syntax is CSS meta-syntax, and there's a strong concern that it's going to be difficult to learn for web authors.

One alternative would be some kind of explicitly constructed object tree, using for example the typed OM constructors are leaves.

**Comment by tabatkins** [comment]
We really can't do anything else.  The group discussed using the constructors directly to represent types, but that's really bad. Some types aren't represented by distinct constructors (unless, I guess, you represent `<length-percentage>` with `CalcLength`), and the grammar operators have no direct analog in JS (we discussed just using an array to represent `|`, but there's no way to represent `+`, `*`, `?`, `||`, `&&`, etc without inventing new JS constructors solely to represent them).

Not all authors are familiar with the CSS property grammar syntax.  But a lot are, and it's the best we have.  Inventing an *entirely new* grammar just for this, that has the exact same powers as CSS's syntax, would just be gratuitous and silly, obviously.

So, closing as no change right now.  The spec as it stands is the best we can do.
