### ISSUE TITLE
[css-layout-api] ConstraintSpace needs more data members

### ISSUE THREAD

**Issue by atanassov** [w3c/css-houdini-drafts#200]
We're missing information about percent value resolution in the constraint space. Perhaps something like:
interface ConstraintSpace {
    attribute double? width;
    attribute double? height;
    attribute double? widthPercentConstraint; 
    attribute double? heightPercentConstraint; 
. . .
}

**Comment by bfgeek** [comment]
These now exist in the latest version of the draft specification.
