### ISSUE TITLE
[css-paint-api] Add inputArguments to paint API

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#219]
Syntax...

``` js
registerPaint('foo', class {
  static get inputArguments() { return ['<length>', '<number>']; }

  paint(ctx, geom, styleMap, args) {
    args[0] instanceof CSSLengthValue; // true
    args[1] instanceof CSSNumberValue;  // true
  }
});
```

**Comment by bfgeek** [comment]
```js
background-image: paint(foo, 2px, keyword);
```

**Comment by dmvaldman** [comment]
If this notation is adopted, is the `inputArguments` getter still necessary?

If that method is for caching purposes, it seems it wouldn't be necessary as you'd know when the cache is busted because this new notation explicitly defines the input arguments.

**Comment by tabatkins** [comment]
I'm confused by your question - did you mean to refer to something else?

The `inputArguments` getter specifies the types of the arguments, so we know how to parse and expose them to the paint() function.
