### ISSUE TITLE
Why is there a responsible browsing context, but no document?

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#224]
If the document goes away, the worklet will too, no? It's hardly ever useful to have a handle on a browsing context...

@bzbarsky

**Comment by bfgeek** [comment]
@annevk I looked back at the old revision of the spec* and was trying to work out was this was referring to...

....was this just referring to the fact we didn't have a defined lifetime yet? I.e. does https://github.com/w3c/css-houdini-drafts/pull/389 fix this?

* https://github.com/w3c/css-houdini-drafts/blob/e5e2586ca08508a8d8c9f16e272a38c620bebe45/worklets/Overview.bs

**Comment by annevk** [comment]
That sounds like a slot on the other side, which presumably already exists since that's the document/Window holding the worklet.

**Comment by annevk** [comment]
This blocks https://github.com/whatwg/html/pull/2521 although it seems @domenic is okay with leaving it as an open issue.

**Comment by bfgeek** [comment]
There is now a concept called the owner document in the spec:
https://drafts.css-houdini.org/worklets/#workletglobalscope-owner-document

The global scope is destroyed when the document is discarded, similar to workers.

**Comment by domenic** [comment]
With https://github.com/whatwg/html/pull/6056, we can close this. The lifetime of WorkletGlobalScopes is now very explicit.
