### ISSUE TITLE
[css-paint-api] Decide how much information is in the "Geometry" passed into a paint function

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#23]
The most basic information needed is the width and height of the fragment you are currently painting.

Other information that might be desirable is:
sibling fragment information - for example you want to know your position relative to you siblings so that you can paint an effect that spans multiple fragments.
previous sibling fragment information only - same as above, but you only receive your previous sibling fragment information.
children fragment information - you want to know your children fragments so that you can paint effects like a line between them (or something).

It is probably desirable to (upon registering the custom paint class) to decide which type of information here you are interested in. For example invalidating a polyfill of conic-gradient based on children fragment information isn't optimal.

**Comment by tabatkins** [comment]
Wrong layer - CSS already handles this for you.  Based on 'box-decoration-break', CSS will either call the image generator once (with sizing info of the combined fragment list) and slice/position it for you, or call it multiple times (with sizing info for each fragment).  There's no need for the image generator to care about any of this itself.

(We'll need to handle this in a later version of the Paint API that lets you intercept/override the painting of the entire element, like we discussed in the beginning, but v1 of Paint doesn't work at that layer.)
