### ISSUE TITLE
draw a paint image is not thread safe

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#231]
https://drafts.css-houdini.org/css-paint-api/#draw-a-paint-image seems to access the worklet, the document, and the box tree. These are not necessarily on the same thread in the future. And if we want to enable that future, we need to design now to avoid those kind of issues.

@bzbarsky

**Comment by bzbarsky** [comment]
It's not just in the future.  The whole premise is that the worklet global should be able to be on a different thread from the DOM, but the algorithm here bounces back and forth between touching those two things.

**Comment by bfgeek** [comment]
A worklet global scope _may_ be on a different thread from the DOM, it doesn't require that.
(but yeah, I'll work on making this thread-agnostic). ^-^

For blink (initially at least) we'll place our paint and layout worklets on the main thread.

It'll be possible in the future for the whole paint phase in blink to be on a background thread (in ~2years maybe) at which point we'd move paint worklet onto a background thread potentially. But this is way in the future.

**Comment by bzbarsky** [comment]
Servo has DOM, layout, and paint on three different threads right now, fwiw.

**Comment by bzbarsky** [comment]
(Well, and layout and paint can actually be multiple threads each.)

**Comment by bfgeek** [comment]
Yup aware of that, dw. :)
