### ISSUE TITLE
Using Invoke/Construct directly without IDL settings machinery is broken

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#235]
https://drafts.css-houdini.org/css-paint-api/

@domenic can probably help here.

@bzbarsky

You probably also want to update the reference to https://tc39.github.io/ecma262/...

**Comment by domenic** [comment]
Yeah, see "Calling scripts" in https://github.com/w3c/css-houdini-drafts/issues/222

**Comment by bfgeek** [comment]
Is there anything for construct at the moment?

(I've mostly fixed invoke, copying off CE)

**Comment by bfgeek** [comment]
This was fixed in 4a1ca96e449657b287d40d7188770ab54443db75.
