### ISSUE TITLE
[css-typed-om]: CSSCalcLength is not defined

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#240]
@bzbarsky

**Comment by bzbarsky** [comment]
As in, nothing says what the getters/setters of any of the properties on it should do.

**Comment by shans** [comment]
CSSCalcValue is somewhat better defined now (by @tabatkins )

**Comment by annevk** [comment]
Would be useful if you have a commit so it can be reviewed.

**Comment by shans** [comment]
Tab made a sweeping set of changes to the way we handle values. As part of that, he defined calc objects better. So there's not a commit to reference, as such - reviewing the current version of the specification is likely to be far simpler for you than dredging through a commit range.

**Comment by tabatkins** [comment]
Yeah, the class is small and you can just look at it.  <https://drafts.css-houdini.org/css-typed-om/#complex-numeric>

They're just maplikes now, with a `.type` attribute telling you roughly what the CSS type is.

**Comment by annevk** [comment]
It still doesn't seem to make much sense. E.g. "strong type" is defined as something of CSSCalcValue, but it's repeatedly asked of a string as well...

**Comment by tabatkins** [comment]
No, CSSCalcValues *have* strong types; strings *are* strong types (some of them, at least).

That said, you did catch an error - when I say "If unit is a strong type", I mean "If unit's CSS type is a strong type".  I'll fix.
