### ISSUE TITLE
[css-typed-om]: CSSCalcDictionary needs a different name

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#241]
Per @bzbarsky, it's length-specific, whereas `calc()` can return a number.

**Comment by tabatkins** [comment]
Yeah, we need a family of calcs for each type.  (It can also return an angle, a frequency...)

**Comment by shans** [comment]
Going to rename this CSSLengthCalcDictionary.

**Comment by shans** [comment]
Addressed by https://github.com/w3c/css-houdini-drafts/commit/647b44ddbb37ed564268965e4d9db4ad044f4c30
