### ISSUE TITLE
[Typed OM] rotate3d syntax in old OM is "rotate3d(x, y, z, a)", but in Typed OM it is Constructor(angle, x, y, z)

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#245]
rotate3d syntax in old OM is "rotate3d(x, y, z, a)", but in Typed OM it is Constructor(angle, x, y, z)

https://drafts.css-houdini.org/css-typed-om/#dom-cssrotation-cssrotation-angle-x-y-z

https://www.w3.org/TR/css-transforms-1/#funcdef-rotate3d

Should they be consistent?

**Comment by tabatkins** [comment]
Yes, they should be. This was an ovesight.
