### ISSUE TITLE
[css-properties-values-api] Computed values for <color>

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#247]
[Section 2.4][1] of the spec says:

`For <custom-ident>, ident, <color>, <image>, <url>, <integer>, <angle>, <time>, <resolution>, <transform-function> or "*" values, the computed value is identical to the specified value.`

But what if a color value is _currentColor_, or a color name like _red_?

[css-color level 4][2] says that the computed value of the color property is an RGBA color.

Should the computed value of a variable with type `<color>` be an RGBA color as well?

[1]: https://drafts.css-houdini.org/css-properties-values-api/#calculation-of-computed-values
[2]: https://drafts.csswg.org/css-color-4/#the-color-property

**Comment by bfgeek** [comment]
@tabatkins and I ran into currentColor in #133 as well.

If I understood correctly currentColor now specified to be an actual color at used-value time.
css-color level 4 might be inconsistent with itself? (see: https://drafts.csswg.org/css-color-4/#currentcolor-color )

**Comment by tabatkins** [comment]
The computed value of `color` is always an rgba color; that has nothing to do with `currentcolor`.

`currentcolor`, when used in any other `<color>` context, is indeed preserved at computed-value time, and only turned into rgba at used-value time.

**Comment by jonathanyc** [comment]
Then is currentColor considered "computationally idempotent" in terms of the _initialValue_ parameter?

**Comment by shans** [comment]
There's a problem here.

```background: currentcolor;```
will repaint when color changes from red to green; but

```background: paint(foo);
--background-color: currentcolor;
...
registerPaint(“foo”, …, [“--background-color”]);```
will not repaint when color changes, because currentcolor is computationally idempotent.

You could just add color to the list of sensitivities in registerPaint, but that seems like a bit of a hack given that currentcolor is valid all over the shop. Would it make sense to special-case currentcolor instead? This would require --background-color to be registered as a color property.

**Comment by tabatkins** [comment]
Yes, I think we should bite the bullet and special-case currentcolor. It's used as the initial value of a bunch of properties already (border-color, text-decoration-color, etc), and there's definitely custom property use-cases that want the same thing.

**Comment by shans** [comment]
(Note this also applies for line-height and custom-layout)

**Comment by tabatkins** [comment]
My current definition actually captures this correctly:

> A property value is <dfn export>computationally independent</dfn>
> if it can be converted into a computed value
> using only the value of the property on the element,
> and "global" information that cannot be changed by CSS.

"currentcolor" as a specified value becomes "currentcolor" as a computed value, no extra information necessary (or it becomes #000 for 'color', same deal).  It's not until used-value time that extra information is pulled in to resolve it into something different.
