### ISSUE TITLE
[css-typed-om] CSSLengthValue normalization typo?

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#249]
The [section](https://drafts.css-houdini.org/css-typed-om/#lengthvalue-normalization) on CSSLengthValue normalization says:

> Otherwise, if the provided value can be parsed as a calc expression with a resolved type of `<length>` or `<percentage>`, then a CSSCalcLength is constructed with each unit that is mentioned in the calc expression reflected as the matching attribute set to the appropriate value.

But in the linked spec on 'resolved type,' it says that:

> A math expression has a resolved type, which is one of `<length>`, `<frequency>`, `<angle>`, `<time>`, `<number>`, or `<integer>`. ...
> If percentages are accepted in the context in which the expression is placed, a `<percentage-token>` has the type of the value that percentages are relative to; otherwise, a math expression containing percentages is invalid.`

Is there some spec that says `<percentage>` is also a resolved type, or is this a typo?

**Comment by tabatkins** [comment]
Hmmmm. Everywhere else in CSS so far, a percentage resolves relative to something else, but I guess in Houdini it's not required to.  I should amend V&U to allow `<percentage>` as a resolved type.

**Comment by tabatkins** [comment]
Fixed in V&U.
