### ISSUE TITLE
 [css-properties-values-api] Computed values for <transform>

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#250]
The `perspective` transform takes a `<length>` value. [Section 2.4](https://drafts.css-houdini.org/css-properties-values-api/#calculation-of-computed-values) says that the computed values of `<length>`s should be absolute lengths in pixels. But currently it says that the computed values of `<transform-function>`s are identical to the specified value.

Should implementations recursively compute transform function values? Otherwise it seems like there will be unexpected results with inheritance. For comparison, the [CSS transforms](https://drafts.csswg.org/css-transforms/#serialization-of-the-computed-value) specification says that the computed value for the `transform` property is actually fully computed to a `matrix()` or `matrix3d()` function.

**Comment by shans** [comment]
Yes, you're right. The <transform-function> computed values need to resolve absolute lengths.
