### ISSUE TITLE
[css-typed-om] CSSMatrix class conflicts with old prefixed Matrix classes

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#252]
See also: 
https://developer.mozilla.org/en-US/docs/Web/API/CSSMatrix
https://bugs.chromium.org/p/chromium/issues/detail?id=621945

WebkitCSSMatrix and MSCSSMatrix exist with a different API, and some libraries, including Adobe animations and the Closure library write code like 
`window.CSSMatrix || window.WebKitCSSMatrix || window.MSCSSMatrix`, which causes some websites to break (notably Google photos, some others I found were www.bahamas.com and www.australianexplorer.com). Adobe's animation library is versioned and while mostly served from adobe.com, is also served from other domains.

Aside from breaking pages, it will be confusing for developers to have CSSMatrix and WebkitCSSMatrix/MSCSSMatrix have such different interfaces.

Should we rename CSSMatrix to something else?

**Comment by shans** [comment]
I have a PR for closure: https://github.com/google/closure-library/pull/719
Though given Adobe's done this too, maybe we do need to change the name. Suggestions?

**Comment by wilddamon** [comment]
hmm...
CSSMatrixComponent
CSSMatrixValue
CSSMatrixTransformComponent
CSSMatrixTransform
?

**Comment by shans** [comment]
@wilddamon did you end up with a preferred name?

**Comment by wilddamon** [comment]
No, we didn't agree on anything. For now the Blink implementation is using CSSMatrixTransformComponent, but I think it'd be nice to change it to something shorter.

**Comment by shans** [comment]
I'm OK with the name being long. I'm not sure we actually want to encourage use of matrix values, and if they become popular then people can add shortnames manually via js.
