### ISSUE TITLE
[css-layout-api] Come up with a better name for "Box"?

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#254]
`Box` in context of the layout API is just being used as input to the layout algorithm.

They are "something that has an associated computed style". In this context they have no layout information themselves. (Fragments have that in this context).

This may be confusing to folks from CSS specs / authors who think of a box having layout information.

¯\\_(ツ)_/¯

**Comment by frivoal** [comment]
The CSS terminology used to be a lot more vague, and throw the words box or element around without much consideration, but I think that in the more modern and deliberate usage, the distinction between Box and Fragment does match the way these words are used in the spec. (even though in contexts where we don't care about fragmentation, I am pretty sure we still occasionally use box when we mean box fragment.)

**Comment by tabatkins** [comment]
Yeah, a box knows what its display type is and has fully resolved computed styles, but it doesn't have layout information - it generates fragments which *do* have size/position.  Boxes are abstract style/content containers, is all.
