### ISSUE TITLE
[css-layout-api] Specify which anonymous boxes generate boxes for the purposes of the layout API.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#255]
We'll need to specify specifically which types of anonymous boxes generate a box for layout.

E.g.
 - A `<div style="display: table-cell;">` will insert additional boxes to surround it with an appropriate <table> box.
 - Text inside a flexbox which has undergone blockification.

etc.

**Comment by tabatkins** [comment]
All of them do, that's the entire point of generating anonymous boxes. We don't need to say anything special here, anonymous boxes are just part of the box tree, and the box tree is transformed into the fragment tree via layout.
