### ISSUE TITLE
[css-properties-values-api] Specific identifier syntax & CSS-wide keywords

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#259]
One supported syntax string is: "Any string, the contents of which matches the `<ident>` production", [1] which matches that identifier. An identifier is "a sequence of characters conforming to the `<ident-token>` grammar." [2] But "Regardless of the syntax specified, all custom properties will accept CSS-wide keywords as well as revert, and process these values appropriately." [1]

Is "inherit" then a legal syntax string? What should happen if the user declares that custom property with the value "inherit"?

[1]: https://drafts.css-houdini.org/css-properties-values-api/#supported-syntax-strings
[2]: https://drafts.csswg.org/css-values-3/#typedef-ident

**Comment by tabatkins** [comment]
Ah, that should probably instead say `<custom-ident>`.  The CSS-wide keywords aren't allowed, because CSS handles them automatically.

Related, we should be clear about the keywords being codepoint-matched, not ASCII-CI, right?

**Comment by jyc** [comment]
Thanks for the clarification.
Just to make sure, by codepoint-matched, do you mean matching code point by code point? And by ASCII-CI, do you mean case-insentively matching character by character as if the string were ASCII?

**Comment by tabatkins** [comment]
Yes. Those are the two modes CSS operates in - if the string is in an ASCII-only context, it's matched ASCII case-insensitively; otherwise, it's matched codepoint-by-codepoint.  No normalization is ever done in CSS (or in the web platform as a whole, unless you're specifically using a Unicode-transforming library).

**Comment by jyc** [comment]
Got it, thanks.
