### ISSUE TITLE
[css-paint-api] Add to spec how many times a paint function is able to be called if its inputs don't change

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#26]
Is it fine if the paint function is allowed to be called multiple times if its inputs don't change?
 - Probably yes as we want UAs to be able to dispose of results to reduce memory.

Is it fine if the paint function is allowed to be called multiple times within the same frame if its inputs don't change?
 - Maybe? I don't have strong arguments for or against here.

**Comment by frivoal** [comment]
> On 01 Sep 2015, at 00:11, Ian Kilpatrick <notifications@github.com> wrote:
> 
> Is it fine if the paint function is allowed to be called multiple times if its inputs don't change?
> 
> Probably yes as we want UAs to be able to dispose of results to reduce memory.
> Is it fine if the paint function is allowed to be called multiple times within the same frame if its inputs don't change?
> 
> Maybe? I don't have strong arguments for or against here.
> —
> Reply to this email directly or view it on GitHub <https://github.com/w3c/css-houdini-drafts/issues/26>.
> 
As long as any randomness is included as an input, that sounds like the right thing to do. I don't see why we would need to draw a distinction for multiple times within the same frame.

**Comment by tabatkins** [comment]
Same. There doesn't seem to be any reason to restrict when/how often we can call the function.

**Comment by bfgeek** [comment]
Yeah I was thinking about this, seems overly constrictive on UAs to not allow this. Will close this bug once I've added it to the spec.

**Comment by bfgeek** [comment]
Realized this has been in the spec for a while now.
