### ISSUE TITLE
[css-paint-api] Issue with GIF, APNG, WebP (animated images)

### ISSUE THREAD

**Issue by acterhd** [w3c/css-houdini-drafts#260]
Hello. I found issue in specification of Paint API. How will draw animated gifs, apng, etc. on CSS Paint API? By policy of html5 canvas this is not possible. As minimum needs low level API for image sources or frames. I think need make low level API of specification for image and video decoder.

**Comment by shans** [comment]
The Custom Paint API is not intended for presentation of pre-rolled animated content. Just use the resource directly on your page instead.
