### ISSUE TITLE
[css-typed-om-2] "This version" link is wrong

### ISSUE THREAD

**Issue by rjwright** [w3c/css-houdini-drafts#262]
As title

**Comment by rjwright** [comment]
"This version" link is wrong in CSS Typed OM 2. 
Says https://drafts.css-houdini.org/css-typed-om-1/ but should say https://drafts.css-houdini.org/css-typed-om-2/

**Comment by zrhoffman** [comment]
The *This version* link on <[https://drafts.css-houdini.org/css-typed-om-2/](https://drafts.css-houdini.org/css-typed-om-2/)> still points to version 1, probably because the [`main`](https://github.com/w3c/css-houdini-drafts/commits/main) branch does not include a1cea5f8a4e4.

**Comment by svgeesus** [comment]
Thanks! Had not realizes I was on the old master branch.

Fixed by https://github.com/w3c/css-houdini-drafts/commit/30fd3205eef4d78cbf2b13fb766a0a80b606ccc4
