### ISSUE TITLE
[css-typed-om] StylePropertyMap iterable

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#267]
`StylePropertyMapReadOnly::get` returns `CSSStyleValue?`, but `StylePropertyMap` is itself ` iterable<DOMString, (CSSStyleValue or sequence<CSSStyleValue> or DOMString)>`.
In what circumstances is the iterator value then a `CSSStyleValue` or `sequence<CSSStyleValue>`?

There is also a note saying that:

> The sequence of CSSStyleValues associated with a property do not represent multiple successive definitions of that property’s value. Instead, sequences represent values associated with list-valued properties.
> This approach allows single-valued properties to become list-valued in the future without breaking code that relies on calling get() and/or set() for those properties.

Shouldn't `StylePropertyMapReadOnly::get` return `sequence<CSSStyleValue>` then? Why not make the iterator value the same?

https://drafts.css-houdini.org/css-typed-om/#the-stylepropertymap

**Comment by tabatkins** [comment]
No, this is the exact reason we have both `get` and `getAll` - `stylePropertyMap` is a MultiMap, which can masquerade as a plain single-valued Map if you interact with it via the Map methods (`get`, etc), but which can expose multiple values per key if you use the specialized MultiMap methods.

The text you're quoting explains precisely why we do this.

**Comment by jyc** [comment]
Alright, thanks! Then what is `get` supposed to return for a list-valued property? E.g.

```
background-image: url(http://example.com/a.png), url(http://example.com/b.png), ..., url(http://example.com/z.png);
```

Does `get` return the first image? The last image? Throw an error? I understand `getAll` returns a sequence of all the images.

In what circumstances is the iterator value a `CSSStyleValue` or `sequence<CSSStyleValue>` or `DOMString`? `CSSStyleValue` makes sense for non-list-valued properties and `sequence<CSSStyleValue>` for list-valued properties, but why `DOMString`? This doesn't seem to be mentioned anywhere in the spec.

**Comment by tabatkins** [comment]
`get` will return the first one.

`DOMString` is for the properties that don't yet have a Typed representation, I think.  This spec needs some cleanup. :/

**Comment by jyc** [comment]
Alright, thanks. Anyone who would be good to email/ping?

**Comment by tabatkins** [comment]
Me or Shane, and you've just done so. That's the point of this repo. ^_^

**Comment by shans** [comment]
DOMString seems wrong. Components that don't have a Typed representation would be raw CSSStyleValues?

**Comment by shans** [comment]
Closed via https://github.com/w3c/css-houdini-drafts/commit/23e8e6062077f11c7305c4118c633bbde4cc35d8
