### ISSUE TITLE
[css-typed-om] CSSRotation/Skew can be constructed with doubles, but not CSSTranslation/Perspective

### ISSUE THREAD

**Issue by rjwright** [w3c/css-houdini-drafts#272]
Since we allow constructing transform components with double angles in _deg_, should we also allow constructing transform components with double lengths in _px_? Alternatively disallow both.

**Comment by rjwright** [comment]
@tabatkins

**Comment by rjwright** [comment]
@shans

**Comment by tabatkins** [comment]
No, only zero lengths can be unitless.  Angles, unfortunately (because of people implementing badly before the spec was even written), support unitless degrees in several spots, including rotate(). :/

**Comment by shans** [comment]
We should take the opportunity to provide consistency here.

It sounds like you would lean towards correctness (i.e. no unitless degrees either). An argument can also be made for convenience:
new CSSSimpleLength(42, 'pixels')
vs.
new CSSSimpleLength(42).

Overall I think I probably value correctness more too. Anyone else have any thoughts?

**Comment by tabatkins** [comment]
Discussed this with @fantasai - we shouldn't be allowing unitless angles either.  That's a back-compat issue for the CSS literal syntax because Safari engineers are terrible at designing CSS syntax; we have no such restrictions in Houdini, and can make sure we do things consistently and correctly instead.

**Comment by rjwright** [comment]
So shall I pull it out?

**Comment by tabatkins** [comment]
I'd prefer it, but want to verify with @shans

**Comment by shans** [comment]
It's always easier to add stuff later than remove. Let's pull out all unitless constructors for now.

**Comment by rjwright** [comment]
SGTM

**Comment by shans** [comment]
@rjwright want to submit a PR for this?

**Comment by rjwright** [comment]
Will do
