### ISSUE TITLE
[css-properties-values-api] Interpolate lists as simple or repeatable lists?

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#273]
CSS Transitions defines two ways general lists of values can be interpolated - as simple lists, (lengths must match) or as repeatable lists (result list is the LCM of the lengths of the start & end lists and the start & end lists are repeated).

Should lists of values be interpolated as simple lists or as repeatable lists?

https://drafts.csswg.org/css-transitions/#animtype-repeatable-list

**Comment by tabatkins** [comment]
The only list we allow right now is simple value repetition via the `+` combinator, and those types of lists always go as simple lists.  I'll make the spec clearer about it.
