### ISSUE TITLE
[css-properties-values-api] <image> gradient values computed

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#274]
Right now the spec says `<image>` computed values are the same as their specified values, but we can create `<image>`s using gradients which might contain relative length values. Should we compute these terms first?

**Comment by shans** [comment]
For level 1 this is mainly going to be an issue with the cssText of the computed gradient. In level 2 we'll also need to make sure that any raw data members are computed.

**Comment by shans** [comment]
This is covered by #268 - cssText for computed objects will be generated via the underlying CSS values.
