### ISSUE TITLE
[css-typed-om] Describe how the StylePropertyMaps should interact with custom properties

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#276]
Especially when using `getProperties()` and when using the iterators, and whether you should be able to set/get custom properties.

**Comment by shans** [comment]
strawperson suggestion:

You should be able to get/set custom properties on inline and specified styles. You should be able to get custom properties on computed style.

getProperties:

* For inline style, should return the custom properties that are set on the inline style of the current node
* For specified style, should return the custom properties defined in the current rule
* For computed style, should return all defined custom properties on the current node (including inheritance)

**Comment by shans** [comment]
(removing @apply because that isn't likely to happen any time soon)

**Comment by tabatkins** [comment]
+1 to all three of those getProperties lines

**Comment by tabatkins** [comment]
For typed custom properties with an initial value, they should show up in the computed style map.

**Comment by tabatkins** [comment]
I went into more detail with this in 2519d4b and a preceding commit about the computed style.
