### ISSUE TITLE
The Calc* classes need a "number" member

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#278]
line-height can accept a length, a % (which resolves to a length at computed-value time), or a number (which resolves to a length at used-value time).  Need something to be able to express the combination of these three in a calc() (even if some engines can't actually handle that right now).

I suggest just adding a 'number' field to the Calc classes; they all currently have a % field even tho %s aren't valid in all circumstances, and this'll be the same (just invalid in much more places).

**Comment by tabatkins** [comment]
(Make sure it's clear in the spec that setting a calc with a % or number to a property that doesn't accept those throws at setting time, just like setting 'width' to an angle or something.)

**Comment by shans** [comment]
This has been resolved.
