### ISSUE TITLE
IDL index contains fake IDL constructs

### ISSUE THREAD

**Issue by tidoust** [w3c/css-houdini-drafts#281]
The Worklets draft contains [examples of fake IDL constructs](https://drafts.css-houdini.org/worklets/#examples). I would expect the [IDL index](https://drafts.css-houdini.org/worklets/#idl-index) that appears near the end of the document to only list the IDL constructs that the spec normatively defines (`WorkletGlobalScope` and `Worklet`). However, this index, automatically generated by Bikeshed, also includes `FakeWorklet`, giving the feeling that the spec normatively defines that term as well.

I see that there is a way to [turn off IDL processing](https://github.com/tabatkins/bikeshed/blob/master/docs/idl.md#turning-off-processing) in Bikeshed, although that's probably not what you want here, since the processing itself is useful for the Examples section. I do not know if there is a way to mark the IDL as "example" or "informative" so that Bikeshed does not include it in the IDL index. @tabatkins, is it doable?

**Comment by tabatkins** [comment]
Yeah, the fake stuff just needs to be in a non-normative section - it or an ancestor needs a class of "note", "example", or "non-normative".  That's currently only indicated in prose in the spec.

**Comment by bfgeek** [comment]
@tabatkins This is fixed right?

**Comment by tabatkins** [comment]
Whoops, yeah.
