### ISSUE TITLE
registerProperty/unregisterProperty should be clearer about escaping of property name

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#283]
The [definition of <code>registerProperty()</code> and <code>unregisterProperty()</code>](https://drafts.css-houdini.org/css-properties-values-api/#the-registerproperty-function) should be clearer about CSS escaping of the property name.  It says that the name given has to match a CSS production that does include escaping, but it doesn't actually say that that CSS escaping is processed in the production of the property name that is actually registered, or that registering and unregistering by different strings that are equivalent once escaping is processed properly unregisters, or similar for registering twice throwing an exception.

**Comment by tabatkins** [comment]
It looks like we don't currently CSS-parse it, and instead just take it literally.

If you run:

```js
CSS.registerProperty({
   name:"--f\\30o", 
   syntax:"<color>", 
   initialValue:"blue", 
   inherits:false});
```

then `getComputedStyle(document.body).getPropertyValue("--f\\30o")` returns blue, while `getComputedStyle(document.body).getPropertyValue("--f0o")` returns the empty string.

So yeah, I'm fine with specifying, like in other parts of the platform and TypedOM, that the name is taken literally.

**Comment by tabatkins** [comment]
(Done in ec02741)

**Comment by tabatkins** [comment]
(and also in 17d9a30 just now for additional cleanup)
