### ISSUE TITLE
[css-typed-om] Value of 3d parameters in 2d transform components

### ISSUE THREAD

**Issue by rjwright** [w3c/css-houdini-drafts#284]
If I do  `var translate = new CSSTranslation(10px, 10px)`, what is the value of `translate.z`?

Rotation and scale have the same problem.

Currently it is null, at least in the polyfill. I can't find it outlined in the spec. What should it be?

**Comment by rjwright** [comment]
@shans @tabatkins @wilddamon

**Comment by shans** [comment]
Probably should be 0px. We need to spec this though.

**Comment by rjwright** [comment]
> Probably should be 0px.

+1

> We need to spec this though.

I can draft it once we decide, if you want.

**Comment by tabatkins** [comment]
Yeah, should def be 0px. (Or equivalent "nil value", if some of the other 3d transforms have things other than lengths.)

**Comment by shans** [comment]
This has been specced.
