### ISSUE TITLE
[CSS Typed OM] CSSFontFaceValue objects can't store source value

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#293]
In the case of CSSFontFaceValue objects, shouldn't the have a member that stores the source as well?

For eg in the case:

@font-face {
      font-family: "XYZ";
      src: url("https://mdn.mozillademos.org/files/2468/VeraSeBd.ttf");
    }

I am assuming the specified member fontFaceName stores the string "XYZ" and we will need to store the source in another member.Potentially in a CSSFontFaceSrcValue which inherits from CSSFontFaceValue? This can deal with the case where it is specified as a url or as a local value

**Comment by nainar** [comment]
@shans

**Comment by shans** [comment]
@tabatkins @bfgeek how important is this for L1?

**Comment by tabatkins** [comment]
Why can't we just expose the string?

**Comment by shans** [comment]
that would be fine. But do we need it for L1?

**Comment by tabatkins** [comment]
I mean, do we need *any* of the descriptors from `@font-face`?  It seems weird to only offer some of them.

**Comment by shans** [comment]
We're going to track this stuff in #405. The whole design of CSSFontFaceValue needs to be reconsidered.
