### ISSUE TITLE
When doing CSSStyleValue.parse(), what should throw vs return null?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#305]
The old (very incomplete) definition of CSSStyleValue.parse() said that things returned null if they didn't parse. I've rewritten it in a proper algorithmic style, and identified three possible error locations. Which should throw, and which should return null? (Currently, the spec throws for all of them.)
1. Property name isn't an ident.
2. Property name is an ident, but not recognized as a CSS property.
3. Valid property name, but property value doesn't match the grammar of that property.

**Comment by SebastianZ** [comment]
My gut feeling says throw for 1 and return `null` for 3. I'm unsure about 2 but tend to throw to be able to distinguish that case from 3.

Sebastian

**Comment by shans** [comment]
I think 2 is more or less the same as 3 - in each case, it's possible that the failure is due to uneven implementation across different browsers.

**Comment by shans** [comment]
@SebastianZ WDYT? Should 2 be like 3, or distinguishable?

**Comment by SebastianZ** [comment]
I stand with my previous comment that 2 and 3 should be distinguishable.
This could either be done by letting 2 throw while 3 returns `null`, as I wrote earlier, or throwing in both cases (with properly distinguishable exceptions).
It's still not a strong opinion, though.

Sebastian

**Comment by shans** [comment]
Currently specified behavior is:
1. throws a Syntax Error
2. throws a Type Error
3. throws a Syntax Error

This satisfies distinguishability. Remaining question: should 3. return null instead?

**Comment by SebastianZ** [comment]
This makes 1 and 3 hard to distinguish, so I still say return `null` for 3. Any other opinions?

Sebastian

**Comment by shans** [comment]
I'm leaning that way too. @tabatkins ?

**Comment by tabatkins** [comment]
#1 is *definitely* a SyntaxError, no question in my mind.  I think #2 being a TypeError has strong reasoning behind it.

I don't have strong opinions on #3.  I guess `null` could be okay, but like you said in <https://github.com/w3c/css-houdini-drafts/issues/305#issuecomment-246914817>, #2 and #3 will commonly be due to the same thing (uneven support between browsers), and having them be extremely different (throw vs null) will often be a disservice, I think.

I think I'd rather have them both throw, with whatever error is most appropriate, and solve the "wrong property, or wrong value?" problem more directly.  That sounds like an API idea we can work on.  I don't think we should smuggle the use-case into which error we emit.

**Comment by tabatkins** [comment]
Let's do TypeError for everything; that's the error we're currently consistently throwing in all the StylePropertyMap similar cases, and they don't even check for whether the string is a valid ident.
