### ISSUE TITLE
[css-properties-values-api] Add 'Latest published version' links to EDs

### ISSUE THREAD

**Issue by SebastianZ** [w3c/css-houdini-drafts#314]
None of the Editor's Drafts of the Houdini specs currently has a link to the latest corresponding version in TR.

E.g. the [CSS Painting API Level 1](https://drafts.css-houdini.org/css-paint-api-1/) has a related [Working Draft](https://www.w3.org/TR/css-paint-api-1/) but is missing the link to it.

Those links should be added to the titles of the drafts saying 'Latest published version' like it's the case in other CSS EDs.

Sebastian

**Comment by shans** [comment]
@tabatkins is there a particular way to do this in bikeshed?

**Comment by tabatkins** [comment]
add a `TR: url-goes-here` metadata

**Comment by tabatkins** [comment]
And/or a `Previous Version: url` one, if we've published more than once.

**Comment by bfgeek** [comment]
Added for [worklets] and [css-paint-api].

**Comment by shans** [comment]
It seems that this has been done for css-properties-and-values too
