### ISSUE TITLE
One repo per draft?

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#316]
It would be much clearer if we had one repo per draft. The current setup makes it really hard to inspect outstanding issues.

WebAppSec had the same problem at one point and since they splitted everything has much improved. Just use a common prefix if you want them all easy to find from /w3c.

**Comment by tabatkins** [comment]
We're definitely doing so in the future; everything new in Houdini is being WICG'd (see [the Parser API](https://github.com/wicg/css-parser-api/) for the first such example) and thus will have its own repo.

I'd be okay with splitting the existing repo apart, but it would be relatively disruptive to our existing issue threads.

**Comment by shans** [comment]
IIRC the reason for a single repo was that some people on the group wanted a single point where they could subscribe to all changes & issues. There are advantages and disadvantages (e.g. a number of times we've wanted to file an issue on multiple specs at once). I'm not opposed to splitting at some point but I think we'd want to get the group to agree first.

We've been tagging the outstanding issues by spec to make it easy to just focus on one specification at a time - e.g. for typed OM you can use https://github.com/w3c/css-houdini-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-typed-om-1.

**Comment by annevk** [comment]
The group thing you can take care of by just defining a group of people on GitHub and add them to each repo.

**Comment by shans** [comment]
Yes, that would work for keeping interested parties subscribed to all the changes, thanks.

Any ideas about issues that apply to multiple repos? We've also had to move issues between specs on more than one occasion.

**Comment by annevk** [comment]
Just file multiple and add pointers. That is what other specs do for mutual dependencies. If it really happens a lot there might be a more structural issue.

**Comment by annevk** [comment]
Closed without any kind of comment, really?

**Comment by tabatkins** [comment]
The initial response is what we're doing - future specs will live in their own repos, but it's too much trouble for not enough benefit to split apart the current repo.
