### ISSUE TITLE
Only microtasks, but still postMessage()?

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#319]
It seems some worklets want a postMessage() API, but how does that work without tasks? I couldn't find a definition anywhere.

**Comment by jyasskin** [comment]
Specifically, https://github.com/WebAudio/web-audio-api/wiki/AudioWorklet-IDL-Proposal#user-content-audioworkletnode vs https://drafts.css-houdini.org/worklets/#the-event-loop

**Comment by tabatkins** [comment]
Worklets definitely aren't getting postMessage. Some sort of signaling back to the main thread is needed by some worklets, but we've yet to work out the details.

(This was discussed at TPAC - AudioWorklet eventually needs this comm mechanism, but doesn't desperately need it *right now*; some people were worried about Process, tho, and wanted to shoehorn something in early.)

**Comment by bfgeek** [comment]
So I'll close this for now, the webaudio folks have moved away from a postMessage api and all of the baggage that contains for a far more constrained `sendData` method, and `ondata` callback which just works on structured cloning the given data. `ondata` works the same as other worklet callbacks and called right before the `process` callback is invoked. (rather than triggered by the event loop).

**Comment by annevk** [comment]
ondata is an event or a callback? That would have to be a microtask somehow per the not super precise description of worklets event loop?

**Comment by annevk** [comment]
I looked at https://webaudio.github.io/web-audio-api/ btw and `sendData()` is far from defined. There's no processing algorithm whatsoever.

**Comment by annevk** [comment]
(I also found https://github.com/WebAudio/web-audio-api/issues/1193.)

**Comment by bfgeek** [comment]
Filed https://github.com/WebAudio/web-audio-api/issues/1194 regarding it being currently a EventHandler when it should just be a callback which is invoked by the UA.

**Comment by hoch** [comment]
Thanks for pointing them out. Those were the last bit of loose ends in the AudioWorklet spec. I posted follow up questions on the issue.
