### ISSUE TITLE
[css-paint-api] Change <image-or-paint> to just <image>

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#32]
As above.

**Comment by frivoal** [comment]
Right, we should extend the &lt;image> type and blacklist things it should not apply to, if any (maybe the cursor, see Issue #33), rather than create a superset &lt;image-or-paint> type and have whitelist everything that should accept it. It seems much more maintainable.

**Comment by bfgeek** [comment]
This has been changed to be an addition to <image>. I've noted this in the spec for now.
https://drafts.css-houdini.org/css-paint-api/#funcdef-paint

Eventually this should show up in css3-images?
Closing for now.
