### ISSUE TITLE
[typed-om] Shorter dimension constructors on the CSS namespace?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#320]
Several years ago [I left a comment about Typed OM stuff](https://lists.w3.org/Archives/Public/www-dom/2013OctDec/0114.html) wherein I suggested that the CSS namespace object could host very short constructors (/ factory functions) for the common dimensions.

That is, right now if you want to make a 5px length, you have to type:

```
let len = new CSSLengthValue.from(5, 'px');
//or
let len = new CSSSimpleLengthValue(5, 'px');
```

That's long and ugly and everyone will hate us if we force them to do that everywhere.  My idea was to additionally allow:

```
let len = CSS.px(5);
```

Basically we'd just add functions to the `CSS` namespace object for all the dimensions CSS knows about. We can possibly add more for various functions, but it looks like we wouldn't gain much. Like, for transform stuff:

```
// Current
let trans = new CSSTranslation(CSS.px(5), CSS.px(10));
// Potential new?
let trans = CSS.translate(CSS.px(5), CSS.px(10));
```

It's a bit better, but not a huge win. It also suggests that we would need to add one for every single CSS function, and somehow deal with the potential places where the same function name means different things in different contexts. (I don't think there are any, but it's potentially allowed by CSS.)  I'd be fine with ignoring this, at least unless/until we discover in the wild that people want it. In other words, L2 for this stuff, but L1 for the dimensions.

**Comment by shans** [comment]
The colors might be a big win too:
```
CSS.rgb(255, 0, 0)
CSS.rgba(255, 0, 0, 0.1)
```

**Comment by tabatkins** [comment]
Ah yeah, indeed, if we allowed raw numbers instead of requiring `CSSNumberValue`s.

**Comment by tabatkins** [comment]
Actually I'd probably want to define them as only taking a 0-1 value for all their arguments.  And things which take unitted values get easier:

```
CSS.hsl(CSS.deg(60), 1, .5)
```

**Comment by tabatkins** [comment]
With this change we can remove the static `CSSLengthValue.from(value, unit)` function, too - the `CSS.unit()` functions functionally replace them.

**Comment by shans** [comment]
There are "Numeric Factory Functions" now specified (section 4.3.4).
