### ISSUE TITLE
[css-typed-om] .equals methods for CSSStyleValue subclasses

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#325]
Could be useful for some calculations

e.g. someLengthValue.equals(otherLengthValue)

``` javascript
CSSCalcLength({px: 5}).equals(CSSSimpleLength(5, 'px')) // returns true
```

@shans

**Comment by tabatkins** [comment]
Yes, they definitely all need one, or at least all the "numeric" ones.

**Comment by tabatkins** [comment]
So there are several cases here:

1. Both UnitValues, equal unit: just compare values
2. Both UnitValues, different but compatible units: convert values, compare?
3. Both CalcValues, all terms pair up with equal-unit terms: just compare values
4. Both CalcValues, all terms can group by canonical unit, then can all pair up: convert values, compare?
5. UnitValue & CalcValue, Calc has same unit: just compare values
6. UnitValue & CalcValue, Calc has compatible units: convert values, compare?

This all sound good? Any cases I'm missing?

**Comment by tabatkins** [comment]
Should we drop 0-valued units from the comparison, so "calc(1px + 0em)" is equal to "1px"?

What if the 0-valued units aren't compatible - is "calc(0px)" equal to "calc(0rad)"?  (I assume no; we'll probably check that they have the same CSS type before checking the individual units.)

**Comment by shans** [comment]
I think .equal should be pretty strict equality. We can add a less strict version that does things like unit conversion and 0-valued unit elision if necessary.

So in other words:
1.  yup
2.  nope, they're different.
3.  yep.
4.  nope, they're different.
5.  nope, they're different.
6.  nope, they're different.

**Comment by tabatkins** [comment]
That certainly makes things easier to define.

I'm only really concerned about #5 - I don't see a good reason to distinguish between `5px` and `calc(5px)`.

**Comment by shans** [comment]
We decided to stick to strict equality for now (i.e. #5 distinguishes because they're different classes)

**Comment by tabatkins** [comment]
Unifying idea behind strict equality is "what would a Value Object do for ==, if/when that exists?" - it'll type-check then check for equality of the bytes in the underlying typed array.  That gives us our current answer.

Loose equality can be achieved today by casting both to a known type and then calling .equals(), so it's almost just sugar.  (Not quite - comparing non-trivial calcs can't be done that way.)

**Comment by nainar** [comment]
@tabatkins merged in a change from me (https://github.com/w3c/css-houdini-drafts/pull/412) and said that they would finish this up themselves. Just posting a status update since we are working on some of the Typed OM spec issues.

**Comment by nainar** [comment]
Need to add the text to make sure that we recurse over all our children here.

**Comment by tabatkins** [comment]
That is to say, currently the last steps assume the children of the functions are all unit-values; it just needs to do a proper recursion instead.

**Comment by nainar** [comment]
Closing this since the last bit of the text was added in PR #452
