### ISSUE TITLE
[css-paint-api] should normatively require switching between at least 2 worklet global scopes in most cases

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#327]
As [recorded at the end of our Lisbon minutes, part I](https://lists.w3.org/Archives/Public/www-style/2016Oct/0084.html), css-paint-api should:

```
  RESOLVED: Paint/Layout specs will have normative section that
            implementations must have at least 2 globals with an
            opt-out for memory constraints.
```

We wanted this (if my memory is correct) to reduce the chance that content will depend on state in the global scope in ways that would break implementations that want to do things like run these worklets at the same time on different threads, which is something that probably won't happen in initial implementations but that we might want to do in the future.

The current wording in the spec appears to be:

> Let workletGlobalScope be a PaintWorkletGlobalScope from the list of worklet’s WorkletGlobalScopes from the paint Worklet.
> 
> The user agent may also create a WorkletGlobalScope given the paint Worklet and use that.
> 
> Note: The user agent may use any policy for which PaintWorkletGlobalScope to select or create. It may use a single PaintWorkletGlobalScope or multiple and randomly assign between them.

which does not express this normative requirement.

(I got here from https://github.com/w3ctag/spec-reviews/issues/140 .)

**Comment by upsuper** [comment]
This behavior sounds hard for testing? Probably we can have a test which relies on this behavior and use some statistical approach (simplified BigCrush?) to ensure that its output doesn't have any reliable pattern?
