### ISSUE TITLE
[css-paint-api] class constructor valid flag is unused

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#329]
The [concepts section](https://drafts.css-houdini.org/css-paint-api/#concepts) of the paint API spec defines a "class constructor valid flag".

However, the [algorithm that sets this flag](https://drafts.css-houdini.org/css-paint-api/#registering-custom-paint) always sets it to true, since it throws exceptions earlier rather than doing things that would set it to false.

It seems like this flag can be removed given that the earlier errors throw exceptions.  Unless, that is, it's needed to address https://github.com/w3c/css-houdini-drafts/issues/328 .

(I got here from https://github.com/w3ctag/spec-reviews/issues/140 .)

**Comment by bfgeek** [comment]
This flag is used to only try to construct a class instance once. E.g. if the constructor threw an error for example (in "draw a paint image"). Where it was set was misspelled and hence not referenced properly.

E.g. 
```js
registerPaint('foo', class {
  constructor() { throw Error(); } // will once get called once.
});
```
