### ISSUE TITLE
[css-paint-api] should paintWorker be a property on window (and thus be in the global namespace)?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#330]
One thing that came up in the TAG review is that css-paint-api [adds a <code>paintWorklet</code> property to Window](https://drafts.css-houdini.org/css-paint-api/#paint-worklet).  (See @travisleithead's https://github.com/w3ctag/spec-reviews/issues/140#issuecomment-256214435 .)  Since this is on Window, it's polluting the global scope.

While we weren't necessarily against this, there was at least some concern over this, and thought it was worth hearing what alternatives were considered, and what led to the decision to add to <code>Window</code>.  One alternative that came to mind was [<code>window.CSS</code>](https://drafts.csswg.org/cssom/#css).

**Comment by bfgeek** [comment]
```
CSS.paintWorklet
CSS.layoutWorklet
CSS.animationWorklet

CSS.registerProperty()
```

Resolved in Houdini F2F Seattle to move all window attributes & methods to CSS namespace.
