### ISSUE TITLE
Global CSS Mixins

### ISSUE THREAD

**Issue by adamos42** [w3c/css-houdini-drafts#332]
Sorry if I posting this in the wrong place, I just bumped into this and I wanted to share to the community.

It would be nice if we could use CSS mixings like any other CSS selector in stylesheet. For example I could just add the same color for few element:
```
--paper-input-container-input, --my-awesome-input, --paper-button {
  color: purple;
}
```
the selectors of corse meaningless, but it would be nice to have this instead of making a shared css mixin or property and ```@apply``` each of the items which should have same css rule.

**Comment by tabatkins** [comment]
I don't understand what your proposal is here. Can you elaborate?

**Comment by adamos42** [comment]
I'am using Polymer for my project and to customize a look to an element I need to use CSS mixins to override the defaults in Shadow DOM. But sadly I wanted a bit different look like the Material Design after recoloring the project I need to add a few more rules to group of mixins.

Right now I have something like this code:
```
:root {
    --paper-input-container-input: {
        border-bottom: 1px solid #222;
        font-family: 'Open Sans', Arial, Verdana, sans-serif;
        color: #666; letter-spacing: 1px;
        text-shadow: 0 0 3px #fff;
    };
    --paper-button: {
        border-bottom: 1px solid #222;
        font-family: 'Open Sans', Arial, Verdana, sans-serif;
        color: #666; letter-spacing: 1px;
        text-shadow: 0 0 3px #fff;
    };
    --paper-toolbar: {
        border-bottom: 1px solid #222;
        font-family: 'Open Sans', Arial, Verdana, sans-serif;
        color: #666; letter-spacing: 1px;
        text-shadow: 0 0 3px #fff;
    };
}
```
Wich is not so usefull if I want to change a few rules in the mixins. Alternative solution would be use a common mixin, but then I also need to ```@apply``` that:
```
:root {
    --common-code: {
        border-bottom: 1px solid #222;
        font-family: 'Open Sans', Arial, Verdana, sans-serif;
        color: #666; letter-spacing: 1px;
        text-shadow: 0 0 3px #fff;
    };

    --paper-input-container-input: {
        @apply --common-code;
    };
    --paper-button: {
        @apply --common-code;
    };
    --paper-toolbar: {
        @apply --common-code;
    };
}
```
It would be way nicer to use the css mixins like a normal class or id:
```
:root --paper-input-container-input,
:root --paper-button,
:root --paper-toolbar {

        border-bottom: 1px solid #222;
        font-family: 'Open Sans', Arial, Verdana, sans-serif;
        color: #666; letter-spacing: 1px;
        text-shadow: 0 0 3px #fff;
}
```

**Comment by tabatkins** [comment]
Ah, ok! This is why you lead with your problem, not your suggested solution - your actual problem is that you want to give the same values to multiple custom properties, and would like a shorter syntax for doing so, right?

If that's the case, then you already see how to do it properly today - declare a custom property bag with the common properties, then @apply them into each of the custom properties you want to have those values. Or just `var()` them, like:

```css
:root {
  --common-code: {
    ...
  };
  --paper-input-container-input: var(--common-code);
  --paper-button: var(--common-code);
  --paper-toolbar: var(--common-code);
}
```

This is very little additional code, and it makes your intent clear.

Theoretically we could add something that makes this case slightly shorter, but it would be weird; setting custom properties is just *setting a CSS property*, and there's no precedent for anything that lets you set multiple properties to the same value explicitly.

**Comment by adamos42** [comment]
Oh, the ```var()``` makes it a little-bit better 😄 I like to think about the _CSS mixins_ as virtual collections of _rules_ what can be apply to anything. When I build my application I usually add a bunch of exists _Web Components_ and most of the time their author use a different name for the same functionality what I have already customized and in this way I have ridiculously long CSS assigments.

The mixins already a weird thing because if you open a bracket you expect the same functionality that any other class or id and they are not, they are just _CSS property_ with multiple rules. They are not reacting to state changes and you have to collect all of the used elements and states to set them. In multiple level of Shadow DOM it does not work because the states not reflected to the outside of the Shadow DOM, you have to go inside the element and add a bunch of new properties or helper classes for able to do it outside and keep you code clean.

It's really hard to maintain a large application if your customer want's to change something, you cannot use a simple stylesheet to change everything you have to go and change the elements to do it, and It's seems to the platform has no better way to do it.

It would be nice to have the custom properties like the classes or ids with state changes, because it would shrink down the CSS code length significantly which means faster download time, earlier paint.

**Comment by tabatkins** [comment]
Yes, we've found that using custom properties to apply things to shadow DOM is a little clunky as soon as you want to respond to `:hover` or similar; you kinda have to create families of variables, like `--foo-button` and `--foo-button-hover` (and more, if you want `:focus`, etc).

We've been looking into ways to make this work better, but it's difficult to do well without having some bad performance regressions.  Putting selectors into `@apply`'d rules defeats much of the optimizations browsers use to tell when they need to recalculate style for an element (an expensive process), so we have to be really careful about how we introduce this.

**Comment by tabatkins** [comment]
Now that we're probably going to pursue `::part()`/`::theme()`, this issue disappears - CSS cascade works normally again because we're doing the work in the right value space.
