### ISSUE TITLE
[css-layout-api] VoidFunction is also defined in another spec

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#335]
https://drafts.css-houdini.org/css-layout-api/#registering-a-layout has:

    callback VoidFunction = void ();

but VoidFunction is also defined in https://webaudio.github.io/web-audio-api/#AudioWorkletGlobalScope and a conformant IDL parser will error out on the duplicate definition of the name.

We _could_ change IDL to allow this sort of thing: identical callback definition sharing a name.  Or we could change these two specs to reference VoidFunction as defined in some one place.

**Comment by tabatkins** [comment]
Like, say, the Infra spec over in WHATWG?

**Comment by bzbarsky** [comment]
That would be a reasonable place for something like this, yes.

**Comment by annevk** [comment]
From @foolip:

> https://heycam.github.io/webidl/#common already has VoidFunction.

**Comment by annevk** [comment]
Filed https://github.com/WebAudio/web-audio-api/issues/1132 on Web Audio.

**Comment by bfgeek** [comment]
I've removed this from both the paint and layout specs.
