### ISSUE TITLE
[all] Move Houdini APIs to `window.CSS`

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#350]
Per Seattle resolution (and TAG feedback), all the Houdini APIs should namespace themselves under the `CSS` object, rather than living on the global.

(Constructors still get put on the global by default, and that should be fine. We should add convenient aliases to `CSS` as appropriate, like `CSS.px(x)` for `CSSSimpleLength(x, 'px')`.)

**Comment by dbaron** [comment]
#330 has some prior discussion (though specific to css-paint-api), including references to WebIDL work

**Comment by shans** [comment]
For typed OM, this would just be Window.getComputedStyleMap.

Should that become CSS.getComputedStyleMap, or CSS.getComputedStyle?

**Comment by bfgeek** [comment]
I've changed all the css-paint-api to CSS interface.

**Comment by nainar** [comment]
With regards to @shans suggestion I vote for CSS.getComputedStyleMap to make it clear to developers if they misuse it

**Comment by nainar** [comment]
As per #454 - removing css-typed-om label. Since the work pertaining to that spec seems to be done here.

**Comment by majido** [comment]
@tabatkins  can we close this issue now? Is there any more work left to be done?
