### ISSUE TITLE
[css-typed-om] Add .update() to styleMap

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#353]
Per [Seattle resolution](https://log.csswg.org/irc.w3.org/houdini/2017-01-10/#e755988), we should add a .update() method to styleMap, which takes a key and a callback, passing the value to the callback and setting the key to the return value.  This is a convenience API to make it easier to mutate things without having to repeat yourself.

(There was discussion about this making things more performant, as you only need one cache lookup, but Daniel Ehrenburg pointed out that you can mutate the map in the callback, so you can't rely on the cache lookup remaining valid.)

**Comment by shans** [comment]
Fixed by <https://github.com/w3c/css-houdini-drafts/commit/f9a8e09451e3148577367329f85a147c827fb720>.
