### ISSUE TITLE
[css-properties-and-values] Setting/registering is allowed to be order-dependent

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#354]
Per [Seattle resolution](https://log.csswg.org/irc.w3.org/houdini/2017-01-10/#e756205) (resolution is badly worded, read up to figure out what was actually being discussed), we're OK with an order-dependence between setting a value and registering a value.

That is, we want the following behavior:

```js
CSS.registerProperty("--foo", { grammar: "<color>" });
el.styleMap.set("--foo", "red");
el.styleMap.set("--foo", "hello"); // throws an error
// --foo is still set to "red"
```

and 

```js
el.styleMap.set("--foo", "red");
el.styleMap.set("--foo", "hello"); // valid at this point; --foo is untyped
CSS.registerProperty("--foo", { grammar: "<color>" }); // valid
// because --foo was set to a non-<color> value,
// it's now set to "unset", the bottom value for properties
```

**Comment by tabatkins** [comment]
Further clarification: per [Seattle resolution](https://log.csswg.org/irc.w3.org/houdini/2017-01-10/#e756301), when using a typed property *in a stylesheet*, setting to an invalid value doesn't trigger fallback.  That is:

```
<script>
CSS.registerProperty("--foo", {grammar: "<color>"});
</script>
<style>
div { --foo: red; }
div.foo {  --foo: hello; }
</style>
```

In here, the "--foo: hello" is *not* thrown out at parse-time; it's accepted, but because it's invalid, it gets treated as "--foo: unset;".

* This is an intentional break from "real" CSS properties, because the threat model is different (unpredictable browsers with varying support, vs known libraries with well-known support).  
* This *removes* the order-dependence between setting and registration when you're setting in a stylesheet, rather than thru the JS API.
* This makes typed custom properties less consistent with "real" CSS properties, but more consistent with *untyped* custom properties.

**Comment by shans** [comment]
What specifically needs to change in Typed OM for this? Seems like mainly a properties & values thing?
