### ISSUE TITLE
[css-typed-om-1] Interfaces with value iterators need additional attributes and operations

### ISSUE THREAD

**Issue by rakuco** [w3c/css-houdini-drafts#358]
The WebIDL spec [says](https://heycam.github.io/webidl/#idl-iterable): "_a value iterator must only be declared on an interface that supports indexed properties_".

Another section [defines](https://heycam.github.io/webidl/#idl-indexed-properties) that an interface "supports indexed properties" when it has an indexed property getter and defines an integer-typed attribute named “length”. This then gives an interface with an `iterable<V>` declaration several operations for free (they come from `%ArrayPrototype%`) such as `forEach()` and `keys()`.

With that said:
* `CSSUnparsedValue` has an `iterable<(DOMString or CSSVariableReferenceValue)>` declaration with no `length` attribute or indexed getter.
* `CSSTransformValue` has an `iterable<CSSTransformComponent>` declaration with no `length` attribute or indexed getter.

This means a WebIDL-ECMAScript bindings generator should reject those interfaces (which is something I'm trying to implement in Blink).

The css-typed-om-1 spec should be updated to include those missing attributes and operations, as well as some prose describing what sort of value the getter needs to return.

**Comment by rakuco** [comment]
@shans @tabatkins (apologies if you already received a notification)

**Comment by shans** [comment]
CSSUnparsedValue is fixed. Tab - does the same fix apply to CSSTranformValue?

**Comment by shans** [comment]
There's also this: https://github.com/heycam/webidl/issues/291

**Comment by tabatkins** [comment]
Yes, it does apply to both.  And yeah, I got deep into the array-like discussion; short version is that there's no good answer right now. I'll see about reviving the discussions again.

**Comment by rakuco** [comment]
For future reference: https://github.com/heycam/webidl/issues/338
