### ISSUE TITLE
[css-paint-api] Add example which uses ES5 class syntax.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#361]

**Comment by domenic** [comment]
-1, no browser which supports paint worklet will not support ES6 class syntax

**Comment by bfgeek** [comment]
Closing this unless others feel particularly strongly about adding a ES5 class example :).

**Comment by slightlyoff** [comment]
ES6 classes are (largely) sugar over ES5. While the support will be there for ES6, showing that ES5 syntax is supportable (and the semantics thereof) seems useful.
