### ISSUE TITLE
[css-typed-om] Why `.cssText` instead of just using stringifiers?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#364]
Why are we using a cssText attribute on the various interfaces, rather than just defining a stringifier?  I think the String OM's .cssText comes from legacy IDL before stringifiers were defined.

**Comment by shans** [comment]
What would using a stringifier look like?

**Comment by tabatkins** [comment]
It's just the `.toString()` method on the object; it gets automatically called if you add it to a string, or pass it to a method that expects a DOMString.

**Comment by shans** [comment]
Yeah let's do that. Sounds much better.
