### ISSUE TITLE
[css-typed-om] Why don't the transform constructors/attributes accept CSSUnitValues?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#365]
The CSSRotation.x/y/z and CSSScale.x/y/z attributes are typed as `double`, presumably because the arguments are typed as `<number>` in CSS. But we don't generally represent `<number>`s as doubles in the TypedOM; they're CSSUnitValues with `{unit: "number"}`.

Is there a particular reason we're using doubles here, or should we switch to CSSNumericValue?  Or maybe `(double or CSSNumericValue)`, in both the constructors and the attribute setters?  (Whatever we do, we're setting precedent for all future interfaces representing `<number>` values.)

**Comment by shans** [comment]
They should definitely accept CSSNumericValues.

If we switch rather than accepting both, I guess we could have convenience functions on CSS?

**Comment by tabatkins** [comment]
I think we should have convenience functions, yes.  `let x = new CSSTranslations(CSS.px(5), CSS.px(10))` is still a little long; I'd prefer `let x = CSS.translate(CSS.px(5), CSS.px(10))`.  (And, in general, all the CSS functions should have a convenience version on CSS, I think.)

We should discuss in depth how much type-level convenience we want.  CSSNumericValue vs double is one thing, CSSKeywordValue/CSSStringValue vs DOMString is another.  Let's make a principled decision, then we can apply it to both cases.

**Comment by shans** [comment]
Upon discussion we decided that raw numbers should be accepted everywhere CSSNumericValues are, and strings everywhere CSSKeywordValues are.

**Comment by tabatkins** [comment]
> raw numbers should be accepted everywhere CSSNumericValues

That is, everywhere CSSNumericValues of unit "number" are.

**Comment by tabatkins** [comment]
Done, they're all numberish now.
