### ISSUE TITLE
[css-typed-om] What to do with a 2d CSSMatrixComponent set to a 3d DOMMatrix?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#366]
Our new direction for separating 2d vs 3d transform values (a flippable is2D switch, that ignores sets to the 3d-related attributes when it's true) works great for most of the transform subclasses.  But CSSMatrixComponent is a little trickier, because it's 3d-related attributes are in a sub-object (its `.matrix` attribute), which we don't have direct control of.

So, what to do here when `is2D` is true?

One possibility is to enforce 2d-ness: on set, set the internal slot's matrix to reflect *just* the 2d indexes of the supplied matrix; on get, return a DOMMatrix reflecting just the 2d indexes of the internal slot's matrix.

Or we can make this one special and implicit - on set, if the matrix is 3d, silently set the `is2D` flag to false as well; on get, if `is2D` is true, return a matrix with only the 2d indexes of the internal slots' matrix.

Or we can be closer to the other objects - on set, if `is2D` is true and the matrix is 3d, do nothing; on get, if `is2D` is true, return a matrix with only the 2d indexes of the internal slot's matrix.  This might be a little harsher, tho.

**Comment by tabatkins** [comment]
We have a similar issue with the constructor - if you pass a 3d matrix, sure, we'll set `is2D` to false.  But if you pass a 2d matrix, should we set `is2D` to true (locking it into 2d operations only) or not? (All the other operations have one or more arguments that can be either left out (2d) or set to 0/1/whatever (3d).)

One possible solution is to create two constructors, one that takes a DOMMatrix (3d) and one that takes 6 numbers (2d).

Alternately: nuts to this, just default matrixes to 3d; you can toggle it to 2d if you want manually.

We still need to answer the question from the first comment, tho.

**Comment by shans** [comment]
Another option for consideration - because CSSMatrixComponent is special we should split it (and just it) into separate 2D and 3D objects.

**Comment by tabatkins** [comment]
Yeah, I think that's probably the best, actually.

And then, hm, I guess go for the first option (enforce 2d-ness on set/get) for the 2d version? Since we can't intercept/ignore mutations on the contained matrix directly.

**Comment by trusktr** [comment]
What about just treating it the same way CSS treats it with transformList strings?

For example, this style:

```css
div {
  transform: matrix(1, 2, 3, 4, 5, 6) matrix3d(3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1);
  outline: 1px solid red;
  width: 100px;
  height: 100px;
}
```

would be the same as appending first a CSSMatrixComponent to the style map that contains a 2D DOMMatrix, then appending a CSSMatrixComponent that contains a DOMMatrix that is 3D.

I'm new to this, maybe I'm missing something, but it seems like if a CSSMatrixComponent is set to a 3D DOMMatrix, then it should just be 3D. It would be like replacing `matrix()` with `matrix3d()` in the string value nowadays.

So the style would go from (for example)

```css
div {
  transform: matrix(1, 2, 3, 4, 5, 6);
}
```

to

```css
div {
  transform: matrix3d(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);
}
```

Seems like the most intuitive way to treat it based on what we currently have today.

Ignoring the 3D values of the DOMMatrix on the other hand does not sound intuitive.

**Comment by trusktr** [comment]
Another thing that seems unintuitive would be the ability to set `is2d` on the CSSMatrixComponent and having a whole 'nother `is2d` attribute on the DOMMatrix. Why don't we just let the DOMMatrix value be the definitive source of truth, and avoid confusion (or questions like this one)?

**Comment by trusktr** [comment]
Either that, or at least have CSSMatrixComponent throw an error if is2d is true and you pass in a 3D DOMMatrix. At least that avoids confusion/ambiguity/silent errors, although I don't feel it is as clean.

**Comment by tabatkins** [comment]
The problem is that we need to distinguish between 2d and 3d transforms, and while some 3d transforms are obvious (those that are non-zero in the parts that only 3d cares about), some aren't (but they still need to trigger the extra UA work that 3d transforms cause).  Literal CSS is fine with this - the function name distinguishes them.  But we don't want to create separate interfaces for *all* the functions, as it's usually irrelevant. This is just the problematic one.

Throwing upon setting a definitely-3d matrix for a 2d matrix interface *sounds* nice, but it runs into the problem from the OP - the matrix is a sub-object that doesn't allow us to intercept its sets, so you can create an initially-2d matrix, create a CSSTransformMatrix from it, then mutate it to be 3d.  We've gotta do something about that, and just asking "is the matrix *currently* 2d-ish or 3d-ish" doesn't work well.

**Comment by shans** [comment]
Enforcing on get/set works for me. It doesn't particularly matter if using CSSMatrix2D is a bit slower because it's a special case of a special case.

**Comment by tabatkins** [comment]
Finally settled on the easiest possible answer - is2D just controls whether you pay attention to the 3d parts at all or not. Sure, you can set CSSTranslation.z to 5px if you want, who cares? It'll still stringify to just `translate(X, Y)`.  So then we can merge the Matrix classes back together and just not care about what happens if you set a 3d matrix; we only pay attention to the 2d indexes anyway.

**Comment by trusktr** [comment]
Are any of the 2D indices affected by 3D transforms?

**Comment by tabatkins** [comment]
Yeah - a 3d translate that moves in the X or Y directions definitely affects the "2d" parts of the matrix.

**Comment by trusktr** [comment]
Yeah, and a 3d translate that moves in the X or Y directions would result in essentially a transformation that can be represented by a 2D matrix.

But what about a rotation around the Y axis? Would that cause the visual result when is2D is true to be different than what the actual 3D matrix says?

If I understand your is2D idea, you means that if we set `is2D` to `true`, then we simply treat the matrix as 2D no matter what?

**Comment by tabatkins** [comment]
Yes, exactly. A matrix with is2D set just acts exactly like if you specified `matrix(...)` with the six values coming from the "2d indexes".  It just ignores the other 10 indexes entirely.

**Comment by trusktr** [comment]
What would be the result of the Y rotation when is2D is true?

**Comment by tabatkins** [comment]
Exactly what I just described.  I don't know off the top of my head what happens in the matrix when you rotate around the Y axis, but whatever it is, we just take the 6 "2d indexes" and that's the transform that the object represents.

**Comment by shans** [comment]
You'll get a foreshortening in the X direction.

Look at the matrix for R_y in the first image here: https://en.wikipedia.org/wiki/Rotation_matrix#Basic_rotations

The X scale factor is cos(theta), and not ignored. The other rotation factors get ignored. This makes sense if you think about what a flattened Y rotation would look like.
