### ISSUE TITLE
[css-typed-om] Hz/kHz are the only Numeric factory methods containing capital letters

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#367]
https://drafts.css-houdini.org/css-typed-om/#dom-css-hz

**Comment by wilddamon** [comment]
(This is probably fine, I just wanted to double check that this is intentional)

**Comment by tabatkins** [comment]
Yup, intentional. That's how those units are spelled.  (CSS doesn't happen to care, being case-insensitive, but JS does.)

I could be convinced to lowercase them, tho.

**Comment by wilddamon** [comment]
There are other JS constructs that don't lowercase things, eg Date.UTC and NaN, so I think it's fine.

Would we consider having a lowercase version as well?

**Comment by tabatkins** [comment]
I don't think it's necessary? It's not like these are commonly used units in the first place - they're provided for completeness only.

**Comment by tabatkins** [comment]
Also, @tobie says to keep them in their proper case, as that's what they'll do with Sensors if they end up exposing units. (In the #whatwg chat room.)

**Comment by wilddamon** [comment]
SGTM. I'll go ahead and implement it as Hz/kHz then :)
