### ISSUE TITLE
[worklets] No Console interface anymore

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/css-houdini-drafts#368]
The Worklets spec [defines a `console` attribute](https://drafts.css-houdini.org/worklets/#the-global-scope) with `Console` interface:

```webidl
[Exposed=Worklet]
interface WorkletGlobalScope {
    attribute Console console;
};
```

However, now [the Console spec](https://console.spec.whatwg.org/#console-namespace) does not have `Console` interface anymore and instead it defines `console` namespace, which is already defined to be exposed on worklets.

Thus I think the console attribute can be removed, what do you think?

**Comment by bfgeek** [comment]
Thanks!
