### ISSUE TITLE
[worklets] don't run scripts from "in parallel"

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#370]
import() tries to do this, that doesn't work and leads to all kinds of undefined behavior. When you run script the world needs to be in some kind of stable state.

**Comment by bfgeek** [comment]
Right but each `WorkletGlobalScope` could be in a different thread. Workers do this by saying:
"Create a separate parallel execution environment (i.e. a separate thread or process or equivalent construct), and run the rest of these steps in that context."

We could instead say:
"Each WorkerGlobalScope as a <dfn>execution environment</dfn> which may be parallel (i.e. it may be on a separate thread or process, it also may be on the same thread or process). Which thread this lives on is decided by the user-agent." 

And inside the for-loop inside import:
"Run the following steps in context of the WorkletGlobalScope's execution environment".

/cc @domenic

**Comment by annevk** [comment]
Yeah, that sounds reasonable, but `import()` can be invoked after one is created and is already running script, no? So you first need to synchronize across those possible threads somehow (usually done via message passing) before you can start running things.

**Comment by bfgeek** [comment]
`import()` in this case is only ever called from the main thread, so subsequent calls would run in the right order? This doesn't need to be explicit right?

(also did you want to review this change at all?)

**Comment by annevk** [comment]
Happy to review PRs (I found out you have a few outstanding PRs without any kind of status, might want to check those).

You do need to be explicit about ordering, since with "in parallel" the second call could happen before the first. No ordering guarantees. Also, the second call could finish during the execution of the first script, at which point you obviously can't run script, etc.

(@domenic this is another reason we need "in parallel" to become threads with message passing.)
