### ISSUE TITLE
[worklets] import() method conflicts with new JavaScript feature

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#373]
Do we still need https://drafts.css-houdini.org/worklets/#dom-worklet-import with https://github.com/tc39/proposal-dynamic-import?

cc @domenic

**Comment by bfgeek** [comment]
The import on the worklet allows the main thread to import scripts into other threads? So yes? It's analogous to workers.

e.g.
```js
new Worker('foo.js');
CSS.paintWorklet.import('foo.js');
```

_Inside_ the WorkletGlobalScope you'd use the dynamic import() function or just the regular import statement.

**Comment by bfgeek** [comment]
There was debate a while ago if `worklet.import()` should be renamed to `loadModule` instead...

**Comment by annevk** [comment]
Okay, I got confused about the setup. Having some inline examples would help. And yeah, maybe a more specific term would be good. Something like "distributeScript"? To make it more clear it ends up running multiple times against several globals.

**Comment by bfgeek** [comment]
Filed https://github.com/w3c/css-houdini-drafts/issues/374 and added an example section for what import actually does.
