### ISSUE TITLE
[worklets] imports requires WorkletGlobalScope creation to be immediate

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#377]
https://drafts.css-houdini.org/worklets/#dom-worklet-import step 4 is:

> Ensure that there is at least one `WorkletGlobalScope` in the worklet’s `WorkletGlobalScope`s. If not create a `WorkletGlobalScope` given the current `Worklet`.

This creates a new `WorkletGlobalScope` immediately, and doesn't allow `WorkletGlobalScope` creation to be in another thread. Could this step be moved into the "in parallel" steps?

**Comment by bfgeek** [comment]
This is being fixed in: PR https://github.com/w3c/css-houdini-drafts/pull/375

 :)

"create a WorkletGlobalScope" is now async and waits for the thread-hop to complete.

**Comment by asajeffrey** [comment]
Cool!
