### ISSUE TITLE
[worklets] Provide hook for allowing downstream specs to specify a CSP destination.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#378]
For example the css-paint-api spec should provide its worklet with a destination of "paintworklet".

Being more granular probably makes more sense here, instead of just a generic "worklet" destination.

**Comment by bfgeek** [comment]
Sent https://github.com/whatwg/fetch/pull/527 for fetch integration.

**Comment by bfgeek** [comment]
And sent https://github.com/w3c/webappsec-csp/pull/205 for CSP integration.

**Comment by padenot** [comment]
What is preventing this to be merged, @bfgeek ? The two PRs above are merged.

**Comment by bfgeek** [comment]
@padenot Done.
