### ISSUE TITLE
markup lanuage

### ISSUE THREAD

**Issue by joeblew99** [w3c/css-houdini-drafts#383]
I work on Polymer for Web and QT / QML for mobile and desktop.

This Paint API is amazing. It remind me allot of QT and QML, which i also use.
If you know QT and QML, QML is a markup language where you layout the control tree and also event handler (they call them slots). 
You can run the QML without and code behind it and it will run. SO it really is a markup language.
You can even compile the QML to machine code and then distribute the package without the QMl at all. This gets you much fast startup time.

My question is, is there any proposals for a markup language ?

**Comment by tabatkins** [comment]
That already exists, and is called SVG. ^_^

**Comment by joeblew99** [comment]
@tabatkins Seriously so passive agressive.

**Comment by tabatkins** [comment]
That was... meant to be a friendly response? Thus the smiley? We already have precisely what you're asking for in the web platform.

**Comment by joeblew99** [comment]
Well i took it as a blow off.
SVG is nothing at all like QML architecturally. No signal / slots as far as i know etc.

I am really interested in how programmers can get more of a WYSIWYG using this newer css stuff your working on you see. It woudl be a huge win for teams

**Comment by surma** [comment]
I agree with @tabatkins, it sounds a lot like SVG (or just HTML even). It has events (similar to signals), and listeners (similar to slots). I’m not familiar with QML, so maybe I don’t fully understand – what are those features missing? What else do you find lacking?

**Comment by meandmycode** [comment]
I think it would be worth (for the sake of those not familiar with QML) a small example of how it works, there are a lot of overlapping theory within GUI, another similar example is WPF/XAML which defines all layers (rendering, layout etc) as classes and objects and uses XAML to define graphs of objects.

I do think there is a bit of an issue when developers try to get involved in discussions with those who live it day-to-day, there's an understandable frustration with the apparent lack of domain knowledge but I see this kind of unpleasant interaction a lot and I think it's always worth spending a bit of time entertaining conversation before a patronising one liner followed immediately with **closed**.
