### ISSUE TITLE
[css-typed-om] CSSNumericValue.to should take multiple type inputs

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#391]
... so you can "cast" a type to a calc expression - e.g. collapse a calc with inches, pixels and ems to a calc with just pixels and ems.

**Comment by tabatkins** [comment]
Now that we have `toSum()`, do we want to instead move this functionality there?  So that `toSum()` (no args), just collapses as far as possible, but `toSum("px", "em")` returns something that has specifically "px" and "em" keys.

**Comment by shans** [comment]
This makes sense to me. I think this functionality is fairly specialist anyway, so it's OK for it to be slightly hidden away.

Note: we will need a constructor/factory function to convert sums back into values.

**Comment by tabatkins** [comment]
Done. `toSum()` now, appropriately, returns a `CSSMathSum` object, so there's no need for an additional factory function to turn the result back into a CSSNumericValue.
