### ISSUE TITLE
css-paint-api should give example of using border-image to draw outside the border-box

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#397]
As mentioned in https://github.com/w3ctag/design-reviews/issues/140#issuecomment-281580852, css-paint-api should have an example showing how border-image properties can be used to draw things outside of the border-box.  (Ideally, avoiding the 9-slice mess... which I think is doable.)

**Comment by bfgeek** [comment]
Fixed in  59786fd.
