### ISSUE TITLE
[css-typed-om] Allow 'none' for CSSImageValue

### ISSUE THREAD

**Issue by surma** [w3c/css-houdini-drafts#400]
`CSSImageValue` cannot represent the `none` value that both `background-image` and `border-image` accept.

This gets especially annoying when working with Custom Properties:
[`registerProperty()`](https://drafts.css-houdini.org/css-properties-values-api/#the-registerproperty-function) is currently spec’d to throw if now `initialValue` is defined when `syntax` is anything but `*`.

If I define a custom property with `syntax: <image>`, I have no way of specifying an initial value of no image except for something like

```js
    CSS.registerProperty({
        name: '--image',
        syntax: '<image>',
        initialValue: 'url(data:image/png,)',
    });
```

**Comment by tabatkins** [comment]
That's because `none` is a CSSKeywordValue. The `syntax` key accepts `<image> | none`.
