### ISSUE TITLE
[worklets] Should worklets inherit their "HTTPS state", "referrer policy" from the parent document?

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#403]
https://drafts.css-houdini.org/worklets/#script-settings-for-worklets

From: https://github.com/w3c/css-houdini-drafts/issues/396

**Comment by bfgeek** [comment]
cc/ @mikewest @domenic @annevk

**Comment by annevk** [comment]
They should, but I don't think it has any effect (until we add APIs which make them observable, which at least for referrer I believe we don't want to be doing).
