### ISSUE TITLE
[worklets] Fetching and invoking a worklet script which reports an exception

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#407]
The algorithm to fetch and invoke a worklet script (https://drafts.css-houdini.org/worklets/#fetch-and-invoke-a-worklet-script) will reject the promise if the fetch fails (step 3) but if running the module script (step 4) reports an exception, the promise will be resolved (step 5).

Should the promise be rejected if running the module script reports an exception?

**Comment by karlt** [comment]
https://github.com/w3c/css-houdini-drafts/issues/509#issuecomment-424362200 advises that Chrome should reject the promise with the module script's error to rethrow.

**Comment by karlt** [comment]
Oh, error to rethrow is determined during fetch (step 3), so that's not relevant to step 5, sorry.

**Comment by domenic** [comment]
I think this was fixed at some point in the past, and can be closed. https://html.spec.whatwg.org/multipage/worklets.html#dom-worklet-addmodule rejects the promise with the error-to-rethrow, and I copied that from the worklets spec.
