### ISSUE TITLE
[css-typed-om] Describe what setting is2D on CSSTransformComponent should do

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#414]
https://drafts.css-houdini.org/css-typed-om/#dom-csstransformcomponent-is2d

Should setting is2D to true clear out any 3D attributes on a component? For example:

```javascript
  let rotation = new CSSRotation(1, 2, 3, new CSSUnitValue(10, 'deg'));
  assert_false(rotation.is2D);
  assert_equals(rotation.z, 3);

  rotation.is2D = true;
  assert_true(rotation.is2D);
  assert_equals(rotation.z, 1);
```

Additionally, should setting is2D to false again after that restore the previous value? My guess is no, but if it did, then the following would work

```javascript
  let rotation = new CSSRotation(1, 2, 3, new CSSUnitValue(10, 'deg'));
  rotation.is2D = true;
  assert_true(rotation.is2D);
  assert_equals(rotation.z, 1);
  rotation.is2D = false;
  assert_false(rotation.is2D);
  assert_equals(rotation.z, 3);
```

The difference is whether the 3D attributes are still "there but hidden" when is2D is set to true, or whether setting is2D clobbers them.

**Comment by tabatkins** [comment]
No, under the current spec setting it to `true` just makes the 3d portions *irrelevant*.  They're not affected in any way, it just changes how you interpret the object when translating to a CSS value.

**Comment by tabatkins** [comment]
In other words: 

```js
let rotation = new CSSRotation(1, 2, 3, CSS.deg(10));  assert_false(rotation.is2D);
assert_equals(rotation.z, 3);
assert_equals(rotation+"", "rotate3d(1, 2, 3, 10deg)");

rotation.is2D = true;
assert_true(rotation.is2D);
assert_equals(rotation.z, 3);
assert_equals(rotation+"", "rotate(10deg)");
```

(Actually defining the stringifiers is still on my TODO list, but this is what's intended.)

**Comment by wilddamon** [comment]
Oh, so the getters should still return "3d" values for the transform, even when the component is set to being 2D? So you can set things, and see that they've been set, but they don't get applied. Isn't that potentially confusing for authors?

**Comment by wilddamon** [comment]
Oh, and for CSSTransformValue, if all the contained components have is2D set to true, should toMatrix still return the 3D matrix? 
https://drafts.css-houdini.org/css-typed-om/#dom-csstransformvalue-tomatrix

**Comment by tabatkins** [comment]
> Oh, so the getters should still return "3d" values for the transform, even when the component is set to being 2D? So you can set things, and see that they've been set, but they don't get applied. Isn't that potentially confusing for authors?

Yes, yes, and potentially yes, but the alternatives were more confusing and/or had very bad ergonomics.  For example, say that when is2D is set, we replace the 3d components with appropriately "null" objects, and ignore any writes to those values. But the values are objects themselves in some cases, like `CSSTranslation.z`, where it's a CSSUnitValue - we'd have to somehow communicate to *that* object that it should ignore writes as well.  That requires either a hidden flag that I check in all the algorithms, or a parallel object hierarchy of silently-readonly objects.

> Oh, and for CSSTransformValue, if all the contained components have is2D set to true, should toMatrix still return the 3D matrix?

The spec says that it multiplies their "equivalent 4x4 transform matrix"es.  This should change based on whether it's 2d or not, just like the serialization does; I should put in a note making that clearer.  Then I need to see if DOMMatrix automatically gets is2D set correctly for this case; if not, I'll need an explicit check for it.

**Comment by wilddamon** [comment]
I see what you mean - I had prototyped returning a new value for CSSTranslation.z each time if is2D was true, but that's a bit weird too.

Cool, I'll implement CSSTransformValue changing the resultant matrix depending on the is2D-ness.

**Comment by tabatkins** [comment]
> I had prototyped returning a new value for CSSTranslation.z each time if is2D was true, but that's a bit weird too.

Yeah, that's precisely the behavior that bz complained about elsewhere - attributes "feel" cheap/static, so they shouldn't create fresh objects on every read, only methods should do that.

**Comment by tabatkins** [comment]
Okay, added a note about this in 7873bee

**Comment by tabatkins** [comment]
And just checked - the is2D flag of DOMMatrix is *not* automagically set, so the algorithm now handles that.
