### ISSUE TITLE
[css-paint-api] Converting a URL to a CanvasImageSource?

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#416]
`PaintRenderingContext2D` (https://drafts.css-houdini.org/css-paint-api/#2d-rendering-context) implements `CanvasDrawImage` (https://html.spec.whatwg.org/multipage/canvas.html#canvasdrawimage), which uses `CanvasImageSource` as the type of its `image` argument (https://html.spec.whatwg.org/multipage/canvas.html#canvasimagesource).

In examples such as https://github.com/w3c/web-platform-tests/blob/740aba06484bcb174c692175493fa591d29feedd/css-paint-api/paint2d-image.html#L20, the `image` is a URL. It is not obvious from the spec how this should be converted to a `CanvasImageSource`. In particular, paint worklets do not have access to the `HTMLImageElement` class, as it is not marked `Exposed=(Window,PaintWorklet)`.

**Comment by jdm** [comment]
CanvasImageSource contains ImageBitmap, and ImageBitmap values are created by the [createImageBitmap](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#dom-createimagebitmap) API which can accept a Blob as its argument.

**Comment by asajeffrey** [comment]
Looking at what Chrome does, the properties map contains a `CSSURLImageValue` (https://drafts.css-houdini.org/css-typed-om-1/#cssimagevalue). Presumably `CanvasImageSource` is extended to allow `CSSURLImageValue` arguments?

**Comment by bfgeek** [comment]
Hey - yeah basically `CSSImageValue` becomes a valid `CanvasImageSource`, I had a PR on HTML to extend it in this way for a while, but will write the monkey patch here for the moment instead...

**Comment by asajeffrey** [comment]
@bfgeek thanks!
