### ISSUE TITLE
[css-properties-values] Apply hook triggering new style resolution?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/css-houdini-drafts#42]
During last meeting, Tab told that to accomodate changes made in the ApplyHook of css-propvals, a new round of style computation and resolution would happen to fix anything that would not be computed-compatible added by the hook.

To me, this means we've made something which is not a primitive of the web browser, but a new feature that will add more complexity to the system.

I propose we mark the ApplyHook as at-risk until we develop a ComputedStyle TypedOM and restrict the value of properties set in the ApplyHook to those values, in order to avoid any style recalc after this step.

**Comment by tabatkins** [comment]
We received pushback *during the meeting* about that, and explicitly decided against it; the ApplyHook has to emit Computed-ready values (lengths are only px, percent, or keywords, etc) or else it's an error.

**Comment by FremyCompany** [comment]
Thanks for clarifying. That's mostly what I proposed at the end of the message. 
I would tentatively be in favor of the ApplyHook take a dependency on the TypeOM because if the set of values it can take and receive both express cleanly in the set of values the new OM is supposed to accept, it would be a mistake to make it work on strings.

Could we update this issue to cover this proposal (I take on me to edit the message and title accordingly), or would you prefer me to open a new one?
