### ISSUE TITLE
[css-typed-om] Should the CSSPerspective constructor reject negative lengths?

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#420]
https://drafts.css-houdini.org/css-typed-om/#cssperspective

In the transform spec, the `<length>` taken by perspective must be positive. Should the CSSPerspective constructor throw a TypeError if the length is negative?

https://drafts.csswg.org/css-transforms-2/#propdef-perspective

**Comment by nainar** [comment]
@shans I would think that there should be bound checking in the constructor. Happy to make the spec change if you agree.

**Comment by shans** [comment]
Often you can't tell (e.g. calc(50px - 50%)). If we can figure out something consistent for cases that are knowably negative and cases that are maybe negative that would be best.

@tabatkins what do?

**Comment by tabatkins** [comment]
Nah, the OM very specifically doesn't do range-based errors. Note third paragraph of <https://drafts.css-houdini.org/css-typed-om/#numeric-objects>.  Clamping happens automatically in the style engine when needed.
