### ISSUE TITLE
[CSS Typed OM] What should CSSTransformValue's matrix if one of the components contains a relative length?

### ISSUE THREAD

**Issue by wilddamon** [w3c/css-houdini-drafts#421]
https://drafts.css-houdini.org/css-typed-om/#dom-csstransformvalue-tomatrix

For example, what if we have a CSSPerspective containing a relative length (which seems to be allowed here: https://drafts.css-houdini.org/css-typed-om/#cssperspective)?
```javascript
let t = new CSSTransformValue([new CSSPerspective(CSS.em(10))]);
t.toMatrix() // ??
```

Should the font size be the font size at the root element in the document?
Likewise for vh/vw/vmax/vmin?

**Comment by wilddamon** [comment]
I looked at DOMMatrix's spec, and it disallows <lengths> without fixed units:
"... <transform-function> has <length> values without absolute length units, throw a SyntaxError exception."
https://www.w3.org/TR/geometry-1/#dommatrix-constructors

Perhaps we should do the same for CSSTransformComponents?

**Comment by tabatkins** [comment]
> Perhaps we should do the same for CSSTransformComponents?

No, we absolutely can't do that.  You can write `matrix(3em, ...)` in CSS, so a `CSSMatrixComponent` needs to have the same capabilities.

However, we can impose this limitation when producing a DOMMatrix.  I'll amend the spec to throw some kind of error in `toMatrix()`.
