### ISSUE TITLE
[worklets] Fetching and invoking a nondeterministic worklet script

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#423]
What should happen if a nondeterminstic worklet script is fetched and invoked (https://drafts.css-houdini.org/worklets/#fetch-and-invoke-a-worklet-script)? For example, a paint worklet which returns random properties, arguments or alpha flag. The script will be evaluated multiple time (once per global), and the different executions might return different results, leaving the worklet in an inconsistent state.

**Comment by bfgeek** [comment]
So this is covered by the spec, but might be worth adding a note where we've got the "paint definition" and "document paint definition"...

https://drafts.css-houdini.org/css-paint-api/#registering-custom-paint Step 21.3.3
https://drafts.css-houdini.org/css-paint-api/#invoke-a-paint-callback Step 2.1.2

Basically if the scripts report different things, it'll wipe out the paint definition in the document, and it shouldn't be used from then onwards.

Does that make sense?

**Comment by asajeffrey** [comment]
Ah, that makes sense, I hadn't spotted that bit of the spec, thanks!
