### ISSUE TITLE
[css-typed-om] Semantics of CSSURLImageValue constructor?

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#424]
https://drafts.css-houdini.org/css-typed-om-1/#cssurlimagevalue says that CSSURLImageValue has a constructor, but not what its semantics should be. In particular, should it throw an exception if called with a string which does not parse as a URL?

**Comment by nainar** [comment]
Given a string that does not parse as a URL the CSSURLImageValue  constructor should throw a TypeError.
