### ISSUE TITLE
[css-paint][isolated-workers] What happens if a script throws?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/css-houdini-drafts#43]
This could have an impact on other scripts running in the background worker.
Should we restart the environement after such an error or not?

That's important to know for scripts which may want to share data because if the worker can be restarted during a single-frame step, there's no way to accurately pass information from one script to another (or one run to another).

**Comment by tabatkins** [comment]
> This could have an impact on other scripts running in the background worker.
> Should we restart the environement after such an error or not?

Why would that be necessary?  Errors don't corrupt the scripting environment, they just tear down the call stack until they're caught (or land at the top scripting context).  An error will just invalidate that particular call; the next one will start fresh.

> That's important to know for scripts which may want to share data because if the worker can be restarted during a single-frame step, there's no way to accurately pass information from one script to another (or one run to another).

Workers *can* be restarted in a single frame step; they can be restarted *arbitrarily*. Between every single invocation, possibly.  There is no reliable way to "stash" information between calls, and we're actively seeking to require low-impact ways to make this less reliable, like using a pool of contexts and randomly switching between them between calls.

**Comment by FremyCompany** [comment]
The issue I had in mind is that the script being stopped at some random point in execution may leave a buggy environment around it, which may cause ulterior failures. 

Maybe I'm overthinking this issue though, but I wanted to make sure someone else gave it some thought, too.

**Comment by tabatkins** [comment]
Your script shouldn't be messing with the global environment in the first place; doing it at all is a mistake, and if you fuck yourself up by getting an error before you can clean up, that's your own fault.

**Comment by FremyCompany** [comment]
Ok, good pooint
