### ISSUE TITLE
[css-paint-api] Remove alpha flag, in favour of a contextSettings flag?

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#435]
Currently we have:
```js
registerPaint('foo', class {
  static alpha = false;
});
```

Do we want this to be:
```js
registerPaint('foo', class {
  static contextSettings = {
    alpha: false;
  };
});
```

This is to allow other context settings in the future in the same object, e.g. colorSpace.

**Comment by domenic** [comment]
Why attributes? We already have enough things on the platform called attributes (IDL and content attributes). With my web dev hat on I'd pick "options".

**Comment by bfgeek** [comment]
This has been fixed, and is now `contextOptions`.
