### ISSUE TITLE
[css-paint-api] Consider adding property for expected rendered bitmap size.

### ISSUE THREAD

**Issue by flackr** [w3c/css-houdini-drafts#436]
The rendering context in https://drafts.css-houdini.org/css-paint-api-1/#2d-rendering-context defines the output bitmap size to be the size of the fragment being rendered however the actual size of the rendered bitmap used internally may vary.

In order to allow output density sensitive painting we may want to expose the size of the rendered bitmap we intend to use (or an approximation) so that the author may produce a better rendering for that output size. The author may also use this to reduce the quality of their rendering given an extremely low density (i.e. preview sized renderings may not need to paint as much) or to paint hairline lines.

Options:
1. Expose rasterBackingScale on canvas context
2. Pass additional parameter to paint.

**Comment by bfgeek** [comment]
The `devicePixelRatio` has been added on the `PaintRenderingContext2D` in the above commit.
