### ISSUE TITLE
[css-paint-api] Unnecessary paint-valid flag?

### ISSUE THREAD

**Issue by asajeffrey** [w3c/css-houdini-drafts#447]
The css-paint-api spec includes a paint-valid flag https://drafts.css-houdini.org/css-paint-api/#paint-valid-flag.

This flag is maintained as global mutable state, and is set invalid by they style engine, and valid by the paint worklets. This produces the usual problems of shared mutable state in a concurrent implementation.

The flag's main purpose is to avoid re-drawing paint images when the properties have not changed, but this is already handled by step 10 of https://drafts.css-houdini.org/css-paint-api/#invoke-a-paint-callback:

> At this stage the user agent may re-use an image from a previous invocation if paintSize, styleMap, inputArguments are equivalent to that previous invocation. If so let the image output be that cached image and abort all these steps.

Since user agents are allowed to reuse previous results, it looks like the paint-valid flag is no longer needed.

**Comment by asajeffrey** [comment]
This came up in discussion of #439 with @tschneidereit and @bfgeek.

**Comment by bfgeek** [comment]
So I think this section still has value, it might make sense to change this to being non-normative, and explaining how an engine with this type of invalidation could implement it.

Thoughts?
