### ISSUE TITLE
[css-properties-values-api] Should x and x+ interpolate if the list has only a single element?

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#449]
This isn't a spec ambiguity, but I was wondering if this might make sense.

**Comment by tabatkins** [comment]
Can you give an example of what you're imagining? A given property is only defined as one or the other; I'm not immediately seeing how one would get an `x` and and `x+` on opposite sides of an interpolation.

**Comment by jyc** [comment]
Oops, I thought I'd remembered that Typed OM allowed setting a property to a list of values, but I checked again and what I misremembered is that StylePropertyMap.set is always variadic. You're right, sorry!
