### ISSUE TITLE
[css-properties-values-api] Allowing a default invalid initialValue when syntax is not "*"

### ISSUE THREAD

**Issue by jyc** [w3c/css-houdini-drafts#453]
Right now, we allow a default invalid initial value when `syntax` is omitted or is `"*"` (discussed in #286). While writing testcases/demos for the Servo implementation, I actually expected the same to apply when the syntax was specified to be something other than `"*"`, because I normally only used typed custom properties on specific elements, e.g. for animation and felt kind of icky giving an initial value to everything on the page, and also because unregistered custom properties work that way.

Tab pointed out some [problems](https://github.com/w3c/css-houdini-drafts/issues/286#issuecomment-323851401), in particular, that the value you'd get back for the computed value might not always be an actual value of that type anyomre (it'd be `null` or `""`), and that it would most likely be an authoring error.

Overall, though, it seems to me like it would be more natural and more similar to unregistered custom properties to allow a default invalid initial value for all `syntax`es.

**Comment by nainar** [comment]
Closing this issue as a WontFix as per the Resolution
