### ISSUE TITLE
[worklets] Create ability for code to be loaded into worklets declaratively.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#47]
This is so that script doesn't have to be run to load code into an isolated worker. User agents can also do standard tricks like pre-fetching before html document is parsed.

This probably wants to be done with something like a <link> tag. I.e.

``` html
<link href="paint.js" rel="paint-worker" />
```

**Comment by upsuper** [comment]
Probably something in CSS file like `@import-worklet url;`?

**Comment by bfgeek** [comment]
Service worker has done something similar with a link element. See:
https://github.com/slightlyoff/ServiceWorker/pull/828
http://mkruisselbrink.github.io/ServiceWorker/spec/service_worker/#link-type-serviceworker

For them they use a link element like:
`<link rel="serviceworker" href="/js/sw.js" scope="/">`

We'd probably do something similar like:
`<link rel="workletname" href="/js/sw.js">`

There was talk in the Sydney F2F that we might want to use the `<script>` tag instead, however it seems like, link is a better fit here.

@upsuper Yup, something in CSS would also be nice :+1:

**Comment by atanassov** [comment]
From Houdini F2F Seattle - recommend adding a section that describes the feature in a declarative form even if it is not complete.

**Comment by domenic** [comment]
Let's consolidate this and the other related issues into https://github.com/whatwg/html/issues/6073.
