### ISSUE TITLE
[css-typed-om] Should it be illegal to construct CSSKeywordValue objects with empty strings?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#477]
CSSKeywordValue constructor: https://drafts.css-houdini.org/css-typed-om-1/#csskeywordvalue

The constructor currently accepts empty strings, but CSS keywords can't be empty strings. Should the constructor throw an exception in this case? And similarly for when we set the 'value' attribute on an existing CSSKeywordValue object?

**Comment by tabatkins** [comment]
Yes, I think it should - unlike the other cases where a keyword *can* be constructed with those contents using escapes, you can't produce a keyword with no value at all.

**Comment by nainar** [comment]
Going to mark this as Needs-Edits?
