### ISSUE TITLE
[css-typed-om] What should CSSNumericValue.type() do?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#482]
Currently the IDL just says `??? type()` and there's an issue saying " Figure out how we want to represent the type of an expression in JS, and define the type() method accordingly.", but there's no GitHub issue associated with it.

@shans Seems like we already have wording for the type of a numeric value, but just need to decide how to represent it in Javascript?

**Comment by tabatkins** [comment]
Yeah, the abstract "type" of a numeric value is a map of units to powers. We could simply reflect that, but it's not clear how useful it is.

**Comment by nainar** [comment]
Seems like I suck as a scribe. The resolution should have read 

RESOLVED: type() will be a map of types to powers. @tabatkins as FYI.

**Comment by darrnshn** [comment]
Thanks @nainar. @tabatkins are we also going to expose the [percent hint](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-percent-hint)? Not that there's much use for it.

**Comment by tabatkins** [comment]
Yeah, pretty much all the algos working on types need to look at the percent-hint; if anything in userland wants to work with types, it'll need it too. We shoudl just expose it as another key in the map, like "percent-hint".

**Comment by darrnshn** [comment]
Fixed in #546
