### ISSUE TITLE
CSSNumericArray should be an Array-like restricted to containing CSSNumericValue objects. 

### ISSUE THREAD

**Issue by nainar** [w3c/css-houdini-drafts#486]
This is dependent on [WebIDL#345](https://github.com/heycam/webidl/issues/345) getting resolved properly

**Comment by darrnshn** [comment]
Just to ensure I understand the issue: We would like 'values' to be an object that acts like an array but also has type checking to ensure every element is CSSNumericValue? Did we end up deciding whether to use get/set or [] as the interface?

**Comment by tabatkins** [comment]
> Just to ensure I understand the issue: We would like 'values' to be an object that acts like an array but also has type checking to ensure every element is CSSNumericValue?

Yes. We have to do that type-checking at *some* point, and it's bad for both understandability and perf to do that at the point you actually try to set the value to some property.  (You can get at-time-of-mistake errors for every other sort of API, it's just arrays that don't allow it right now.)

The plan for now is to go with the "full Proxy" solution (indexed getters/setters), which gives us the `val[x]` syntax, and when WebIDL fixes this to give us cheaper numeric-property traps, switch the spec to that.
