### ISSUE TITLE
[css-typed-om] What is CSSMathValue.type?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#492]
I'm probably missing something here, but what is [CSSMathValue.type](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssmathvalue-type)? The spec mentions what type of a CSSMathValue should be, but that type links to [CSSNumericValue.type](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-type), which is a map not a string.

**Comment by tabatkins** [comment]
It's a remnant of the world before we made things more complex. This seems like basically a dupe of #482, right?

**Comment by darrnshn** [comment]
Ah right, does that mean we could just remove CSSMathValue.type, since it inherits CSSNumericValue's type() method?

**Comment by tabatkins** [comment]
Yeah, we should.

**Comment by nainar** [comment]
Fixed by #497
