### ISSUE TITLE
[css-typed-om] Do CSSMathValue subclasses copy their constructor arguments?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#494]
When you pass CSSNumericValues to construct a subclass of CSSMathValue, do the arguments get copied? For example,
```javascript
let x = CSS.px(1);
let y = CSS.px(1);
let sum = CSSMathSum(x, y);
// Q: are sum.values[0] and x the same object?
x.unit = 's'; // Should this be an error since now sum is adding a length with time?
```

I couldn't really find any wording for this; sorry if this was already implicit in the spec. 

Spec: https://drafts.css-houdini.org/css-typed-om-1/#dom-cssmathsum-cssmathsum

**Comment by nainar** [comment]
Transcribing conversation with Tab.

Q: are sum.values[0] and x the same object?
Yes. The first step says, "Replace each item of args with the result of rectifying a numberish value for the item." In this case the item would be equal to x.

**Comment by nainar** [comment]
Marking the second question as Needs-Feedback.

**Comment by darrnshn** [comment]
I asked Shane and it looks like when you're mutating an expression tree, it should propagate type checking up. So setting `x.unit = 's'` should be an error. I couldn't find anything in the spec that explicit states this though; maybe we should add a note?

**Comment by tabatkins** [comment]
So the resolution doesn't solve this problem. It prevents you from changing the overall type of something *if it's only composed of CSSUnitValues*, but not if it's composed of CSSMathValues.  That is, this is still allowed:

```
let child = new CSSMathProduct(CSS.px(5));
let parent = new CSSMathSum(child, CSS.px(10));
// parent == calc(calc(5px) + 10px), everything's good
child.values[0] = CSS.s(5)
// parent == calc(calc(5s) + 10px), invalid!
```
