### ISSUE TITLE
[css-typed-om] CSSUnparsedValue constructor behaviour if arguments are not alternating

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#495]
In the [wording for the tokens internal slot](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssunparsedvalue-tokens-slot) of CSSUnparsedValue, it says that `tokens` is "a list of alternating DOMString and CSSVariableReferenceValue objects". What happens if a [CSSUnparsedValue was created](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssunparsedvalue-cssunparsedvalue) with non-alternating tokens? e.g.

```javascript
new CSSUnparsedValue('foo', 'bar');
```

**Comment by tabatkins** [comment]
That statement is just wrong in the first place - I think `--foo:var(bar)var(baz);` would have two variables references in a row, without a string in the middle. (Theoretically we could put an empty string there, but why?)  I should remove it.

**Comment by shans** [comment]
I don't think I ever intended it to mean strictly alternating. The sense was that you could alternate back and forth between the two types in a single list (as opposed to either having a list of one or a list of the other).

We definitely should reword to make this less confusing, but I think it'd be good to retain that sense somehow.
