### ISSUE TITLE
[css-typed-om] Should CSSNumericValue attributes accept doubles?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#498]
CSSMathNegate has a [CSSNumericValue 'value' attribute](https://drafts.css-houdini.org/css-typed-om-1/#cssmathnegate), so you can't set it to a double. But the spec also says: "Any place that accepts a CSSNumericValue also accepts a raw double". So should you be able to set CSSMathNegate.value to a double, or does 'place' mean like a function?

**Comment by darrnshn** [comment]
On a similar note, the [various transform style](https://drafts.css-houdini.org/css-typed-om-1/#transformvalue-objects) constructors seem to be inconsistent about whether they're taking CSSNumericValues (e.g. translate) or CSSNumberishes (e.g. rotate). Is there a reason for this?

**Comment by tabatkins** [comment]
Ah, that attribute should be a `CSSNumberish`, thanks.

**Comment by darrnshn** [comment]
Cool thanks! In general, when should something be a `CSSNumericValue` vs `CSSNumberish`? Based on the "Any place that accepts a CSSNumericValue also accepts a raw double", I'm guessing the only place where you can have a `CSSNumericValue` is readonly attributes (since they don't "accept" `CSSNumericValues`) and everything other occurrence of `CSSNumericValue` should be a `CSSNumberish`?

**Comment by tabatkins** [comment]
Any input that can potentially accept a CSS `<number>` (or, in TypedOM language, any place where a CSSUnitValue with a type of "number" would be valid) should be a `CSSNumberish`.  Many numeric attributes don't qualify; the difference in the transform style constructors is deliberate, as translate() only takes lengths.

Output should always be `CSSNumericValue`, as we'll always output TypedOM objects.  (So yeah, readonly attributes are `CSSNumericValue`, read/write attributes are `CSSNumberish` *if* they can accept a `<number>` value.)

(`CSSKeywordish` is more absolute - *all* keyword-accepting input should be `CSSKeywordish`. There's no conglomeration of value spaces to worry about here.)

-------

Note: I wrote my earlier comment based on the first comment in the thread, coming straight off of the email. I hadn't seen the second comment. I was specifically referring to `CSSMathNegate` needing to be switched to `CSSNumberish`, not referring to the transform stuff.
