### ISSUE TITLE
Should registerProperty/unregisterProperty be on CSS or Document?

### ISSUE THREAD

**Issue by shans** [w3c/css-houdini-drafts#50]
<EOM>

**Comment by frivoal** [comment]
What's the argument for not having in on CSS?

**Comment by shans** [comment]
At the moment, I don't think the scope of CSS is defined, and all functionality exposed by it is static.

Presumably property registration should have Document scope. If we don't want to tie CSS to Document scope then that would be an argument.

Also there's a bunch of stuff already on Document like registerElement, stylesheets, etc. This feels a bit like that stuff.

On the other hand, putting this on CSS seems to make sense too.

**Comment by frivoal** [comment]
I had assumed that CSS had a Document scope, but you're right, that's undefined, and maybe we don't want it that way.

As for having a bunch of stuff on Document, that's true, but the various things there don't all feel like they belong together. Many do relate to the document, but others (e.g. Document.registerElement()) merely have the same lifetime.

**Comment by shans** [comment]
After discussion with Tab: CSS is Window scoped, and properties should probably be registered at Window scope too. So it seems like CSS is the right place for this.
