### ISSUE TITLE
[css-typed-om] Should StylePropertyMap.set work even when the property is not in the property model?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#501]
With [StylePropertyMap.set](https://drafts.css-houdini.org/css-typed-om-1/#set-a-value-on-a-stylepropertymap), if I do something like
```
styleMap.set('width', '10px')
```
and the styleMap doesn't have 'width', the spec says it's a no-op ("If StylePropertyMap’s property model contains an entry for property, let entry be that entry. Otherwise, exit the algorithm."). Intuitively, `set` should work independent of whether width is in the property model or not right?

**Comment by tabatkins** [comment]
Ah, yup, the "property model" is just the set of properties that the stylemap currently knows about. `.set()` shouldn't be consulting that in this way. It *should* check - there's [a related plain-CSSOM issue about ordering properties by the way they're set](https://github.com/w3c/csswg-drafts/issues/1898), so the algo should check if the property is already in the property model and *delete it* if so, then append its value to the end.

**Comment by nainar** [comment]
Fixed by Tab's rewrite
