### ISSUE TITLE
[css-typed-om] Simplifying expressions in CSSMathValue subclasses.

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#503]
In [the algorithm for adding CSSNumericValues](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-add), we have an explicit step (Step 3) for simplifying the expression if all values are `CSSUnitValues` with the same unit. However, none of the other subclasses seem to have this step, even though theoretically it should be possible (e.g. `min(2px, 3px) == 2px`). The inconsistency is a bit confusing and makes addition a special case in terms of implementation. Is there any particular reason for making addition simplify but not the others?

**Comment by tabatkins** [comment]
.add(), .sub(), and .negate() all have special cases.  (.sub() has it by virtue of calling into the .add() algo.)

.mul() *could* have a special-case here - check if `this` + every value is a CSSUnitValue with type=number, or at most one has a different type, then return a plain CSSUnitValue accordingly.

.div() could have a special case - if this+values are all `CSSUnitValue`, and all the values (not `this`) are number type, we can return a CSSUnitValue.

.invert() could special-case a number type.

I agree that .min() and .max() could have the exact same special-case as .add().

Happy to add these in if others think they're good ideas.
