### ISSUE TITLE
[css-typed-om] CSS.q() should be CSS.Q() or CSS.Hz() should be CSS.hz()

### ISSUE THREAD

**Issue by ewilligers** [w3c/css-houdini-drafts#504]
The CSS WG recently [resolved](https://www.w3.org/blog/CSS/2017/10/11/minutes-telecon-341/) to use upper case for Q in the spec text. This is similar to Hz and kHz.

When serialized in CSSUnitValue.unit, the unit should be lower case, like 'hz' and 'khz'.

The case used in the CSS [factory functions](https://drafts.css-houdini.org/css-typed-om-1/#numeric-factory) is currently inconsistent: use  Q Hz kHz  or  q hz khz.

**Comment by tabatkins** [comment]
Yeah, we should def be consistent. I don't have a strong opinion on which way it should be, tho.
