### ISSUE TITLE
[worklets] restrict worklets to SecureContexts

### ISSUE THREAD

**Issue by jeisinger** [w3c/css-houdini-drafts#505]
Blink decided to restrict CSS Paint to secure contexts for now, amongst other reasons because of the worklets.

E.g. the Web Audio WG also looked at this, and decided to just do whatever worklets does.

Opening this issue to track whether the worklet spec should be restricted to secure contexts, or whether the individual APIs should have this restriction.

/cc @annevk @mikewest

**Comment by hoch** [comment]
Reference: https://github.com/WebAudio/web-audio-api/issues/1436

**Comment by nhiroki** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=779938

**Comment by domenic** [comment]
With https://github.com/whatwg/html/pull/6056, we can close this. The HTML Standard reflects implementation reality wherein worklets are restricted to secure contexts.
