### ISSUE TITLE
[worklets] dynamic import()

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#506]
I thought we already had an issue for this somewhere. If worklets cannot have `fetch()`, I don't think it makes sense for them to have dynamic `import()`. That would cause the same kind of execution problems.

cc @domenic @nhiroki @bfgeek

**Comment by annevk** [comment]
See https://github.com/whatwg/fetch/pull/527#issuecomment-342038491 for issues if we decide to allow it somehow.

**Comment by bfgeek** [comment]
I agree that it makes sense we shouldn't have `import()`.

**Comment by bfgeek** [comment]
I'm not sure what the behaviour should be, if `import()` is just hidden, or it throws. :/

**Comment by surma** [comment]
If we are disallowing it, I’d say hide it. A function whose only purpose is to throw seems odd.

**Comment by domenic** [comment]
It's not a function; it's syntax. It can't be removed without language changes. I'm not even sure what hiding it would mean.

**Comment by bfgeek** [comment]
Oh didn't realize that, makes sense.

**Comment by annevk** [comment]
@domenic I assume we can make it reject the promise it returns? (Depending on what data gets passed to Fetch, we could even return a network error there for all fetches made by worklets. Not sure that's ideal however as it's unlikely to be implemented that way.)

**Comment by domenic** [comment]
Yeah, that's doable.

**Comment by nhiroki** [comment]
Filed a [tracking issue](https://bugs.chromium.org/p/chromium/issues/detail?id=782538) in crbug.

**Comment by domenic** [comment]
To be clear, I don't think we _should_ reject import() in worklets, per my position from the earlier thread on the same topic. I think all forms of importing code should work in worklets, including lazily importing. I was only commenting on the technical feasibility here.

**Comment by annevk** [comment]
I wonder how worklets work with the opaque origin setup if their modules can have non-dynamic imports. Did you review that @domenic? Or maybe the opaque origin is assigned after all dependencies are fetched?

The main reason to block dynamic `import()` is the same reason we block `fetch()`; to make it clear worklets are not supposed to have that kind of code.

**Comment by nhiroki** [comment]
> I wonder how worklets work with the opaque origin setup if their modules can have non-dynamic imports. Did you review that @domenic? Or maybe the opaque origin is assigned after all dependencies are fetched?

IIUC, non-dynamic imports are handled as sub-resources of the owner document like ```addModule()```, so the opaque origin is not a problem. Chromium implemented this behavior and there are [WPT tests](https://github.com/w3c/web-platform-tests/blob/master/worklets/resources/import-tests.js#L29) for the case.

**Comment by annevk** [comment]
Thanks. But the referrer would be the top-level module script's (base) URL? So yeah, if we want dynamic `import()` to work we'd need some justification as to why that's okay and `fetch()` is not and then figure out how it should actually work as per the comment following OP.

**Comment by nhiroki** [comment]
> But the referrer would be the top-level module script's (base) URL?

Yes. It's the same with plain ES6 modules. I'm now adding WPT tests for the referrer of descendant scripts ([crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=773921)).

**Comment by bfgeek** [comment]
Part of the justification that it shouldn't work for me at least, is that worklet global scopes are allowed to be transient, and when they are created again they _should_ contain all the same code as the other WGS. Allowing the dynamic import here makes it a little too easy for them to diverge.

We won't be able to remove all non-deterministic apis, but this one seems easy to reason about?

**Comment by domenic** [comment]
I don't think we should be piecemeal disabling parts of the JS language. It should be principled, e.g. adding a switch that disables dynamic import and Math.random() and Date.now()/new Date()/etc. at the same time.

**Comment by annevk** [comment]
It is principled, no network APIs.

**Comment by domenic** [comment]
Then static import should be disallowed.

**Comment by annevk** [comment]
Why? Those are all resolved before execution.

**Comment by domenic** [comment]
They're still network APIs, so it seems the line is not very principled?

**Comment by bfgeek** [comment]
Anne is right. This keeps inline with "no communication to the outside world" once you've added the scripts, i.e. no networking apis.

**Comment by nhiroki** [comment]
What error code does ```import()``` return on WorkletGlobalScope? ```NotSupportedError```?

**Comment by nhiroki** [comment]
If there is no objection, I'm going to make ```import()``` on WorkletGlobalScope reject the promise with ```NotAllowedError``` ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/790059)).

**Comment by annevk** [comment]
Apologies for not replying sooner. I think `TypeError` would be better for a JavaScript language construct.

**Comment by nhiroki** [comment]
@annevk Thank you! ```TypeError``` sounds good. I didn't know ```NotSupportedError``` is not a native error type defined in the [ECMAScript spec](https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard). I'll update the CL.
