### ISSUE TITLE
[worklets] addModule() should reject a promise with a more specific exception

### ISSUE THREAD

**Issue by nhiroki** [w3c/css-houdini-drafts#509]
The current spec defines that ```addModule()``` rejects a promise with "AbortError" DOMException in any case:

> 2. Reject promise with an "AbortError" DOMException.
> (see https://drafts.css-houdini.org/worklets/#fetch-and-invoke-a-worklet-script)

This obfuscates the reason why ```addModule()``` failed and makes it hard to debug. It would be nice to reject it with a more specific exception like "NetworkError" and "SyntaxError".

**Comment by nhiroki** [comment]
Filed an issue in crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=782066

**Comment by hiroshige-g** [comment]
How about using module script's error to rethrow? (If the module script is non-null)
https://html.spec.whatwg.org/multipage/webappapis.html#concept-script-error-to-rethrow

**Comment by nhiroki** [comment]
@hiroshige-g Sounds good.

@bfgeek Would it be possible to change the worklet spec based on hiroshige's suggestion? According to the feedback on chromium's bug tracker, this makes it difficult for developers to use worklets.

(cc/ @majido @surma )

**Comment by bfgeek** [comment]
@nhiroki I won't have time to make the spec change until later, but it sounds good, and you should make the change in chrome. If you cc me on the patch I can make sure it'll work with the spec.

If you like you can always submit a PR to the spec!

Ian

**Comment by nhiroki** [comment]
@bfgeek Thanks! I'll make a patch for chrome and try to change the spec.

**Comment by nhiroki** [comment]
It turned out that Error objects are not cloneable (see [crbug.com/82066#c10](https://bugs.chromium.org/p/chromium/issues/detail?id=782066#c10) for details) and cannot be passed between threads. It may be necessary to re-construct an Error object on the document side.

**Comment by guest271314** [comment]
Related https://github.com/WebAudio/web-audio-api/issues/1846. A `DOMException` is thrown at Chromium 72 if the URL passed to `.addModule()` is a `404` (thrown by `import` and `import()`).

**Comment by karlt** [comment]
Error objects can now be cloned.  See https://github.com/whatwg/html/issues/4268
