### ISSUE TITLE
[worklets] WebAudio API does allow multiple global scopes

### ISSUE THREAD

**Issue by svgeesus** [w3c/css-houdini-drafts#510]
Just noticed this:

> Note: Specifically the [css-paint-api-1] allows for multiple global scopes, while the [webaudio] API does not.
https://drafts.css-houdini.org/worklets/#worklet-section

This is incorrect, audio worklet can also have multiple global scopes.

**Comment by domenic** [comment]
This can be closed; it was removed and replaced with more generic language in https://html.spec.whatwg.org/multipage/worklets.html
