### ISSUE TITLE
[css-typed-om] List-valued property iteration of property

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#511]
What does "list-valued property iteration of property" mean in the [coercion algorithm](https://drafts.css-houdini.org/css-typed-om-1/#algorithm-that-coerces-value-into-an-appropriate-type-for-a-given-property)?

**Comment by tabatkins** [comment]
The intention of this is that the CSSStyleValue needs to match the grammar of one comma-separated repetition of the property, not the entire property. Like, a single background-layer, not the entire list of background layers. It is indeed written confusingly.

**Comment by tabatkins** [comment]
Fixed.
