### ISSUE TITLE
[css-typed-om] StylePropertMap.set for non-list properties

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#512]
What should StylePropertyMap.set do for non-list properties when given multiple arguments? e.g.

```
styleMap.set('width', CSS.px(1), CSS.px(2), CSS.px(3));
styleMap.getAll('width'); // ???
```

According to the [spec](https://drafts.css-houdini.org/css-typed-om-1/#set-a-value-on-a-stylepropertymap), the "property model" will contain an entry `("width", [1px, 2px, 3px])`. It's then unclear what `getAll` should return. If we follow the [spec](https://drafts.css-houdini.org/css-typed-om-1/#get-all-values-from-a-stylepropertymap) strictly, we return `[[1px, 2px, 3px]]` (a single-element list containing a 3-element list), which is probably not right... Should `set` throw an exception or just set the first element?

**Comment by tabatkins** [comment]
Actually, it just silently treats all properties as list-valued, even when they're not. This is still a bug tho - it's inconsistent with how .append() works on single-valued properties (it throws). We should be consistent here and just throw in both situations, so calling .set() on a single-valued property with more than one value should throw a TypeError.
