### ISSUE TITLE
[css-typed-om] Could CSSVariableReferenceValue have a constructor?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#514]
Could we add a constructor to [CSSVariableReferenceValue](https://drafts.css-houdini.org/css-typed-om-1/#cssvariablereferencevalue)? It's not exactly clear why there isn't one, since we can already create any sort of CSSVariableReferenceValue by changing its attributes. It would make writing tests a lot easier :)

**Comment by tabatkins** [comment]
Yeah, it should have a constructor.

And then .fallback should be readonly, so you can't set a variable reference as its own fallback. (Same as #513 for math stuff.)
