### ISSUE TITLE
[css-typed-om] Should type of CSSMathNegate be the same as its argument?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#516]
According to the [spec](https://drafts.css-houdini.org/css-typed-om-1/#type-of-a-cssmathvalue), the type of a `CSSMathNegate` is the same as the type of its argument but with entries negated. So `CSSMathNegate(1px)` has type `[ length -> -1 ]`, but `-1px` has type `[ length -> 1 ]`. Should the type of `CSSMathNegate` just be the type of its argument?

**Comment by tabatkins** [comment]
Oh shoot, yeah, it should be the same type. It just negates the values; the type is left unchanged.
