### ISSUE TITLE
[css-typed-om] Why the property model is defined to be a list of pairs, rather than an ordered map?

### ISSUE THREAD

**Issue by triple-underscore** [w3c/css-houdini-drafts#517]
The structure of the term “property model” ( https://drafts.css-houdini.org/css-typed-om-1/#property-model ) is defined to be a list of (property / sequence of values) pairs, but I could not find spec text saying or requiring that there can be multiple entries for a given property in a property model.

It seems more natural and clearer to define it as an ordered map (such as defined in WHATWG Infra standard).

**Comment by tabatkins** [comment]
Agreed.

**Comment by nainar** [comment]
Fixed by: https://github.com/w3c/css-houdini-drafts/commit/3a4541b369ebff2d7eff1d1f58c101e4ec83ef9f
