### ISSUE TITLE
[css-typed-om] Should CSSURLImageValue serialize with quotes?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#519]
The [spec](https://drafts.css-houdini.org/css-typed-om-1/#urlimagevalue-serialization) says that `CSSURLImageValue` serializes to `"url(" + url + ")"`. Unless the quotes implied when serializing the `url` attribute, the result will not contain quotes (e.g. `url(www.google.com)` and `url("www.google.com")`). Should the serialized string have quotes?

**Comment by tabatkins** [comment]
Yes, it should have quotes. The quoteless form can't represent all URLs, and it's something we discourage anyway.
