### ISSUE TITLE
[css-typed-om] Should the product of two unit maps be addition instead of union?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#520]
In the spec (Step 2.3.1.1 for CSSMathProduct in the [sum value section](https://drafts.css-houdini.org/css-typed-om-1/#sum-value)) for multiplying two unit maps, the wording says to take the union of the unit maps. I might be misunderstanding unit maps, but wouldn't that make something like `1px * 1px == { px -> 1 }` instead of `1px * 1px == { px -> 2 }`? Should we add the entries/exponents in the two unit maps instead (like in types)?

**Comment by tabatkins** [comment]
Ah, that's what's intended by "union" (result should be `{px -> 2}`), but I agree that it's unclear as written.

I should be explicitly linking to [multiplying types](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-multiply-two-types).

**Comment by darrnshn** [comment]
Fixed by #593
