### ISSUE TITLE
[css-typed-om] Add example of normalizing n-ary math operators

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#521]
Let's add an example of normalizing something like `calc(1 + 2 + 3)`, which returns `new CSSMathSum(1, 2, 3)` as opposed to `new CSSMathSum(new CSSMathSum(1, 2), 3)`.

**Comment by tabatkins** [comment]
And related, an example of normalizing `calc(calc(1 + 2) + 3)`, which *does* normalize to your second example.

**Comment by darrnshn** [comment]
Fixed in #532
