### ISSUE TITLE
[css-typed-om] Normalizing 'top' as CSSPositionValue

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#522]
Following the [algorithm](https://drafts.css-houdini.org/css-typed-om-1/#positionvalue-normalization), `top` is a single keyword, so we go into [this case](https://drafts.css-houdini.org/css-typed-om-1/#from-single-keyword) with value `top` and bias `horizontal`. With these parameters, we would skip all the if statements and land on the else (step 6): If value is not the keyword "center", then this process fails. Since `top` is not `center`, we fail.

Did I interpret this right? I'm guessing this is not intended...

**Comment by tabatkins** [comment]
This is definitely wrong, but I'm not sure exactly what it's trying to do; this algo is written too algorithmically for me.

It definitely *should* be treated the same as `top center`, tho.  Just need to see if any other cases need similar fixups or what.

**Comment by darrnshn** [comment]
After staring at this for a bit, the algorithm might work if we initialize the bias to `auto` when handling the single value case.
