### ISSUE TITLE
[css-typed-om] Should CSSVariableReferenceValue.variable setter reject invalid variable names?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#524]
There's currently [no validation done](https://drafts.css-houdini.org/css-typed-om-1/#cssvariablereferencevalue) when you update `CSSVariableReferenceValue.variable`. Should we throw a `SyntaxError` if the variable is not a valid custom property name?

**Comment by tabatkins** [comment]
Hmm, yeah, it should.
