### ISSUE TITLE
[css-typed-om] CSSNumericValue.to could return a CSSUnitValue

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#525]
A bit of a nit :) The [return type](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-to-unit-unit) of `CSSNumericValue.to` is currently `CSSNumericValue`, but I think we could change it to `CSSUnitValue`. I only raised this issue for consistency since `CSSNumericValue.toSum` returns a `CSSMathSum` and not a `CSSNumericValue`.

**Comment by tabatkins** [comment]
Agreed.

**Comment by nainar** [comment]
Fixed by #527
