### ISSUE TITLE
[css-typed-om] can <calc> normalization from parsing/cssom simplify the expression?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#528]
If I'm getting a calc from the style property map, should it be simplified or not?
```
testDiv.style.width = 'calc(1px + 1px)';
testDiv.attributeStyleMap.get('width') // CSSMathSum or CSSUnitValue?
```

I think the [typed OM spec](https://drafts.css-houdini.org/css-typed-om-1/#stylevalue-normalization) says it should return a `CSSMathSum`. However,  Blink currently simplifies `<calc>` expression during parse time, so I don't know if we're allowed to return the simplified expression (`CSSUnitValue`) or maybe if returning the original expression contradicts another spec (the [css values module 3 spec](https://drafts.csswg.org/css-values-3/#calc-notation) doesn't seem to say anything about this).

On the one hand, it makes intuitive sense to retain the original calc structure. On the other hand, normalization is converting `<calc>` values to `CSSStyleValues`, but doesn't necessarily mandate how to go from strings to `<calc>`s (including whether simplification at parse time is allowed).

**Comment by tabatkins** [comment]
The normalization process just takes a CSS value and turns it into an object. It has no opinion on what the value is; that's determined by CSS. And in this case, the calc() spec says that expressions like `calc(1px + 1px)` are indeed simplified into `calc(2px)` at computed-value time, so it would get reflected as a `CSSMathSum(CSS.px(2))`.

On the other hand, asking for the specified value of that should return a `CSSMathSum(CSS.px(1), CSS.px(1)`; so should just doing `CSSMathValue.parse("calc(1px + 1px)")`.

**Comment by darrnshn** [comment]
I just did a quick test and looks like both Chrome and FF simplify the specified value for calcs:
```
document.body.style.width = 'calc(1px + 1px)'
document.body.style.width; // calc(2px)
```

The [calc spec](https://drafts.csswg.org/css-values-3/#calc-notation) doesn't seem to say much about this, so it looks like computed, specified and parsing all should simplify calc expressions (at least until the calc spec becomes clearer about this).

I don't know if any actual edits are required in the Typed OM spec, but we should definitely make sure that any examples involving calcs are simplified.

**Comment by tabatkins** [comment]
Read the [calc() serialization section](https://drafts.csswg.org/css-values/#calc-serialize) - it talks about this a bit. Technically, as specified, this doesn't affect the actual values, just how you produce a string from them; in reality, these should apply to the underlying value, and we just agreed in the call today to do that too. ^_^

So yeah, at specified-value time we merge `px` values (but would leave `calc(1px + 1in)` alone); at computed-value time we convert units around to produce more identical-ness (so `calc(1px + 1in)` becomes `calc(97px)`, `calc(1px + 1em)` becomes `calc(16px)` or whatever), and then at used-value time we finish converting everything to px so we always have a `calc(Xpx)` and nothing else.

**Comment by darrnshn** [comment]
Ah I see, I wasn't aware of the new (level 4) spec :) the old spec just said serialization was undefined at that level. But yeah what you said makes sense.

**Comment by darrnshn** [comment]
Sorry, just to check my understanding: in the [type checking section](https://drafts.csswg.org/css-values/#calc-type-checking), it says that a multiplication or division must have a `<number>` on one side, which means that [they can always be simplified](https://drafts.csswg.org/css-values/#math-function-simplify-an-expression). Does this imply that we will actually never normalize multiplication or division? Should we remove the wording for normalizing products / division then?

**Comment by tabatkins** [comment]
Under the previous "no unit algebra" rules for calc(), yes, multiplications/divisions never actually show up in the result - you can always simplify the expression into a sum of unit-values (or min()/max(), now).

But Typed OM implicitly allows unit algebra (expressions like `5px/1em`), and Values 4 will allow it as soon as I finish writing the text for it (which I started before winter break), per WG resolution.

**Comment by darrnshn** [comment]
I see. So basically Values 4 will behave like Typed OM once it's written. In that case I don't think any edits are needed by this issue.
