### ISSUE TITLE
[css-typed-om] Should percents be allowed for CSSTranslation.z?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#530]
According to the [spec](https://drafts.css-houdini.org/css-typed-om-1/#dom-csstranslation-csstranslation), `CSSTranslation.z` can be a percent, but [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate3d) suggests that the Z value can't be a percent. Should `CSSTranslation.z` only match `<length>` and not `<length-percentage>`?

**Comment by tabatkins** [comment]
Yes.
