### ISSUE TITLE
[css-typed-om] Is CSSTransformValue.is2D true when given no transforms?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#534]
I'm not quite sure what [CSSTransformValue.is2D](https://drafts.css-houdini.org/css-typed-om-1/#dom-csstransformvalue-is2d) should return if there are no transforms.

**Comment by tabatkins** [comment]
It shouldn't return anything, because we should make the constructor arg non-optional, and add a check to the constructor that it has at least one element, just like the CSSMathValue constructors do.
