### ISSUE TITLE
[css-typed-om] Transform serialization wording should be rephrased

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#548]
Following the [algorithm for serializing transforms](https://drafts.css-houdini.org/css-typed-om-1/#transformvalue-serialization):

- Serializing `new CSSTranslation(0, 0)` would give `translation(0, 0)` instead of `translate(0, 0)` (need to remove the `tion`).
- Serializing `new CSScale(0, 0, 0)` would give `scale(0, 0, 0)` instead of `scale3d(0, 0, 0)` (need to append `3d`).

**Comment by darrnshn** [comment]
Hi @tabatkins , would it make more sense to change the serialization algorithm to explicitly map `CSSTranslation` to `translate` or to rename `CSSTranslation` to `CSSTranslate`?

**Comment by tabatkins** [comment]
That algo in general needs to be substantially rewritten. :(

But yeah, I'd support renaming to `CSSTranslate` and `CSSRotate`.

**Comment by darrnshn** [comment]
Sorry, unclaiming this. Bit off more than I could chew :P

**Comment by tabatkins** [comment]
Fixed in 7669657
