### ISSUE TITLE
[css-typed-om] Should StylePropertyMap.set be exposed to worklets?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#549]
From the [original issue](https://github.com/w3c/css-houdini-drafts/issues/237#issuecomment-351227807), it sounds like only `.parse` and `.parseAll` are not exposed to worklets. However, `StylePropertyMap.set` can take strings as arguments and will perform parsing. Is this problematic if it's called from a worklet?

**Comment by nainar** [comment]
No, currently StylePropertyMap.set isn't useful to be exposed to worklet. So let's restrict it to Window only for now.

**Comment by tabatkins** [comment]
We also need to restrict `append()` and `update()`, as they have the same problems. At that point the only function left for worklets is `delete()`, which makes me think we just shouldn't expose the interface *at all*, and only give them CSSStyleMapReadOnly. Thoughts?

**Comment by tabatkins** [comment]
(Also, hm, I think that if we don't expose the method, it'll get the default implementation from being maplike? If that's the case, then we *do* need to expose it, but throw immediately.)

**Comment by nainar** [comment]
To make sure I understand what you are saying correctly:

PaintWorklet exposed:

- StylePropertyMapReadOnly

Window expose: 

- StylePropertyMap

If we do this we don't have the problem of the default implementation being available in PaintWorklet no?

**Comment by tabatkins** [comment]
Right, then it's just plain not editable at all, so no parsing required. ^_^

(And StylePropertyMapReadOnly is exposed to *both* Window and PaintWorklet, obvs.)
