### ISSUE TITLE
[css-typed-om] Behaviour of unsupported CSSStyleValues

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#553]
When you get an unsupported `CSSStyleValue`, does the spec have any requirements about its behaviour? I couldn't find any wording on this. I would think that at the minimum, we should be able to use them correctly in `StylePropertyMap`s.

```
const value = styleMap.get('filter');
otherStyleMap.set('filter', value);
```

**Comment by tabatkins** [comment]
What do you mean by "unsupported" here?

**Comment by darrnshn** [comment]
Sorry I mean the objects described [here](https://drafts.css-houdini.org/css-typed-om-1/#stylevalue-objects):
> Values that can’t yet be directly supported by a CSSStyleValue subclass are also represented as CSSStyleValue objects.

So like what we get if we did `CSSStyleValue.parse('filter', 'blur()')` as it can't be represented by a subclass of `CSSStyleValue` (for now).

**Comment by tabatkins** [comment]
Oh yeah, it's just not any more specific subclass. It's still a valid value that should be accepted back by that same property.

Yeah, we should be more detailed about this.

**Comment by tabatkins** [comment]
I think the gist should be, for forward-compatibility, that it should be treated like a (property, value) tuple, and only be valid in that exact property. (You can manually stringify it to get the value out if you want to use it in another property.)

That preserves positive functionality in the future when it does become a subclass - it won't stop working anywhere it previously worked. (But it might start working in other places, potentially.)
