### ISSUE TITLE
[css-typed-om] Is CSSKeywordish used anywhere?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#561]
The spec gives a definition of [CSSKeywordish](https://drafts.css-houdini.org/css-typed-om-1/#typedefdef-csskeywordish), but it doesn't seem to be used anywhere. Perhaps it was only used by the font stuff which later got removed? Should we still keep this?

**Comment by tabatkins** [comment]
It'll be useful as we add more things that care about keywords. We have relatively few CSSValue subclasses right now, and none of them take keywords yet, but there will be some in the future.  (In particular, the color classes will use keywords.)
