### ISSUE TITLE
[css-typed-om] algorithm for coercing value should specify parseMultiple flag

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#567]
The spec describes an [algorithm that coerces value into an appropriate type for a given property](https://drafts.css-houdini.org/css-typed-om-1/#algorithm-that-coerces-value-into-an-appropriate-type-for-a-given-property).

It says:

> Parse a CSSStyleValue with property property and value value and return the resulting value.

I think it should also say that the parseMultiple flag should be true.  And it should describe the value as a cssText, so I think it should instead say something more like:

> Parse a CSSStyleValue with property property, cssText value, and parseMultiple true, and return the resulting value.

**Comment by tabatkins** [comment]
Fixed.
