### ISSUE TITLE
[css-typed-om] "delete a StylePropertyMap" algorithm is poorly named

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#570]
The spec defines a [delete a `StylePropertyMap`](https://drafts.css-houdini.org/css-typed-om-1/#delete-a-stylepropertymap) algorithm.  But this is really about deleting a property *from* a `StylePropertyMap`.  Perhaps it should be called "delete from a `StylePropertyMap`"?

**Comment by darrnshn** [comment]
Yes, that should be "delete a value from StylePropertyMap" (consistent with "set a value" and "get a value").

**Comment by darrnshn** [comment]
Fixed in #583
