### ISSUE TITLE
[css-typed-om] "get all values from a StylePropertyMap" assumes underlying model might not be list

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#571]
Typed OM defines an [algorithm to get all values from a `StylePropertyMap`](https://drafts.css-houdini.org/css-typed-om-1/#get-all-values-from-a-stylepropertymap).  This says:

> 3. If StylePropertyMap’s property model contains an entry for property:
>
>     1. If property is a list-valued property, return the list of values assigned to that property.
>
>     2. If property is not a list-valued property, let values initially be the empty list and append the value assigned to the property to this list and return values.

However, earlier the spec [says](https://drafts.css-houdini.org/css-typed-om-1/#the-stylepropertymap):

> A StylePropertyMapReadOnly object has an associated property model, which is a list of property - sequence&lt;CSSStyleValue> pairs.

Given this, it's not clear why this distinction between list-valued and non-list-valued properties needs to be made; they're all represented as `sequence<CSSStyleValue>`.

**Comment by darrnshn** [comment]
Fixed in #592

**Comment by dbaron** [comment]
The fix looks OK (modulo the missing comma), but the text appears to be completely gone from the spec just a few days later... I guess it's been turned into the [definition of `getAll`](https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymapreadonly-getall).
