### ISSUE TITLE
[css-typed-om] the style map on a CSSStyleRule shouldn't be called attributeStyleMap

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#572]
The current specification [says](https://drafts.css-houdini.org/css-typed-om-1/#declared-stylepropertymap-objects) that the style map on a style rule is accessed via the property `attributeStyleMap`.  This doesn't make much sense.  The name `attributeStyleMap` makes sense on DOM elements (which is what the [relevant WG minutes where it was chosen](https://lists.w3.org/Archives/Public/www-style/2017May/0026.html) describe it on), but I don't think it makes sense on style rules.

I'd suggest that perhaps just `styleMap` would make sense for style rules, though I'd be open to other options.

**Comment by tabatkins** [comment]
Sounds good. Looks like the specific one for the style attribute is `ElementCSSInlineStyle`, so we'll move it to that.
