### ISSUE TITLE
[css-typed-om] What does lack of range restriction imply about serialization?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#574]
The [section on CSSNumericValue](https://drafts.css-houdini.org/css-typed-om-1/#numeric-objects) says:

> CSSNumericValue objects are not range-restricted. Any valid numeric value can be represented by a CSSNumericValue, and that value will not be clamped, rounded, or rejected when set on a declared StylePropertyMap or inline StylePropertyMap. Instead, clamping and/or rounding will occur during computation of style.

(It then proceeds to give an example demonstrating this.)

What this doesn't seem to address is what implications this has for CSS's existing object model APIs that involve serialization.  It's long been a principle of these APIs that they always give output that is valid CSS.  This means that, for example, getting `element.style.cssText`, modifying it, and setting it back to `element.style.cssText` should change only the thing that was modified.  Likewise for `getPropertyValue` and `setProperty`, or the `element.style.propertyName` that is equivalent to them.  However, the rules for these setters require following the rules of CSS parsing and dropping any declarations that are not valid.  This means that serializing things that don't round-trip correctly would break anything that depends on this round-tripping.

It seem like there are a bunch of bad options here (listed in the order that seems best to worst to me at first glance, although I'm sure I'm missing many considerations):
* serialize CSSUnitValue that are out-of-range as `calc()` expressions
* not do the thing quoted above, but instead do rejection of `CSSNumericValue`s when they're set in some cases
* serialize all CSSUnitValue as `calc()` expressions
* break round-tripping as the spec currently does

I tried to look through the spec to see if one of these options was specified later, but I didn't see anything.  If there is something I missed, it would be good to have a pointer to it from this section.

It's also entirely possible that the WG has discussed this and I've forgotten (or missed it).

**Comment by tabatkins** [comment]
We have not discussed this, but I think serializing out-of-range values as calc() makes the most sense.

**Comment by tabatkins** [comment]
(That said, I think this thus ends up being a CSSOM issue, not a TypedOM issue; this spec is the *source* of the bad values, which previously couldn't occur due to being rejected at parse time, but CSSOM is the source of the stringification.)

**Comment by dbaron** [comment]
(BTW, I think this is the most interesting of the issues I raised from a high-level or architectural perspective.)

**Comment by tabatkins** [comment]
It's definitely an interesting issue, but do you agree that it's a CSSOM issue?

(Serialization of actual TypedOM objects is defined completely independently of what property they appear in; it's only CSSOM that serializes values in the context of a property, where it's possible for them to be invalid.)

**Comment by dbaron** [comment]
I think which spec it's an issue on depends on which solution we end up with...

I think this is a substantive enough issue that it's probably worth bringing to the working group, although we might want some preparation in advance of that discussion.

**Comment by nainar** [comment]
@atanassov just making sure you know we want to add this to the agenda for the next APAC friendly CSSWG call as well

**Comment by alancutter** [comment]
I don't think wrapping in calc() solves all cases where a serialisation round trip would fail e.g. `z-index: calc(4.5)` would fail to parse.

It's not clear to me why we are avoiding rejecting TypedOM values that don't match what property spec text declares as valid numeric values.

**Comment by tabatkins** [comment]
> I don't think wrapping in calc() solves all cases where a serialisation round trip would fail e.g. z-index: calc(4.5) would fail to parse.

Ugh, I didn't think of type mismatches in the number/integer confusion.  I feel like we should probably just relax this in V&U, so that calc() always matches `<integer>` if it's a number, and you just round if necessary.  If `width: calc(-1px)` is fine, there's no reason `z-index: calc(1.5)` shouldn't be.

> It's not clear to me why we are avoiding rejecting TypedOM values that don't match what property spec text declares as valid numeric values.

Because it seems annoying/bad to force the author to keep track of precisely what numeric type their object is - if assigning a `CSS.px(-1)` to width is invalid, but `new CSSMathSum(CSS.px(-1))` is fine, that's weird. The distinction is reasonable in normal CSS, because you don't have an arbitrary object that may be a plain numeric or may be a calc; you're almost always directly writing the value in, so it's obvious which you have.

It's made worse by the fact that the math operations might return a simple type, or not - you can't tell by looking whether `val1.add(val2)` is going to return a CSSUnitValue or a CSSMathSum, as it depends on the types and contents of `val1` and `val2`.

**Comment by alancutter** [comment]
> If width: calc(-1px) is fine, there's no reason z-index: calc(1.5) shouldn't be.

SGTM.

> you can't tell by looking whether val1.add(val2) is going to return a CSSUnitValue or a CSSMathSum, as it depends on the types and contents of val1 and val2.

That's a nasty footgun, avoiding it SGTM. In animation code we've had the liberty of leaving rounding and clamping to the very end, it makes the actual numeric calculations much easier when you've got all of finite floating point space to do your work in.

**Comment by darrnshn** [comment]
Just to make sure I understand the resolution:

- Setting an out of range CSSUnitValue eagerly wraps it in a calc (e.g. `width: calc(-1px)`).
- Setting an <integer> property to a non-integral value eagerly wraps it in a calc (e.g. `z-index: calc(1.3)`)

**Comment by tabatkins** [comment]
Yes to the first. For the second, we first need to get the WG to accept that change in general, as it's not currently valid in CSS.  (Right now, `calc()` tracks whether it contains an integer or something that might be non-integral, and grammars can check against that.)

**Comment by tabatkins** [comment]
I just filed <https://github.com/w3c/csswg-drafts/issues/2337> to track this.

**Comment by darrnshn** [comment]
`CSSUnitValue.value` is currently a double, so how do we determine if that value is integral or not? Is there some standard way defined by the CSS spec that takes into account rounding corner cases etc.?

**Comment by tabatkins** [comment]
If we didn't have the desired behavior, and *did* have to track integral-ness, I expect we'd just use JS's normal semantics - it's an integer if the fraction part is 0. ^_^

**Comment by darrnshn** [comment]
Wait I think I'm understanding something wrong. From your reply, it sounds like to follow the spec, we don't have to check if a double is an integer? But I thought we need to because:

```
styleMap.set('z-index', CSS.number(3.001)) // wrap in calc or not
```

But yeah, I'll use whatever javascript uses if we need to check :)

**Comment by dbaron** [comment]
Just noticed this is still open in the context of w3ctag/design-reviews#223, though I'm not as worried about it as about the other open issue.

**Comment by tabatkins** [comment]
Ah, we can close this now, as the issue on calc() has been solved to my satisfaction - calc() no longer tracks `<integer>` as a type, it just uses `<number>` but will round to an integer when necessary.
