### ISSUE TITLE
[css-typed-om] rule on inferring <length-percentage> is too vague

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#581]
The section on [Numeric Value Typing](https://drafts.css-houdini.org/css-typed-om-1/#numeric-typing) says:

> Many specifications use ''[ &lt;length> | &lt;percentage> ]'' instead of ''&lt;length-percentage>'' in their grammar, and specify in prose that the &lt;length> and &lt;percentage> can be combined. For the purposes of matching, these cases should be treated as &lt;length-percentage>. Similarly for &lt;angle-percentage>, etc.

This doesn't seem clear enough to me to lead to interoperable implementations, since it doesn't make it clear what "specify in proces that ... can be combined" really means.  For example, for `line-height` I would think that &lt;length> and &lt;percentage> can be combined, but depending on what your definition of combined is, maybe &lt;number> and &lt;percentage> can't (since they're more semantically different).

I think this needs to be specified more clearly if it's going to lead to interoperability.  It might need to do that by listing the set of "old" grammar definitions to be patched, and requiring that future grammars get it right.

**Comment by tabatkins** [comment]
`<number>` can't ever be combined with the other units; we resolved that a while ago because it makes unit algebra intractable.

You're right that it's somewhat vague right now, but it's exactly as vague in plain CSS, as the equivalent of that passage is whether `calc(length + percentage)` works in the property.

**Comment by darrnshn** [comment]
Is it okay to close this one?

**Comment by tabatkins** [comment]
I think so; this needs to be addressed in CSS specs, because it's a general CSS issue right now.
