### ISSUE TITLE
[css-typed-om] what's a "list-valued property"?

### ISSUE THREAD

**Issue by gsnedders** [w3c/css-houdini-drafts#582]
This term appears throughout CSS Typed OM, but doesn't seem to be defined in any CSS WG draft.

**Comment by gsnedders** [comment]
We seem to use "mutli-valued property" in other WG drafts, but I still can't find any definition. Yay! :/

**Comment by tabatkins** [comment]
I added an explanatory paragraph in 05b03fc, with an issue to add an appendix explicitly listing which properties are what.  Unsure if that list belongs in this spec or somewhere else (maybe it needs to be a propdef entry?).

**Comment by gsnedders** [comment]
Do we actually need an explicit listing of properties? Can we not just say any property whose value is like [x]? (I'm not quite sure what x to suggest here, but it seems like there should be something.)

**Comment by tabatkins** [comment]
It's *generally* "properties that have a top-level <foo>#", but there are some complexities: counter-reset/increment don't comma-separate (ughhhhhh); 'background' has a special syntax for the final layer, allowing a color; 'animation' allows a lone "none", representing an empty list, as well as a list of animations.
