### ISSUE TITLE
[css-typed-om] "Create a CSSUnitValue from a string" invents its own CSS parsing

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#600]
The definition of [create a CSSUnitValue from a string](https://drafts.css-houdini.org/css-typed-om-1/#create-a-cssunitvalue-from-a-string) says:

>  To create a CSSUnitValue from a string str, return a new CSSUnitValue object with its value internal slot set to the numeric portion of str parsed into a number, and its unit internal slot set to the unit portion of str, or "number" or "percent" if str is a plain number or percent. 

This seems to be inventing its own CSS parsing, and does it in a rather vague way (for example, what's a "numeric portion" -- does it support scientific notation?).  It seems like it would be better to depend on the way CSS already parses dimensions.

**Comment by tabatkins** [comment]
That's solely an internal algorithm, used to make it much more convenient to create numeric values inline in an algorithm. (Currently only used in one place, but I expect it will see more use as we make more of them.)

**Comment by nainar** [comment]
Yes, I think it would easier to have the following two ways of constructing CSSUnitValues:

- double value, string unit
- string value, string unit
