### ISSUE TITLE
[css-typed-om] Should CSSTransformComponent have a toMatrix()?

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#609]
Reading the definition of [CSSTransformValue.toMatrix()](https://drafts.css-houdini.org/css-typed-om-1/#dom-csstransformvalue-tomatrix) made me wonder if [CSSTransformComponent](https://drafts.css-houdini.org/css-typed-om-1/#csstransformcomponent) should also have a `toMatrix()` that works the same way.  It seems like it would make sense.

**Comment by darrnshn** [comment]
I think it's a good idea; it would be equivalent to `new CSSTransformValue([component]).toMatrix()`, so there shouldn't be any problems.

**Comment by tabatkins** [comment]
Yeah, makes sense.
