### ISSUE TITLE
[css-typed-om] Add pseudoElt argument to computedStyleMap(), or wait for PseudoElement interface?

### ISSUE THREAD

**Issue by tabatkins** [w3c/css-houdini-drafts#620]
I'm adding a pseudoElt argument to the Element.computedStyleMap() method right now, but @darrnshn suggests that we intended to wait for the PseudoElement interface to become real and sprout .cSM() on its own.

Which should we do?

**Comment by darrnshn** [comment]
Relevant discussion: https://github.com/w3c/css-houdini-drafts/issues/350#issuecomment-294690156

**Comment by tabatkins** [comment]
Welp, that answers that - we agreed to do the PseudoElement interface.  I'll add a note to that effect to the draft.
