### ISSUE TITLE
CSSPositionValue definition should state rules for mapping syntax to objects

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#625]
The [definition of `CSSPositionValue`](https://drafts.css-houdini.org/css-typed-om-1/#positionvalue-objects) gives a nice example for a reasonable behavior:

> &lt;position> values accept a complicated combination of keywords and values, but in the Typed OM are always simplified to just two offsets. For example, the following style sheet: 

However, it doesn't actually specify that behavior.  The rules for this simplification should be specified.

**Comment by darrnshn** [comment]
Yup, I think we should link to the [CSSPositionValue normalization section](https://drafts.css-houdini.org/css-typed-om-1/#positionvalue-normalization), which specifies these rules explicitly I believe?
