### ISSUE TITLE
[css-properties-values-api] Calls to registerProperty() and unregisterProperty() should not trigger a CSS reparse

### ISSUE THREAD

**Issue by astearns** [w3c/css-houdini-drafts#63]

**Comment by astearns** [comment]
shane: File bug, calls to registerProperty, should not reparse, as would change identity of CSSOM objects.

**Comment by shans** [comment]
Instead just need to reparse specified values of newly registered properties then recompute style.

Sadly this implies that the token streams of all custom properties must be kept around to correctly deal with unregisterProperty then registerProperty w. different type on the same custom property.

**Comment by shans** [comment]
There's prose in the specification now for this but I think it could be written up more clearly. In particular:
1. can I just use the phrase 'invalidation of computed style'?
2. how do I reference the set of documents created by the window that registerProperty is called on (via the CSS interface)?

**Comment by shans** [comment]
@tabatkins thoughts?

**Comment by shans** [comment]
Want to invoke whatever happens when you change style rules through the CSSOM.

--foo: red;
--foo: url('donkey'); 
color: var(--foo);

if we call:
registerProperty({
  name: "--foo",
  syntax: "<'color'>"
});

then color is red.
