### ISSUE TITLE
[css-typed-om] CSSURLImageValue constructor probably shouldn't require "url()" around the URL

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#630]
As specified today, the [`CSSURLImageValue` constructor] seems to require that `url()` be around the URL in the string passed to it, since it depends on the `<url>` production.

I suspect it shouldn't require `url()`... but if that was the intent, an example should be given.

The spec should also specify more clearly how the parameter is processed, for example, whether CSS character escapes are processed.

**Comment by tabatkins** [comment]
I went ahead and matched our resolutions for other constructors, and just took the raw value passed in. No parsing goes on at all.
