### ISSUE TITLE
[css-typed-om] CSSURLImageValue url setter should be specified

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#631]
The setter and getter for the `url` attribute of [`CSSURLImageValue`](https://drafts.css-houdini.org/css-typed-om-1/#cssurlimagevalue) should be specified.  The description of the setter should address the same issues as #630.

**Comment by darrnshn** [comment]
`CSSURLImageValue.url` is `readonly`, so I think we only need to add a description for the `getter`?

**Comment by dbaron** [comment]
Er, I guess `url` is currently `readonly`... but why should it be `readonly`?

**Comment by dbaron** [comment]
(Being `readonly` seems inconsistent with the rest of the typed OM value classes.)

**Comment by darrnshn** [comment]
Sorry, I'm not really sure :/ Paging @tabatkins .

**Comment by tabatkins** [comment]
Unsure too, this part was written by Shane and I haven't given it a serious look since.  I'll check this out.
