### ISSUE TITLE
[css-typed-om] Significance of maplike in StylePropertyMap

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#642]
StylePropertyMap has recently been changed to map-like. I was wondering what the impact of this is on the implementation?

**Comment by nainar** [comment]
I think there is no implementation change for Blink here. We implement following the idl for maplike defined here: https://heycam.github.io/webidl/#idl-maplike.

**Comment by darrnshn** [comment]
Looks like we aren't using maplike anymore.
