### ISSUE TITLE
[css-typed-om] Shorthands in StylePropertyMap

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#643]
This issue to track what needs to be done about shorthands. According to [this discussion](https://github.com/w3c/css-houdini-drafts/issues/181), we definitely need to support shorthands in some way, although it looks like the original discussion resolved on representing them as raw `CSSStyleValue`s for now.

**Comment by darrnshn** [comment]
Representing shorthands as raw `CSSStyleValue` might be problematic for compatibility. Suppose I have code like this (back when `text-decoration` was a longhand):
```
let textDecor = styleMap.get('text-decoration'); // CSSKeywordValue
console.log(textDecor.value); // "underline"
```

When `text-decoration` becomes a shorthand, this code would no longer work:
```
let textDecor = styleMap.get('text-decoration'); // CSSStyleValue
console.log(textDecor.value); // error
```

I think treating shorthands like list-valued properties might avoid this (calling `.get` will return `text-decoration` when it was a longhand, and `text-decoration-line` when it became a shorthand).

**Comment by darrnshn** [comment]
@tabatkins what would be the intended behaviour here for shorthands? Maybe I can start implementing this before the spec text is written.

**Comment by tabatkins** [comment]
> Representing shorthands as raw CSSStyleValue might be problematic for compatibility. 
[snip]

Yeah, I'm talking about *right now*. In the future shorthands will be typed just as strongly as anything else.

(The compat issue you point out is there no matter what - single-keyword properties upgrading into more complicated values later, whether we turn it into a shorthand or not, isn't well-handled at the moment.  I need to (quickly) give this more thought, as Anne's old draft did handle this fairly well.)
