### ISSUE TITLE
[css-typed-om] Question about computed values

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#648]
Hi @tabatkins, just want to make sure I understand:

1. `computedStyleMap()` returns *computed values*, which may be different to the *resolved values* of `getComputedStyle()`
2. Currently, there's nothing that exposes computed values for every property.
3. Which spec should `computedStyleMap()` follow? For example, [margin-top has 4 specs](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top) with different computed values, which do I use?

**Comment by tabatkins** [comment]
> computedStyleMap() returns computed values, which may be different to the resolved values of getComputedStyle()

Yes.

> Currently, there's nothing that exposes computed values for every property.

Yes.

> Which spec should computedStyleMap() follow? For example, margin-top has 4 specs with different computed values, which do I use?

The imaginary hypothetical versions of each spec that @fantasai and I have given a thoro definition of each specified and computed value in terms of abstract data structures, instead of hand-waving. ://///////

**Comment by darrnshn** [comment]
Thanks for the clarification!
