### ISSUE TITLE
[css-typed-om-1]The IDL for StylePropertyMap is not valid due to multiple maplike declarations

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#649]
https://heycam.github.io/webidl/#idl-maplike clearly says:

> The inherited interfaces of a maplike interface must not also have a maplike declaration. 

but that's precisely what StylePropertyMap is doing: inheriting from another interface with a maplike declaration.

The reason for this restriction is that a maplike declaration induces the existence of a  [[BackingMap]] internal slot on instances.  When there are multiple maplike declarations it's undefined whether there are multiple internal slots or whether they interact with the same internal slot or something else.

**Comment by tabatkins** [comment]
(Moot now that I'm not using `maplike<>`, but...)

Hm, I was specifically using `readonly maplike<>` on the (readonly) superclass on `maplike<>` on the (readwrite) subclass; I figured that was how it was supposed to be done, from the similar examples elsewhere in WebIDL.
