### ISSUE TITLE
[css-typed-om-1]The IDL for StylePropertyMapReadOnly has an invalid "get" method

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#650]
https://drafts.css-houdini.org/css-typed-om-1/#stylepropertymapreadonly has both a maplike declaration and a "get" method.  WebIDL clearly says:

> Maplike interfaces must not have any interface members named "entries", "forEach", "get", "has", "keys", "size", or "values" ....

**Comment by darrnshn** [comment]
Looks like we're not using maplikes anymore
