### ISSUE TITLE
 [css-typed-om-1]The IDL for StylePropertyMapReadOnly has an invalid "has" method

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#651]
https://drafts.css-houdini.org/css-typed-om-1/#stylepropertymapreadonly has both a maplike declaration and a "has" method. WebIDL clearly says:

> Maplike interfaces must not have any interface members named "entries", "forEach", "get", "has", "keys", "size", or "values" ....

**Comment by tabatkins** [comment]
Yes, raised in <https://github.com/heycam/webidl/issues/514>.  The other multimap-like interfaces on the web platform today do this by instead just being `iterable<>` and then *manually* defining all of the Map methods, solely so they can override .get().

(I don't understand why .get() isn't overridable but .set() is in the first place.)

**Comment by bzbarsky** [comment]
`set` is overridable so that if you have an internal backing store mirroring the canonical [[BackingMap]] you can update it as needed.  There's no need for that in `get`, which can just read the [[BackingMap]].

**Comment by tabatkins** [comment]
Unless I have an internal backing store mirroring the canonical one, and want a different behavior. ^_^

**Comment by domenic** [comment]
The correct fix here is indeed to manually define the map methods. I understand you'd like Web IDL to do more work for you, but it doesn't yet, so in the meantime, for this spec to be implementable, it'd be best to follow the same pattern as the rest of the platform.

**Comment by tabatkins** [comment]
That's absolutely not the correct fix, as it means this interface (and the other Multimaps using this pattern) will require manual updating if/when ES grows more Map methods (which it looks like it will, from recent TC39 rumblings).

But given the *other* problems with maplike for my use-case, I have indeed switched it to an iterator<> that manually apes a Map.
