### ISSUE TITLE
[css-typed-om-1]Likely typo in prose for StylePropertyMapReadOnly

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#653]
https://drafts.css-houdini.org/css-typed-om-1/#stylepropertymapreadonly-map-entries says:

> This list is initialized differently depending on where the CSSStyleValue is used

but I suspect it means "depending on where the StylePropertyMapReadOnly is used"?

**Comment by tabatkins** [comment]
Yup, thanks.
