### ISSUE TITLE
[css-typed-om-1]"contains" link in "delete" section is broken

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#654]
In https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-delete step 3, "contains" links to https://fetch.spec.whatwg.org/#header-list-contains which is unlikely to be the right concept.

Presumably it means https://infra.spec.whatwg.org/#map-exists given that it thinks it's working with an infra map.

**Comment by tabatkins** [comment]
Ah, thanks, that had a plain `[=contains=]`, rather than `[=map/contains=]`. Curious that it wasn't flagged as a linking ambiguity by Bikeshed, I'll have to investigate that.
