### ISSUE TITLE
[css-typed-om-1]update() behaves a bit oddly for non-single-valued properties

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#656]
https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-update-property-updatefn is defined to do a get(), then pass the single CSSStyleValue to the given function, then do a set().

For a non-single-valued property this would lose all but the first item in the list if an identity UpdateFunction is used.  This seems like slightly odd behavior.

**Comment by darrnshn** [comment]
Maybe adding `styleMap.updateAll` (#645) will provide a more intuitive alternative?

**Comment by tabatkins** [comment]
I'm thinking we should just remove `update()` for now entirely, actually. The value it provides is relatively minimal for the oddness it causes with list-valued things, and I don't want to squat on this name if ES ends up using it.

**Comment by darrnshn** [comment]
I would be okay with that 👍(performance-wise, `.update` doesn't add much to just doing `.get/.set`).

**Comment by nainar** [comment]
Claiming to remove update() \o/
