### ISSUE TITLE
[css-typed-om-1]has() behavior for StylePropertyMap undefined

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#657]
https://github.com/w3c/css-houdini-drafts/issues/148 claimed to fix it, but I don't see it defined.

https://github.com/w3c/css-houdini-drafts/pull/442 claims to be merged, but that text is not present anywhere in the spec as of today.

**Comment by tabatkins** [comment]
Defined now <https://drafts.css-houdini.org/css-typed-om/#dom-stylepropertymapreadonly-has>, thanks.

(It might have gotten removed in favor of the default implementation that WebIDL provides? Can't use that anymore, of course.)
