### ISSUE TITLE
[css-typed-om-1] Exposed value for partial interface Element makes no sense and is not valid Web IDL

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#658]
https://drafts.css-houdini.org/css-typed-om-1/#computed-stylepropertymapreadonly-objects says:

    [Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
    partial interface Element

This is nonsensical (because Element is only exposed in Window), and it's invalid Web IDL, because it's nonsensical.  Specifically, https://heycam.github.io/webidl/#Exposed says:

> If [Exposed] appears on a partial interface or partial namespace, then the partial’s own exposure set must be a subset of the exposure set of the partial’s original interface or namespace.

Does Blink's IDL parser not even pretend to implement this stuff?  :(

**Comment by bzbarsky** [comment]
The partial interface CSSStyleRule and partial interface ElementCSSInlineStyle Exposed values have the same issue.

**Comment by tabatkins** [comment]
Ah, I spammed the [Exposed] a little too aggressively. Removed from all three of the partial interfaces.

**Comment by bzbarsky** [comment]
> Does Blink's IDL parser not even pretend to implement this stuff? :(

Ah, the IDL in the blink tree just looked nothing like what's in the spec.  Awesome.

**Comment by bzbarsky** [comment]
Probably need to update the web platform tests too.  And maybe we need an idlharness bug if it parsed this.  :(

**Comment by tabatkins** [comment]
> Ah, the IDL in the blink tree just looked nothing like what's in the spec. Awesome.

That's because it was a very recent change, from the end of January.
