### ISSUE TITLE
[css-typed-om-1] Behavior of indexed setter on CSSUnparsedValue is not defined.

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#663]
Per https://heycam.github.io/webidl/#idl-indexed-properties 

>  If the operation used to declare the indexed property setter did not have an identifier, then the interface definition must be accompanied by a description of how to set the value of an existing indexed property and how to set the value of a new indexed property for a given property index and value.

but there's nothing like this in the Typed OM draft.

The getter behavior is not really defined either (because there is no decription for how to "determine the value of an indexed property"), but it can at least be guessed at.

**Comment by darrnshn** [comment]
Yeah I'm not quite sure how to phrase it correctly. I'm guessing it should somehow reference the `[[tokens]]` internal slot?

**Comment by bzbarsky** [comment]
Something along those lines seems reasonable...
