### ISSUE TITLE
[css-typed-om-1] Duplicating a CSSVariableReferenceValue is harder than it probably should be

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#665]
Say I have a https://drafts.css-houdini.org/css-typed-om-1/#cssvariablereferencevalue and I want to create a "copy" of it.  How do I do that?

    new CSSVariableReferenceValue(myValue)

throws.

    new CSSVariableReferenceValue(myValue.variable, myValue.fallback)

throws if I have no fallback.

    new CSSVariableReferenceValue(myValue.variable, myValue.fallback || undefined)

works, but who would think of doing that?  ;)

Ideally there would be a constructor taking CSSVariableReferenceValue.

In addition to that, the second (optional) ctor arg should perhaps be nullable and default to null....

**Comment by darrnshn** [comment]
Do we need similar clone methods for other subclasses for consistency?

**Comment by bzbarsky** [comment]
I don't know.  Do you expect people to clone these things?

This one just jumped out at me because extracting information from a CSSVariableReferenceValue that can be used to construct another CSSVariableReferenceValue was nontrivial.

**Comment by darrnshn** [comment]
Yeah `CSSVariableReferenceValue` is a nontrivial one. I think the transforms also might be hard to clone because of `is2D` subtleties. That being said, I don't expect people to clone these things, since performant Typed OM code should reuse objects as much as possible.

**Comment by tabatkins** [comment]
For now, I at least fixed it so that the fallback argument was nullable, so you can just spam the two fields into the constructor and get something equivalent.  Adding constructors for everything that take an existing instance and duplicate it is probably something good to do as well, but I'll defer it for now.

**Comment by bzbarsky** [comment]
> For now, I at least fixed it so that the fallback argument was nullable,

Why not make null the default value too, then, to make the algorithm simpler?

**Comment by tabatkins** [comment]
Yeah, makes sense.
