### ISSUE TITLE
[css-typed-om-1] CSSVariableReferenceValue's "variable" getter needs to be defined.

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#667]
Presumably it returns the "variable" internal slot's value?

**Comment by darrnshn** [comment]
I'm guessing you meant CSSVariableReferenceValue?

**Comment by bzbarsky** [comment]
Er, yes, I do.  They're kinda lumped together in a way that confused me.  ;(

**Comment by tabatkins** [comment]
Fixed in #676.

(I left it out on the assumption that, if undefined, it just does the normal thing.  Specs generally leave off *both* getters and setters for attributes that just reflect the internal slot.)
