### ISSUE TITLE
[css-typed-om-1] rectify a keywordish value allows creation of empty-string CSSKeywordValues

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#668]
https://drafts.css-houdini.org/css-typed-om-1/#rectify-a-keywordish-value doesn't call the constructor of CSSKeywordValue, so bypasses the empty-string check that constructor does.

**Comment by nainar** [comment]
Fixed by #686

**Comment by tabatkins** [comment]
And now moot, since #686 was merged.
