### ISSUE TITLE
[css-typed-om-1] rectify a keywordish value doesn't define the global it creates the CSSKeywordValue in

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#669]
https://drafts.css-houdini.org/css-typed-om-1/#rectify-a-keywordish-value

IDL objects have associated globals.  Constructors set up the association automatically, but we're not calling a constructor here, just creating a CSSKeywordValue from thin air.  What is its global?

This is observable in JS, in general, via the prototype chain.

**Comment by tabatkins** [comment]
I didn't even realize that constructors had the magic association logic. I'll switch to calling the constructor, I guess.

**Comment by bzbarsky** [comment]
Note that calling the constructor is only magic insofar as the constructor knows which global it came from and just associates the new thing with that global.  Which means that from your point of view you still have to specify which global's constructor gets called.

**Comment by tabatkins** [comment]
Sigh. At least it has an obvious answer in every single case - it's the global that the calling method is associated with.

**Comment by bzbarsky** [comment]
The calling method, or the calling method's this object?

**Comment by tabatkins** [comment]
:(

**Comment by tabatkins** [comment]
Looks like the answer is "the calling method's this object", per [HTML's guidance](https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects).

**Comment by bzbarsky** [comment]
The relevant global generally makes sense, right.  I just haven't gotten far enough into this spec yet to see how these bits are used in practice.

**Comment by darrnshn** [comment]
On a side note, I don't think there's any use for `CSSKeywordish` in the level 1 spec (as `ColorValue` has been moved to level 2). We should just probably delete it?

**Comment by tabatkins** [comment]
Yeah, I'm fine with killing it for now.
