### ISSUE TITLE
 [css-typed-om-1]Probably need to define the order of multiplications in mul() step 3 and step 4

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#678]
https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-mul step 3 multiplies together a bunch of floating-point numbers.  Multiplication on floating-point numbers is not associative, so the answer depends on how you do it, exactly.  Ideally this would be specified.

**Comment by bzbarsky** [comment]
Same thing for step 4 of mul.

**Comment by tabatkins** [comment]
Fixed.
