### ISSUE TITLE
[css-typed-om-1] "equal numeric values" may return false when people might expect true

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#682]
Consider the output of https://drafts.css-houdini.org/css-typed-om-1/#equal-numeric-value on these two values:

    CSSMathNegate(CSSMathSum(2px, 1em))
    CSSMathSum(-2px, -1em)

I believe you can produce those data structures, and that this algorithm will return false in this case, right?

I'm not sure I have a nice suggestion here, by the way; solving this in general is not trivial.

**Comment by darrnshn** [comment]
Yeah it will currently return false. There are many definitions of "equal" that we can go with here (some easy, some intractable). I think we should just pick one that's not too opinionated and allow the user to define fancier equalities as they desire by traversing the tree.

Some ideas:
1. Structural equality where order matters (i.e. `CSSMathSum(1px, 2px) != CSSMathSum(2px, 1px)`).
2. Structural equality where order doesn't matter (i.e. `CSSMathSum(1px, 2px) == CSSMathSum(2px, 1ps)`).
3. Structural equality after "simplification" (i.e. your example will return true).

IMHO 3 is difficult to get right. I'm ok with either 1 or 2. Can we take inspiration from another spec or maybe JavaScript itself?

**Comment by bzbarsky** [comment]
Fwiw, I agree that 3 is difficult to get right.  Right now I think the spec is aiming for 2.

**Comment by tabatkins** [comment]
Closing because the spec now clearly specifies 1.

**Comment by annevk** [comment]
I think it would help if you add an example of things seeming equal not being equal.

**Comment by annevk** [comment]
Thanks!
