### ISSUE TITLE
[css-typed-om] Unsupported color values

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#689]
As we have moved `ColorValue` to level 2, what should we return for values like `red` on properties like `color`? My intuition says that returning everything color related (including keywords) as an opaque `CSSStyleValue` (i.e. not `CSSKeywordValue`) in case it's something we'll regret when we actually spec `ColorValue`?

**Comment by tabatkins** [comment]
The plan was to represent `currentcolor` as a `CSSKeywordValue` and all the rest as `CSSColorValue` subclasses, so we should do the same here - `currentcolor` is a CSSKeywordValue, while the rest are `CSSStyleValue`.

**Comment by darrnshn** [comment]
Cool, thanks!
