### ISSUE TITLE
[css-typed-om] Unclear how parse a CSSStyleValue returns CSSStyleValue objects

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#695]
Where do these objects get allocated?

**Comment by tabatkins** [comment]
That's given by the "normalizing" link, which links down to the chapter on how to turn an abstract CSS value into a `CSSStyleValue` object.

(There's the larger issue pervading a bunch of this about what context to use, but I'll fix all that at once.)

**Comment by annevk** [comment]
Yeah, it seems that needs at least one more argument as to where to find the constructor.

**Comment by tabatkins** [comment]
Just to make sure, you're just agreeing with the last sentence of my previous comment, yes?

**Comment by annevk** [comment]
Yup!
