### ISSUE TITLE
[css-typed-om]  CSSStyleValue normalization

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#697]
> If a property’s grammar is more complex than one of the types listed here, it normalizes to a raw CSSStyleValue

Normalizes above links to https://drafts.css-houdini.org/css-typed-om/#cssmath-normalize-a-math-expression which doesn't really make this sentence any clearer.

**Comment by tabatkins** [comment]
I switched the term for "turn a CSS value into a CSSStyleValue object" to "reify", so it is (a) more correct and (b) won't overlap with some of my "normalization" terms, so this is fixed now.
