### ISSUE TITLE
[css-typed-om] If parseMultiple is true, but property is a single-valued property

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#699]
Any reason not to s/, but/ and/?

**Comment by tabatkins** [comment]
Not 100% sure why I added that step in the first place; there's nothing wrong with calling `parseAll('color', ...)` and getting back an array with a single value. (We don't throw if you ask for `.getAll('color')`, after all, we just return an array with a single value.)

So I just removed it, making this issue moot. ^_^
