### ISSUE TITLE
[css-typed-om] Setting list-valued properties to var() refs.

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#707]
What should something like (pseudo syntax): `styleMap.set('transition-duration', new CSSUnparsedValue([--A]), CSS.s(1), '2s')` do? Would it be equivalent to `transition-duration: var(--A), 1s, 2s`? Are there any corner cases to deal with?

**Comment by darrnshn** [comment]
I guess it also depends on whether `transition-duration: var(--A), 1s, 2s` reifies as a single `CSSUnparsedValue` containing all three items, or three separate `CSSStyleValues`?

**Comment by tabatkins** [comment]
Hmm. With the caveat the evaluating the var() might change the number of items, I think that `var(--A), 1s, 2s` should reify to three CSSStyleValues; nothing the var() can evaluate to will change the fact that the property definitely *ends* with two more separate values.

So then passing in those values in your first example should work fine too.

**Comment by darrnshn** [comment]
Cool, cheers.

**Comment by darrnshn** [comment]
Hmm, after thinking about this a bit more and discussing with @alancutter, there are some weirdnesses (at least, for me) if we reify as separate CSSStyleValues.

- In CSSOM, I think you can set something to 'var(--A), bleh'. If you reify that, you probably get a `CSSUnparsedValue(CSSVariableReference('--A'))` and a `CSSKeywordValue('bleh')`. The latter is invalid for that property. I think this breaks roundtripping, but not sure if that's bad tho.
- If you do `styleMap.set(.., CSSUnparsedValue([--A, ',', --B]))`, does that `CSSUnparsedValue` get "parsed" and split into two smaller ones? And how do we make this consistent (if we want to) with `styleMap.set(..., "var(--A), var(--B)")`?
- CSSOM seems to accept stuff like `var(--A),,,,what`, but does that make sense to reify as separate items?

I'm not very familiar with custom properties, so there's probably a good answer for each of these cases. But I think it might be more intuitive / simpler if we reified as a single `CSSUnparsedValue`?

**Comment by tabatkins** [comment]
I can go either way on this. If we do reify it only as a single CSSUnparsedValue, then we need to reject at set-time if you try and set the property to contain a CSSUnparsedValue along with anything else.

But if we do stick with what I said before...

> In CSSOM, I think you can set something to var(--A), bleh. If you reify that, you probably get a CSSUnparsedValue(CSSVariableReference('--A')) and a CSSKeywordValue('bleh'). The latter is invalid for that property. I think this breaks roundtripping, but not sure if that's bad tho.

Yes, you can set a property to that in CSSOM.  I see your argument about it breaking round-tripping, as we'll throw an error when you try to set the CSSKeywordValue.

> If you do styleMap.set(.., CSSUnparsedValue([--A, ',', --B])), does that CSSUnparsedValue get "parsed" and split into two smaller ones? And how do we make this consistent (if we want to) with styleMap.set(..., "var(--A), var(--B)")?

I'd assume no. In your latter point, your call would be invalid; you can't just set a string directly, you need to parse it.

> CSSOM seems to accept stuff like var(--A),,,,what, but does that make sense to reify as separate items?

Yes, it's correct for CSSOM to accept that. And yeah, it's troubling to think about what we would reify it as.

---------

Okay, you've convinced me. Any var() makes the whole thing a CSSUnparsedValue, and I'll add some checks to set/append to make sure we don't violate that.

**Comment by tabatkins** [comment]
ecfcbf9 is the fix for this.
