### ISSUE TITLE
[css-typed-om] What do numeric font weights reify to?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#708]
`font-weight` accepts "numeric keywords" like 100, 200, 300 ... Initially I thought they'd reify as `CSSKeywordValue`s, but I heard that its being changed to accept `<<number>>`s? So should they reify as `CSSUnitValues`?

**Comment by tabatkins** [comment]
font-weight uses numbers, yeah. It always did, they just acted kinda like keywords. They absolutely wern't, tho - you'd have to type `\31 00` to get a keyword for "100", for example, and that's both not necessary and would be invalid in any implementation. ^_^

**Comment by darrnshn** [comment]
Cool, thanks!
