### ISSUE TITLE
Editorial: "initially be"

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#709]
Instead of

> Let s initially be the empty string.

you can write

> Let s be the empty string.

And instead of

> Let s initally be the string "var(".

You can write

> Let s be "var(".

as the quotation marks already signify it as a string per Infra.

**Comment by tabatkins** [comment]
While I'm not perfectly consistent about it, I use "initially be" to indicate that the binding is going to be mutated over the algorithm.

Point taken on the unnecessary type-naming for strings.

**Comment by annevk** [comment]
I think if you want that you should open an issue for it in Infra. Other specifications don't use that convention so I don't think it'll help implementers much as it's not consistently applied.
