### ISSUE TITLE
[css-typed-om] Reifying text-decoration-line

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#717]
[text-decoration-line](https://drafts.csswg.org/css-text-decor-3/#text-decoration-line-property) has a weird grammar where it can either take a single keyword ('none', 'spelling-error', 'grammar-error') or a list of keywords ('underline', 'overline', ...). Should this be:

1. Completely unsupported and reified to a new structure in L2?
2. Reify the single keywords and leave the list keywords to be reified in L2?
3. Reify as long as one keyword is passed in, more than one keyword will be reified in L2?
4. Other ideas?

**Comment by tabatkins** [comment]
I think we should reify as a CSSKeywordValue if it's a single keyword, and as a CSSStyleValue right now otherwise.  That's your option 3.
