### ISSUE TITLE
[css-typed-om]What actually happens when sets happen on a StylePropertyMap?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#719]
Let's consider a specific example.  Say I have:

    <body style="color: red">

and I do:

    document.body.attributeStyleMap.set("color", new CSSKeywordValue("green"));

After that, what does `document.body.getAttribute("style")` return?  What does `document.body.style.color` return?  Why?

The spec for https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-set says that the set happens in the `StylePropertyMap`, but says nothing about modifying the relevant `CSSStyleDeclaration` or anything else.  Should it?

**Comment by bzbarsky** [comment]
This is somewhat related to https://github.com/w3c/css-houdini-drafts/issues/718

**Comment by tabatkins** [comment]
Yes, it should - the StylePropertyMap is meant to be a portal into the underlying values, which the `style` attribute/property also reflects.  This is no well specified at the moment.

**Comment by tabatkins** [comment]
Okay, went and looked at how CSSOM does this, and realized it just directly says that the abstract "css declarations block" concept is reflected as a CSSStyleDeclaration in DOM, so I just did the same thing. The spec should now be at least as specific about this mechanism as CSSOM is!

(And, if I'm reading and understanding correctly, it gives us the style-attribute mutation and mutation-watching we want, for free.)
