### ISSUE TITLE
 [css-typed-om]What happens when things inside a StylePropertyMap are mutated in-place?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#720]
Let's consider a specific example. Say I have:

    <body style="color: red">

and I do:

    document.body.attributeStyleMap.get("color").value = "green";

After that, what does `document.body.getAttribute("style")` return? What does `document.body.style.color` return? Why?

https://drafts.css-houdini.org/css-typed-om-1/#dom-csskeywordvalue-value says to set the internal slot and that's it.

**Comment by tabatkins** [comment]
Nothing special happens, per the original intention and now new text, which clarifies that StylePropertyMaps are just a reflection of the abstract "CSS declarations block" concept, and they freshly reify their abstract values when you call .get()/getAll().

(To be specific, then, `document.body.getAttribute("style")` continues to return `color: red`, and `document.body.style.color` continues to return `red`.)
