### ISSUE TITLE
[css-typed-om] Why does `get` return by reference and `getAll` by value?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#721]
If you compare https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymapreadonly-get and https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymapreadonly-getall the former returns a reference to the internal value.  The latter returns a copied list of references to internal values.

Concretely, say you have a `background-size` property that's a list of `cover`/`contain` keywords.  If you want to change one of the keywords in the list, you can `getAll('background-size')[0].value = "contain"`.  But if you want to change the length of the list, you need to end up doing https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymap-set as far as I can tell, right?

**Comment by tabatkins** [comment]
It's not meant to be reference to the data at all. All the objects returned by get/getAll should be "dead" reified values; the only way to manipulate the underlying values is by calling .set() with what you want.

I definitely see what I'm doing wrong in the spec, tho. Will fix.

**Comment by tabatkins** [comment]
And done - I'm now just reusing the same text that CSSOM does, so that the [[declarations]] slot is the *abstract* "declarations" of a "CSS declarations block", and get()/getAll() properly reify the values before returning.
