### ISSUE TITLE
[css-typed-om]What is the expected behavior when CSSStyleValues in a readonly map are mutated?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#722]
Say I have this HTML:

    <body style="color: red">

and I do:

    var x = document.body.computedStyleMap();
    x.get("color").value = "green";

After this, what do the following return:

    x.get("color").value
    document.body.computedStyleMap().get("color").value
    document.body.style.color

?

**Comment by tabatkins** [comment]
StylePropertyMaps are live - they always reflect the underlying values in the CSS system.  So a mutation via some other method will be immediately reflected in what `.get()` returns.

(I'm writing this up in more detail as we speak - there are several moving parts I'm putting together at once.)

**Comment by bzbarsky** [comment]
> I'm writing this up in more detail as we speak 

Right, that's what this issue is about.  This all needs to actually be defined.

**Comment by tabatkins** [comment]
Defined now. Details in the other four issues you opened about this topic. ^_^
