### ISSUE TITLE
[css-typed-om] How does Typed OM interact with existing setters on CSSStyleDeclaration?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#723]
Say I have this HTML:

    <body style="color: red">

and I do:

    var x = document.body.attributeStyleMap;
    var y = x.get("color");
    document.body.style.color = "green"

After this, what does the following return:

    y === document.body.attributeStyleMap.get("color")

Presumably it's false?  But then what happens if instead I start with the same HTML and do:

    var x = document.body.attributeStyleMap;
    var y = x.get("color");
    var z = new CSSKeywordValue("green");
    x.set("color", z);

after this, modulo <https://github.com/w3c/css-houdini-drafts/issues/719>, is the thing in the map `z` or something else?  Presumably `z`, but to resolve https://github.com/w3c/css-houdini-drafts/issues/719 you need to update the underlying stuff like `document.body.style.color = "green"` ... except without changing the `StylePropertyMap` or something.

**Comment by bzbarsky** [comment]
Similarly, if I set `document.body.style.color = "green"`, what does that do to the object identity of the `CSSKeywordValue` returned by `get("color")` on an already-existing map gotten via `document.body.computedStyleMap().get("color")`?  So specifically:

    var x = document.body.computedStyleMap();
    var y = x.get("color");
    document.body.style.color = "green"

and now is `x.get("color") === y` true?

**Comment by tabatkins** [comment]
> After this, what does the following return:

Yes, it's false - you already grabbed `y` when 'color' was "red", so it's a `CSSKeywordValue("red")`. But style maps are live, so the second `get()` returns a `CSSKeywordValue("green")`.

> is the thing in the map z or something else?

The underlying value has been set to the keyword "green".  `z` itself isn't retained; if you called `.get('color')` again you'll get a fresh object reifying the keyword "green".

> but to resolve #719 you need to update the underlying stuff like document.body.style.color = "green" ... except without changing the StylePropertyMap or something.

I don't know what you mean by this. Why does the StylePropertyMap need to not be changed?

> and now is x.get("color") === y true?

No, every call to `get()` reifies a fresh object.

**Comment by bzbarsky** [comment]
> But style maps are live, so the second get() returns a CSSKeywordValue("green").

"style maps are live" is not really enough to pin down behavior here.  The question is whether setting .style.color creates a new CSSKeywordValue or mutates the existing one.

> z itself isn't retained

That's the part that needs to be specced somewhere.

> Why does the StylePropertyMap need to not be changed?

If I do `map.set("color", foo)`, shouldn't I then have `map.get("color") === foo`?

> No, every call to get() reifies a fresh object.

It does?  So if I do `map.get("color") === map.get("color")` I should get false?  That's not what the spec text at https://drafts.css-houdini.org/css-typed-om-1/#dom-stylepropertymapreadonly-get says.

**Comment by tabatkins** [comment]
Yeah, I realized that all of the issues you filed today are all due to the same spec mistake that I'm fixing now. ^_^

**Comment by bzbarsky** [comment]
@tabatkins What does Blink implement (and is planning to ship) here?

**Comment by tabatkins** [comment]
If you'll give me more than 8 minutes, I can finish writing the thing and show you!

**Comment by tabatkins** [comment]
And done.  Same as #721 - it's now clearer that the thing inside of a StylePropertyMap is a "CSS declarations block", same as CSSOM uses, and so mutations of the block, from any source, are reflected.

.get()/getAll() now properly reify the value upon calling, so you do indeed get fresh objects every time.
