### ISSUE TITLE
[css-typed-om] Moving cached computedStyleMap to another document

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#724]
Originally raised by rune@, what should happen to the cached computedStyleMap on an element if the element is moved to another document? Should it still be the same object?

**Comment by tabatkins** [comment]
Hm, there's nothing particularly Document-specific about it.  The only thing I can think of is that it's generated by a particular global's constructor, and thus won't test as the correct type when compared against another global's version of the constructor.  But that's also true of the element itself, so I don't think that's a big deal.

Unless there's a good code-complexity reason to swap it out for a fresh object, I think it should stay cached.

**Comment by darrnshn** [comment]
Cool thanks, I'll pass that on.
