### ISSUE TITLE
[css-typed-om] Canonical units in computed values

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#725]
If I have an element with `width: 1cm`, then does its computed value reify to `CSS.cm(1)` (which serializes to pixels)? In CSSOM, we only need to deal with canonical units because [serialization uses canonical units](https://www.w3.org/TR/css-values-3/#compat), but I think this doesn't apply to reified objects in Typed OM?

If this is the required behaviour, then AFAIK this is difficult to implement in Blink because we don't retain unit information in computed style. I don't know about the other browsers.

**Comment by tabatkins** [comment]
I have no particular opinion on this. I'm fine with saying that computed value process uses canonical units.

**Comment by upsuper** [comment]
I don't think Gecko preserves unit information for computed value either, so I also agree that it's probably better to use canonical units there.
