### ISSUE TITLE
[css-typed-om] Why do CSSStyleValues created from strings serialize to the string?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#728]
Originally raised by rune@. The spec says that:

```
if the value was constructed from a USVString
   the serialization is the USVString from which the value was constructed.
```

Is this really important? It is inconvenient to both implement and spec (due to the dirtying logic) and apparently other CSSOM APIs don't require inputs to be preserved?

**Comment by tabatkins** [comment]
In general, specified values are preserved exactly as written - if you say `el.style.color = "red"; console.log(el.style.color)`, authors expect to get back `red`, not `rgb(255, 0, 0)` or something like that.  This is intended to preserve that behavior.

I need to make the logic more explicit, tho, with a private slot holding a string or null, which is set to a string only if it's produced by a `.parse()` method or comes from a specified value.

**Comment by lilles** [comment]
So, if I read the spec correctly:

CSSStyleValue.parse("property", cssText); // serialize exactly as cssText input.

elm.attributeStyleMap.get("property"); // serialize as elm.style.property, even if it was set with the CSSValue parsed above.

new CSSUnitValue(31.0, "em"); // serializes as specified in https://drafts.css-houdini.org/css-typed-om-1/#stylevalue-serialization

**Comment by tabatkins** [comment]
Yes, that's exactly the behavior specified in <https://drafts.css-houdini.org/css-typed-om/#stylevalue-serialization>.
