### ISSUE TITLE
[css-paint-api] The paint() function should probably take a <custom-ident>

### ISSUE THREAD

**Issue by nox** [w3c/css-houdini-drafts#729]
https://drafts.css-houdini.org/css-paint-api/#paint-notation

This should probably say:

```
paint() = paint( <custom-ident>, <declaration-value>? )
```

https://drafts.csswg.org/css-values-4/#custom-idents

It doesn't matter much but I think it is good style anyway to not accept CSS-wide keywords anywhere just as to not confuse users.

**Comment by bfgeek** [comment]
-paging in memory-
@tabatkins & I talked about this at some stage. I think it was originally a `<custom-ident>` but we change it to an `<ident>` as there was no good reason why we shoudn't accept the css-wide keywords in a paint function.

But we'll quickly talk about this next week.

**Comment by tabatkins** [comment]
Yeah, there's no particular reason here to exclude someone from creating a paint function named "inherit" - it'll never show up directly in a property context, so it's never a parsing problem.
