### ISSUE TITLE
[css-typed-om] 'fr' units cannot be used in a calc

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#734]
It seems like you can't use ['fr' units in a calc](https://drafts.csswg.org/css-values-4/#calc-notation), but you can create a `CSSMathValue` containing `CSSUnitValues` with `fr` units. Is this going to change? If not, we should handle this case (maybe throw an exception when trying to create a `CSSMathValue` with `fr` units?)

**Comment by tabatkins** [comment]
I think that's accidental - we just made an explicit list of types at one point, and fr units were added *after* that point, and we never thought to add it.  I'm asking @fantasai for confirmation; if so, I'll just fix `calc()` to allow fr units.

**Comment by fantasai** [comment]
You spent a lot of effort arguing that the spec didn't allow `fr` units inside `calc()`, y'know. :) In any case it was resolved not to by the CSSWG in https://github.com/w3c/csswg-drafts/issues/955

**Comment by fantasai** [comment]
Minutes at https://lists.w3.org/Archives/Public/www-style/2017Mar/0060.html

**Comment by tabatkins** [comment]
No, I argued that fr couldn't be combined with `<length>`, which is still correct. But right now `calc(1fr / 7)` is disallowed, which seems like an inadvertant omission rather than a purposeful one.

**Comment by tabatkins** [comment]
Agenda+ to confirm that allowing 'fr' units in calc() (not combinable with anything, just on their own) is okay (and V&U should change as a result).

**Comment by tabatkins** [comment]
Whoops, <https://github.com/w3c/csswg-drafts/issues/2665> points out the `<resolution>` units aren't currently allowed in calc() either.  We should make that possible as well.

(Like `<flex>`, they'll just be usable by themselves. In particular, `<resolution>` values are *not* inverse `<length>`s.)
