### ISSUE TITLE
[worklets] What are the API-s exposed in Worklets?

### ISSUE THREAD

**Issue by gagyibenedek** [w3c/css-houdini-drafts#737]
Is there a list with all the API-s exposed in Worklets?
For example in the [Worklets Level 1 Draft](https://drafts.css-houdini.org/worklets/#workletglobalscope) or in the [PaintWorklet section](https://drafts.css-houdini.org/css-paint-api/#dom-css-paintworklet) there's no mention of Math, but in the examples some of its functions are used, and in the Chrome PaintWorklet implementation its also usable. Console also seems to be available without ever being mentioned in the draft.
Am I missing something?

**Comment by bfgeek** [comment]
It depends on the Worklet. Broadly speaking however:
 - All the JS Builtins. This includes Math.*, String.*, etc.
 - The registerSomething for that particular type of worklet.
 - The TypedOM.

This information isn't listed in the worklets, or paint specification, instead other specifications e.g. TypedOM (https://drafts.css-houdini.org/css-typed-om/#cssstylevalue) list Exposed=PaintWorklet to expose an API.

This *should* be listed in the MDN docs however when we get around to writing it.
https://developer.mozilla.org/en-US/docs/Web/API/Worklet

Was there something that you were looking for - but missing?

**Comment by gagyibenedek** [comment]
Thanks for the answer!
I saw some of the Exposed annotations, just wasn't sure if they were gathered somewhere. MDN makes perfect sense for that.

I wasn't looking for one given thing, just tried to find out more about what's possible and what's not with the Paint API. E.g. the fact, that it will get its own thread tempted me to check if some computation heavy canvas based modules can be moved to a worklet. Obviously this is not what they are intended for, but I considered it interesting enough to check.

**Comment by bfgeek** [comment]
No problem!

At the moment Chrome's implementation isn't on a separate thread, but we have work scheduled to do that later this year (starting around July).

Added heavy computation worklets are certainly fine!

File an issue here if you find an API you'd like, but don't have exposed to the paint worklet. Describing your use-case is super helpful - as there may be alternative solutions rather than exposing API Blah.

**Comment by gagyibenedek** [comment]
> Added heavy computation worklets are certainly fine!

Hm, so this is not considered a hack? That's really cool!

The first thing that comes to mind is requestAnimationFrame. I guess I'm not the first one to think about it, so I'll do my research, and will create an issue if  it makes sense.

**Comment by bfgeek** [comment]
Yup rAF isn't required as you can animation some property, e.g. --tick indefinitely. Note this may not get call every frame however, e.g. the element might be offscreen.

**Comment by bfgeek** [comment]
Re: expensive computation, its up to you to decide what your frame budget is :)
