### ISSUE TITLE
[css-paint-api] Running author function without proper preparation.

### ISSUE THREAD

**Issue by yuki3** [w3c/css-houdini-drafts#743]
In short, [invoke a paint callback](https://drafts.css-houdini.org/css-paint-api/#invoke-a-paint-callback) does not follow Web IDL nor HTML specs.  The CSS Painting API spec and its algorithms are defined using ECMAScript directly, and it violates Web IDL and HTML specs.

I cannot list up all the places that are conflicting with Web IDL and/or HTML, so let me show an example.

In [invoke a paint callback](https://drafts.css-houdini.org/css-paint-api/#invoke-a-paint-callback), step 5.3. "Let paintInstance be the result of Construct(paintCtor)."; this step invokes an author function |paintCtor| without performing [prepare to run script](https://html.spec.whatwg.org/multipage/webappapis.html#prepare-to-run-script) nor [prepare to run a callback](https://html.spec.whatwg.org/multipage/webappapis.html#prepare-to-run-a-callback).  This is NOT allowed in Web IDL nor HTML.  |paintCtor| will run without the Incumbent realm having been set up, so we cannot tell what would happen if |paintCtor| invoked an Web API that uses the Incumbent realm.

I originally reported [the same issue](https://github.com/WICG/animation-worklet/issues/94) to Animation Worklet.  It seems better to report this to CSS Paint API, too, so I'm now reporting here.

Ideally, each Web API spec should not be defined with ECMAScript.  Web IDL provides all the necessary abstraction and it's easier with Web IDL to make each spec consistent.

**Comment by yuki3** [comment]
@annevk , you seem active in this spec, too.  Could you triage this issue?

**Comment by yuki3** [comment]
As Chromium has not yet supported the true Incumbent realm and Chromium is kind-of simulating the Incumbent realm with a hack, it's currently working fine.  However, Blink bindings team is currently working to support the true Incumbent realm.  Once the true Incumbent realm gets supported, Chromium will be in trouble with this issue.

Given that Firefox correctly implements the Incumbent realm, Firefox should have difficulty to implement CSS Paint API as is.

**Comment by yuki3** [comment]
> Chromium is kind-of simulating the Incumbent realm with a hack, it's currently working fine

I meant that the current implementation/hack for the Incumbent realm in Chromium doesn't rely on "prepare to run script" nor "prepare to run a callback".  But Blink bindings team is planning/working to implement it correctly as spec'ed (using "prepare to run script" and "prepare to run a callback").

**Comment by annevk** [comment]
Looking at the open bugs (e.g., https://bugzilla.mozilla.org/show_bug.cgi?id=1302328 and dependencies) it doesn't seem like we've started doing much yet. However, it seems this would also affect https://webaudio.github.io/web-audio-api/#audioworklet.

Having said that, given that a worklet only ever has one global, wouldn't the incumbent always be the same as the current global anyway?

cc @jetvillegas @padenot

**Comment by bfgeek** [comment]
I think we should be able to change:
Let paintInstance be the result of Construct(paintCtor).
to:
Let paintInstance be the result of [constructing](https://heycam.github.io/webidl/#construct-a-callback-function) paintCtor, with no arguments.

I think I based this off the old web components spec initially, which also performed a direct construct (https://w3c.github.io/webcomponents/spec/custom/)

The only concrete difference I can see in our implementation is this will run microtasks at the end of the ctor, when it doesn't look like we currently are. (This will be minor enough for us to fix).

**Comment by yuki3** [comment]
I didn't know that Web IDL now supports [Construct a callback function type value](https://heycam.github.io/webidl/#construct-a-callback-function).  That's great and matches this use case.

I have another request, somewhat orthogonal to this, but somewhat relevant to this.

In [registerPaint](https://drafts.css-houdini.org/css-paint-api/#dom-paintworkletglobalscope-registerpaint) algorithm:
The algorithm is preparing "paint function" as a callback function (but exactly speaking, the manner to create a callback function is not correct.  This is another place to be fixed.  But this is a side note).
The "paint function" is invoked as a callback function in [invoke a paint callback](https://drafts.css-houdini.org/css-paint-api/#invoke-a-paint-callback) with "paintInstance" as the callback this value.

This is pretty similar to "callback interface" (not callback function) in Web IDL.  Why don't we define these algorithms using "callback interface"?  I'd recommend a well-defined common manner rather than a unique way.

**Comment by bfgeek** [comment]
`callback interface` has different semantics to what we are doing here.

Using a callback interface would mean each time we need to access the `paint` or `animate` function off the instance, instead what we do here is look up the `paint` method upon registration, and then invoke that each time.

This was done to be consistent with custom elements which uses the exact same semantics.
@domenic has some of the history here, but this pattern is consistent with the other "register a class" methods on the platform.

**Comment by bfgeek** [comment]
Also according to https://heycam.github.io/webidl/#es-callback-function a callback function and a JS Function represent the same thing. I can change the `registerPaint` algorithm to use the `converting` WebIDL, as this should have no side-effects.

**Comment by domenic** [comment]
callback function = JS function + callback context. Callback context is important for computing the incumbent realm, indeed. Probably you'll want to copy the changes from https://github.com/whatwg/html/pull/1471/files#diff-36cd38f49b9afa08222c0dc9ebfe35ebL66547

**Comment by annevk** [comment]
If we use this pattern in more places, isn't that indication we should start abstracting it?

**Comment by bfgeek** [comment]
From when I had a more limited understanding - https://github.com/heycam/webidl/issues/101
