### ISSUE TITLE
[css-layout-api] Naming of LayoutFragment#inlineSize, blockSize.

### ISSUE THREAD

**Issue by bfgeek** [w3c/css-houdini-drafts#748]
From @travisleithead (Travis - I'm picking off some larger things we can discuss in a group from your [feedback](https://github.com/w3ctag/design-reviews/issues/224#issuecomment-378824908)...)

> LayoutFragment's inlineSize and blockSize might be renamed to reflect (as noted in the spec) that they are relative to the border-box, e.g., inlineBorderBoxSize and blockBorderBoxSize…

**Comment by travisleithead** [comment]
Very kind of you... my plan is to distill all that initial feedback down into only a few issues to file on this repo.

I want to re-emphasis how well done this spec is so far... definitely ranks among the more interesting specs I've read in a long while. It also opens up super-cool new scenarios as well.

**Comment by bfgeek** [comment]
Thanks @travisleithead , we are meeting today so was just pulling out some things we can discuss as a group. Most of your feedback I can go through and fix/answer inline.

**Comment by bfgeek** [comment]
Closing as resolved for no change at the moment. Going to reach out to more webdevs as they are starting to play around with this to see if we need to change anything.
