### ISSUE TITLE
[CSS Typed OM Level 1] Incorrect spelling for "implementation", and the favicon is missing

### ISSUE THREAD

**Issue by geoyws** [w3c/css-houdini-drafts#753]
* please tag the issue title with the spec's shortname, like `[css-foo]`
* please link to the spec section you're talking about, or at least the spec

[https://drafts.css-houdini.org/css-typed-om/#intro](https://drafts.css-houdini.org/css-typed-om/#intro)
![image](https://user-images.githubusercontent.com/1738396/38534507-22bc625a-3cb1-11e8-92f7-be7ffa544732.png)

Also, the favicon is missing.

**Comment by tabatkins** [comment]
And dcdd172 adds the favicon to the repo, thanks!
