### ISSUE TITLE
Former editors (Shane and Elliot)

### ISSUE THREAD

**Issue by zcorpan** [w3c/css-houdini-drafts#755]
In https://github.com/w3c/css-houdini-drafts/commit/9881aec10f1db8674ba723d4adfc96dd331fb282 I accidentally pushed to master instead of creating a new branch... but per https://github.com/w3c/web-platform-tests/pull/10522#pullrequestreview-113237900 @shans and @esprehn are working on other projects

If all is well, we can close this issue and be done.

Otherwise, I can revert the commit.

**Comment by astearns** [comment]
@shans is this OK to keep, or would you rather stay on as editor on these specs until July?

**Comment by shans** [comment]
I am completely OK with keeping this, thanks for checking!
