### ISSUE TITLE
Change credentials mode default

### ISSUE THREAD

**Issue by annevk** [w3c/css-houdini-drafts#756]
We shouldn't use "`omit`" as a default. We should use "`same-origin`" for web developer convenience. See https://github.com/whatwg/html/pull/3656. (Note that `fetch()` already changed to no longer have this as a default.)

Fixing this will also require changing https://github.com/w3c/web-platform-tests/blob/master/worklets/resources/credentials-tests.js.

cc @nhiroki

**Comment by nhiroki** [comment]
Chromium issue: https://crbug.com/838540

Should we remove ```credentials``` field from ```WorkletOptions``` like changes for the worker spec, or remove ```WorkletOptions``` entirely?

**Comment by nhiroki** [comment]
I'll update the WPTs and Chromium implementation after the spec change is clarified.

**Comment by annevk** [comment]
@nhiroki note that @domenic suggested we keep `credentials` and just flip the default. I guess I'm good either way, though currently we don't offer "`omit`" outside of `fetch()`.

**Comment by nhiroki** [comment]
@annevk Thank you! I forgot the domenic's comment in the PR :) I'll change them in that way.

**Comment by nhiroki** [comment]
Fixed Chromium impl and WPTs. Can you close this issue?

**Comment by annevk** [comment]
And the specification changed with https://github.com/w3c/css-houdini-drafts/pull/757. Thanks!
