### ISSUE TITLE
[css-typed-om] 6.3. CSSUnitValue Serialization unit string bug

### ISSUE THREAD

**Issue by rwaldron** [w3c/css-houdini-drafts#761]
https://www.w3.org/TR/css-typed-om-1/#numericvalue-serialization

> 4. Otherwise, if unit is "percentage", append "%" to s, then return s.

If the `CSSUnitValue` object was created via [`CSS.percent(n)`](https://www.w3.org/TR/css-typed-om-1/#numeric-factory), the _unit_ value will be `"percent"`.

**Comment by tabatkins** [comment]
Ah, thanks, I actually made this mistake *three times*.
