### ISSUE TITLE
[css-properties-values-api] Fallbacks for registered properties

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#821]
Not necessarily a spec issue, I just need a clarification: do fallbacks (as specified by the `var()` reference) for registered properties ever trigger? E.g. can ` foo` ever been substituted here?

```
--unreg: var(--reg-length, foo);
```

And what about:

```
--reg-length: 10em;
font-size: var(--reg-length, 100px);
```
In Blink, I've implemented the latter such that the fallback (`100px`) is triggered, but now I wonder if it's more consistent that `var(--reg-length, 100px)` is substituted with the initial/inherited value of `--reg-length`. I.e. the computed value of `font-size` becomes the initial/inherited value of `--reg-length`, and the computed value of `--reg-length` becomes 10 x initial/inherited.

**Comment by tabatkins** [comment]
Yes, registered properties can be invalid. Properties registered with a "*" grammar and no initialValue is invalid by default, and any custom property becomes invalid if it's involved in a cyclic reference.
