### ISSUE TITLE
[css-properties-values-api] Canonical units for computed values

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#826]
The spec currently says:

> For &lt;custom-ident>, ident, &lt;color>, &lt;integer>, &lt;angle>, &lt;time>, &lt;resolution> or "*" values, the computed value is as specified.

I think that's a little weird that e.g. `100ms` becomes `0.1s` for `transition-duration`, but for some reason stays `100ms` for `<time>`-registered custom properties. (And similarly for the other types). I suggest:

- For &lt;angle>, &lt;time>, &lt;resolution>: let the computed value be the specified value converted to its canonical unit, with calc resolved.
- For &lt;integer>:  resolve calc (i.e. same as &lt;number>, &lt;percentage>).
- For &lt;color>: behave like `color` property? (Not sure about this one).

**Comment by tabatkins** [comment]
Agree.
