### ISSUE TITLE
CompoundStyleValue needed

### ISSUE THREAD

**Issue by therealglazou** [w3c/css-houdini-drafts#83]
Two examples:
  background-image: linear-gradient(to top right, red, white, blue)
and
  width: calc(100% - 80px);

To handle properly the individual values inside the functional notations here, you'll need to have specific interfaces for everything we have inside CSS, besides unit-based values I mean. attr, calc, gradients, all. So Maybe you need here a generic CompoundStyleValue that holds a string (for the functional notation part before the opening parenthesis) and a sequence of StyleValues. Please note you also may need a boolean indicating if the values are comma- or whitespace-separated.

**Comment by tabatkins** [comment]
Rather than just exposing them as a function name and a list of tokens, wouldn't it be better to expose a specialized interface for each?

**Comment by FremyCompany** [comment]
The advantage of the former is that it does not prevent the latter, but allows to work on values you didn't know about when you wrote your script in a sane way.

LinearGradient may inherit from CompoundStyleValue and exposes other properties like "direction" or "coloStops" but at the very least if you don't know about LinearGradients you can get an idea about what this is about by looking at the sequence of tokens and their order.

The downside is that it requires keeping track of those things, which browsers might be unwilling to do for performance reasons.

**Comment by shans** [comment]
cssText is always available, and values that we don't know how to objectify will be presented as UnknownValue objects (with just cssText). Splitting unknown functions is hard given that they sometimes use commas, sometimes spaces, and sometimes both.  If you're only splitting it into "function name" and "args", that's not much value over just the entire thing.
