### ISSUE TITLE
Sequence<StyleValue> misses information about comma

### ISSUE THREAD

**Issue by therealglazou** [w3c/css-houdini-drafts#84]
Example:
  font-family: Courier, "Lucida Console", monospace

How will you handle the comma-separated list in font-family?
Parsing is one thing but serialization is another one and you need to keep track of the fact the values are comma-separated. Hence my suggestion to handle it in a CompoundStyleValue

**Comment by tabatkins** [comment]
I'm not sure I understand the issue.  In the Typed OM, font-family knows that it takes a list of font names.  It also knows that this list needs to be serialized comma-separated.  What do you think is missing?

**Comment by shans** [comment]
Furthermore, StyleValue objects are immutable and store their serializations. When created directly (rather than from a serialized string) they invent a normalized serialization.
