### ISSUE TITLE
[css-properties-values-api] @property in shadow trees

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#846]
What happens when `@property` rules appear inside shadow trees?

 * Ignored?
 * Applied (i.e. causes property registration) at the document level?
 * Some new concept of scoped/local variables?

**Comment by tabatkins** [comment]
`CSS.registerProperty()` is allowed inside of shadows, and produces a global registration, which suggests that we should allow @property, and have it similarly produce a global registration (with all the clashing pain that implies).

That said, it would require us to define a stylesheet ordering of shadow stylesheets relative to the rest of the page. That seems complicated; I'm pretty sure we've avoided it so far?

I'm inclined to just disallow it, at least for now. If you're using shadow DOM, you're running script, right now; you can just call `CSS.registerProperty()`.

**Comment by andruud** [comment]
> I'm inclined to just disallow it, at least for now. If you're using shadow DOM, you're running script, right now; you can just call CSS.registerProperty().

Sounds good.

Long term it should probably do something, and I'd expect e.g. `@keyframes` and `@property` to have similar semantics. But it's probably smart to tread carefully here, since `@keyframes` is a mess right now (in Chrome anyway). So I support specifying that's it's disallowed, perhaps with a note that it might be allowed in the future. It should mean `@property` isn't blocked by anything difficult and can move forward relatively quickly. 🙂
