### ISSUE TITLE
StyleValue.parse() should also allow no validation

### ISSUE THREAD

**Issue by therealglazou** [w3c/css-houdini-drafts#85]
I recommend allowing the property argument passed to static StyleValue.parse() to be the empty string. In that case, validation would not happen, allowing polyfills to handle value sets for properties that don't exist in CSS (yet). I think you have an issue in the document for that.

**Comment by tabatkins** [comment]
Can't do, I think. You need to know the property you're parsing for so you can parse correctly.  "red" can be a color or a keyword, depending on where it is. Heck, "1px" can be a length or a keyword, depending.

**Comment by FremyCompany** [comment]
What happens if the properly name we give is a custom one? Because the way those work is basically the same as what Daniel is asking, right?

**Comment by tabatkins** [comment]
Custom properties just parse to a token list, yeah.

**Comment by shans** [comment]
Going to close this issue once I have the parse function defined, as it seems like custom property parsing provides for what Daniel wants.
