### ISSUE TITLE
[css-animationworklet] Avoid StatefulAnimatior/StatelessAnimator superclass and use existence of state() function

### ISSUE THREAD

**Issue by majido** [w3c/css-houdini-drafts#850]
Currently AnimationWorklet differentiate between Stateless/Stateful animators by requiring each specific animator class inherit from a specific superclass. AudioWorklet does something similar with [AudioWorkletProcessor](https://webaudio.github.io/web-audio-api/#audioworkletprocessor).

To specify this correctly we need to check the prototype chain for the registered animator class and see if any ancestor is actually the class we expect a.k.a. `IsSubclassOf(class, expected_ancestor_class)`.

AFAICT, there is no such operation in ECMA262 to achieve this. So for now we have worded the spec to use "[SameValue](https://tc39.github.io/ecma262/#sec-samevalue)" operation and only check the immediate prototype. 

Our options are:

- Ask ECMA262 to add such an operation.
- Implement this in our own spec e.g., by walking up the chain and using the `[SameValue]`.
- Scrap using super-class in our API!

**Note**: I looked at AudioWorklet specification but while their working requires extending AudioWorkletProcessor but the actual [registration](https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-registerprocessor) algorithm does not actually check the prototype chain to verify this and also Chrome implementation does not check it. So AFAICT basically they have the same problem if they are to implement this correctly.

**Comment by hoch** [comment]
What's the side effect of "scraping super-class from the spec"?

**Comment by majido** [comment]
For AnimationWorklet this is not a big deal. We currently only use the super class a way to make distinction between Statefull and Stateless animators. I am not sure about AudioWorklet, do you depend on having a superclass so that you can have 'onmessage' method on?

**Comment by majido** [comment]
To make the difference more clear. Here are the two choices:

### Currently specified - Use two separate superclasses

```
// The fact that this extends StatefulAnimator indicates this is a stateful.
// It still has to implement state() function.
registerAnimator('a', class Foo extends StatefulAnimator {
  constructor(options, state) {}
  animate(currentTime, effect) {}
  state() { return 'some state'; } 
});

registerAnimator('b', class Bar extends StatelessAnimator {
  constructor(options) {}
  animate(currentTime, effect) {}
});
```

Cons:
 - Two super classes (as opposed to mixin) makes its harder for authors to mix it with any existing class hierarchy they have. I suspect most will just have StatefulAnimator at the top of their class hierarchy which defeats the purpose.
- The author still has to implement state() function anyway. 
- More difficult to spec and implement


### New proposal - Use state function existence to differentiate
```js
registerAnimator('a', class Foo {
  constructor(options, state) {}
  animate(currentTime, effect) {}
  // The fact that there is a state getter indicates this is a stateful animator.
  state() { return 'some state'; } 
});

registerAnimator('b', class Bar {
  constructor(options) {}
  animate(currentTime, effect) {}
});
```

Pros:
 - No requirements on class hierarchy which allows a lot more flexibility 
 - Implementation of state function(satisfying the contract) is enough! 
 - Simpler to spec and implement 

Cons:
 - Having a superclass is nice e.g., we can add other methods that have meaningful default behavior (e.g., `pause`, `play`) but that only needs a single superclass `Animator` and also can be done later when it is needed.
