### ISSUE TITLE
[css-typed-om] CSSMathClamp’s min and max props conflict with CSSNumericValue’s methods

### ISSUE THREAD

**Issue by miyaokamarina** [w3c/css-houdini-drafts#855]
[`CSSMathClamp`](https://drafts.css-houdini.org/css-typed-om-1/#cssmathclamp)’s `min` and `max` attributes are incompatible with [`CSSNumericValue`](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue)’s methods `min` and `max`.

This design violates the Liskov substitution principle. Also current version of the interface cannot be properly typed with TypeScript and Flow.

Possible compatible names for these attributes are `lower` and `upper`.

**Comment by tabatkins** [comment]
Ah, indeed, that's a silly mistake on my part. It doesnt' just violate Liskov, it violates WebIDL!

**Comment by jodinathan** [comment]
is this going to be fixed?
shouldn't have ```min``` and ```max``` as ```operation``` and ```attribute``` =/

**Comment by tabatkins** [comment]
Thanks for the ping! Fixed now.
