### ISSUE TITLE
[isolated-workers] JavaScript context and communication

### ISSUE THREAD

**Issue by acterhd** [w3c/css-houdini-drafts#88]
I have thinks about CSS Houdini canvas and communication with plain JS. This is required for render canvases, images, videos, and other plain content, that impossible with pure worklet. 

---
### Communication
Should be messaging with main JS. 

Main code (web-socket style):
```
CSS.onconnection.addListener(function(dialog){
  //dialog.onmessage("hello", function(res){ //Optional
    //Receive from worklet
    //dialog.sendMessage("hello", {...});
  //});
  dialog.sendMessage("hello", {...});
});
```

Worklet code (web-socket style):
```
connect(function(dialog){
  dialog.onmessage("hello", function(res){
    //Receive hello from host
  });
  //dialog.sendMessage("hello", {...}); //optional
});
```
Dialog should be beginned by worklet. 

---

### Plain Canvas API
Also I thinking about API for create canvas in worklet. New class - `Canvas` and `PlainContext2d`. 
```
/* When receive image data from plain JS */ 
var canvas = new Canvas(width, height);
var ctx = canvas.getContext("2d");
var externalData = copyToImageData(ctx, width, height, rawData); //This function is external, user defined
ctx.putImageData(externalData, 0, 0);
images[...] = canvas; //Export to globals

/* When painting */
ctx.drawImage(images[...], 0, 0);
```
---

### Example
Full code of worklet. 
```
function createCanvas(rawData, width, height){
  var canvas = new Canvas(width, height);
  var ctx = ctx.getContext("2d");
  var external = ctx.createImageData(width, height);
  /* TODO - copying rawData to external */
  ctx.putImageData(external);
  return canvas;
}

//Communicate with plain JavaScript
var images = {};
connect(function(dialog){
  dialog.onmessage("image", function(){
    if(res.haveNews){
      images[res.name] = createCanvas(res.data, res.width, res.height);
    }
  });
});

//Draw in backgrounds
registerPaint("image", class {
  static get inputProperties() { return ['--image-name']; }
  paint(ctx, geom, properties) {
    var name = properties.get('--image-name');
    ctx.drawImage(images[name], 0, 0);
  }
});
```
---

### GPU-CPU bottleneck
Also I thinking about received pointers to GPU buffers and drawing directly on canvas. 

Host code. 
```
var pointer = CSS.makePointer(canvas);
... 
send(pointer);
```

Worklet. 
```
/* When receive */ 
images[...] = res.pointer;

/* When painting */
ctx.drawPointer(images[...], 0, 0);
```
---

### Script tag
Okay. I think worklets should be include with script tag. With mime : `application/x-css-paint`, `application/x-css-style`, `application/x-css-layout`... and etc. About shaders, this is impossible use directly as scripts. But houdini worklets can be used with script tag, and asynchronous. 
```
<script type="application/x-css-paint" src="images.paint.js" async></script>
<!-- Async are required! -->
```

---
### Shaders
And I suggest CSS shaders as part of CSS Houdini.  :) 
I suggest after previous failure of this idea. Early already suggested with CSS filters, and I suggest again. 

---
### CSS painting for
I suggest extend allowed properties where we can draw:
- `content`
- `background-image`
- `image-style-image`
- `border-image`

---
### `content` problem 
Problem of `paint`. If no width and height definition on paint or style, should be 0x0. In general, behavior should be same as `url()`. 
```
content: paint(name width height, arg0, arg1... argN); 
background-image: paint(name, args...) 
```

---
### Finally? 
Other suggestions will later.

**Comment by tabatkins** [comment]
Sorry to start with a downer, but in general, lists of requested features like this are worthless to us.  We need to know what sort of *problems* you're trying to solve, so we can tell if we're already solving those in some way, or plan to in the future, or know for a fact that we're *not* planning to solve something. Given a problem to solve that we find valuable, we can figure out what the best feature addition is, but given just a proposed feature, we have no clue whether it's solving valuable problems or just adding bloat to the platform.

A few comments on your actual suggestions.

> Should be messaging with main JS.

Worklets are called sync by the browser as needed, and aren't allowed to store additional state (we want to be able to cache results).  They can't asyncly communicate with the page (or anything).  Anything you need to communicate with the worklet has to be done through the APIs provided.  We will be working more on this in the future, of course.

> Also I thinking about API for create canvas in worklet. New class - Canvas and PlainContext2d.

The Paint API lets you draw CSS images with the Canvas API.  For anything else, you already have the `<canvas>` element.

> Also I thinking about received pointers to GPU buffers and drawing directly on canvas.

I have no idea what this means.

> I think worklets should be include with script tag.

Yeah, #47 already tracks this - we do need an ability to start up a worklet without having to run code in the outer page.

> And I suggest CSS shaders as part of CSS Houdini.

Nothing has changed in the reasons for CSS Shaders not working.

> I suggest extend allowed properties where we can draw:

The `paint()` function is just an `<image>`. It's usable in all of those places already.

> If no width and height definition on paint or style, should be 0x0.

The default size depends on the property you're using it in.  In `list-style-image` it's a 1em×1em square, in `content` it's a 300px×150px rectangle, in `background-image` it's based on `background-size`, etc.

> Other suggestions will later.

Again, we don't need feature suggestions, we need problems you'd like to solve.

**Comment by acterhd** [comment]
I tried solve problems...
- Communication should be solve problem with not available API.
- Pointer to canvas should does not copy from gpu to cpu and reverse.
Pointer is just number.
- Other problems I don't know.
6 дек. 2015 г. 9:42 пользователь "Tab Atkins Jr." <notifications@github.com>
написал:
