### ISSUE TITLE
[css-properties-values-api] The fact that "foo bar" and "foo | bar" are equivalent syntax is confusing.

### ISSUE THREAD

**Issue by emilio** [w3c/css-houdini-drafts#893]
In https://drafts.css-houdini.org/css-properties-values-api-1/#consume-syntax-descriptor, `|` and any other character are treated basically equivalently, so it means that `<length> <percentage>` is really a syntax for `<length> | <percentage>`, rather than a `<length>`, then a `<percentage>`.

Is this intentional? Is there any reason we're closing the gate to more expressive syntaxes that allow multiple keywords?

**Comment by emilio** [comment]
cc @andruud

**Comment by andruud** [comment]
Yes, I just discovered this too. This is a mistake. `"foo bar"` etc is not supposed to work (and if it did, it certainly shouldn't work like that).
