### ISSUE TITLE
[css-properties-values-api] Interpolation behavior of <transform-list> and <transform-function>+

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#901]
The spec currently says:

> Note that "&lt;transform-list>" is a pre-multiplied data type name equivalent to "&lt;transform-function>+"

And also:

> If their type is defined as a list with "+", it’s interpolated as a simple list [css3-transitions].

This means that both &lt;transform-list> and &lt;transform-function>+ interpolate as _simple lists_, and not, for example, according to [Interpolation of Transforms](https://drafts.csswg.org/css-transforms/#interpolation-of-transforms).

We should probably specify that &lt;transform-list>, &lt;transform-function>+/# and &lt;transform-function> all interpolate according to Interpolation of Transforms.

**Comment by tabatkins** [comment]
Presumably `<transform-function>#` should interpolate as a simple list of transforms. Otherwise I agree; individual transform functions, and space-separated lists, should interpolate as transforms.

**Comment by andruud** [comment]
Fixed by 4b03d10649d852f41a38aa45520b1556b4237e16.
