### ISSUE TITLE
[css-animation-worklet] IDL for StatelessAnimator doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/css-houdini-drafts#906]
I was reading through https://drafts.css-houdini.org/css-animationworklet-1/ and the IDL global/exposure bits don't make any sense to me.  For example, the draft has:
```
[Exposed=AnimationWorklet, Global=AnimationWorklet, Constructor
 (optional any options
)]
interface StatelessAnimator {
};
```
This defines an object which is supposed to be a global (hence `Global=AnimationWorklet`) but has a `Constructor`, so you can create multiple of them in a given global?

The IDL spec explicitly says for `[Global]`:

> The [Global] extended attribute must not be used on an interface that can have more than one object implementing it in the same Realm.

which means it's not really compatible with `[Constructor]`.  I filed https://github.com/heycam/webidl/issues/744 to make that very explicit.

Anyway, is this object constructible or a global?  It can't really be both.

**Comment by bzbarsky** [comment]
`StatefulAnimator` has the same problem.

**Comment by majido** [comment]
You are correct. These shouldn't really have the `[Global]` attribute. This is a mistake. :disappointed: 

Given that we are dropping these interfaces as part of #850 so I will not attempt a fix directly to this issue.
