### ISSUE TITLE
[css-typed-om] Simplifying math expressions

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#913]
CSS Values & Units defines a [simplification process](https://drafts.csswg.org/css-values-4/#calc-serialize) for calc() and other math functions, but CSS Typed OM defines no such process for reification. This means that per spec a specified value of e.g. `calc(10px + 10px)` is serialized as `calc(20px)` in CSSOM, but reified with the original structure in CSS Typed OM, and hence serialized as `calc(10px + 10px)`.

According to [this comment](https://github.com/w3c/css-houdini-drafts/issues/528#issuecomment-351580587), there was an agreement, somewhere, at some point, that the simplification should not happen during serialization, but also "apply to underlying values". If so, this should be specified somewhere. Or we should explicitly require or disallow the simplification in CSS Typed OM.

**Comment by andruud** [comment]
@tabatkins As specified currently, math functions reify according to the original structure that was parsed, without any simplification. Is this intended?

cc @xiaochengh

**Comment by tabatkins** [comment]
Not intended, we just didn't have to worry as much about the underlying value/serialization distinction before. That simplification should move to the underlying value, yes.  I'll re-file this over on CSS Values.

**Comment by tabatkins** [comment]
Lol, I filed it a year and a half ago. https://github.com/w3c/csswg-drafts/issues/2245

**Comment by andruud** [comment]
Hehe, OK. Thanks for the clarification.
