### ISSUE TITLE
[css-layout-api] out of date https://css-houdini.rocks/svg-path-layout

### ISSUE THREAD

**Issue by laurentperez** [w3c/css-houdini-drafts#934]
Hi

Chrome Canary M78

78.0.3887.0 (Build officiel) canary (64 bits)
Révision | 8a7bd486e7da7bfcc2cc336ef162d6400de4e57a-refs/branch-heads/3887@{#1}

https://css-houdini.rocks/svg-path-layout used to work fine
Now it console logs

> The layout function must be async or return a promise, falling back to block layout.

This is due to https://chromium.googlesource.com/chromium/src/+/9c224451fb63df743fbd510052458e088a438517

Is an update planned ?

**Comment by myakura** [comment]
you might want to file a bug against https://github.com/iamvdo/css-houdini.rocks
