### ISSUE TITLE
To what extent should these specs be ECMAScript-specific?

### ISSUE THREAD

**Issue by RByers** [w3c/css-houdini-drafts#95]
Normally web specs are defined only in terms of WebIDL.  JavaScript bindings are obviously the norm, but we probably don't want to completely preclude these APIs from being used from other language bindings, right?

For example [registering custom paint] refers directly to ECMAScript's "[IsConstructor](http://www.ecma-international.org/ecma-262/6.0/#sec-isconstructor)". 

I think this is fine for now, but we should probably be working to push WebIDL to specify the features we need so that we're clear on exactly what bindings properties we depend on.

**Comment by RByers** [comment]
Also if we had indirection through WebIDL, the spec would probably be a lot easier to read.  Don't need to explicitly constantly say things like "If the result of HasProperty(O=prototype, P="overflow") and IsCallable(argument=Get(O=prototype, P="overflow")) is false, throw a NotSupportedError and abort all these steps."

**Comment by bfgeek** [comment]
I've forgotten where this was actually said, but specs are allowed to directly reference (and assume) javascript now. I.e. see html spec
https://html.spec.whatwg.org/multipage/workers.html#run-a-worker

I've got an open email with @heycam about this that I haven't responded to yet (sorry cam!) to basically make a "class" a first class primitive in webidl for these purposes. I was going to poke him about it this week in person.

For the moment however we have to do all the manual checking until we have webidl support.

**Comment by RByers** [comment]
Perfect, thanks.

**Comment by bfgeek** [comment]
Tracking WebIDL bug in #125 . Closing this bug.
