### ISSUE TITLE
Rename directory css-animationworklet to css-animation-worklet

### ISSUE THREAD

**Issue by majido** [w3c/css-houdini-drafts#959]
Animation Worklet is two words and the shortname for its spec is `css-animation-worklet`. However its directory in houdini is [`css-animationworklet`](https://github.com/w3c/css-houdini-drafts/tree/master/css-animationworklet) which does not match this. 

We should rename this directory to `css-animation-worklet`. 
The only concern I have is how it will affect the existing URLs? In particular

- https://drafts.css-houdini.org/css-animationworklet/
- https://drafts.css-houdini.org/css-animationworklet-1/

Ideally it will be nice if we could redirect these to the new URLs with additional `-`. It seems that drafts.css-houdini.org has some built-in functionality for redirection. @tabatkins do you know if this is true and how I can leverage this?

Notes:
 - The first TR was published under the correct URL: `https://www.w3.org/TR/css-animation-worklet-1/`
- Once we rename the URL we should also update WPT repo to reflect this: https://github.com/web-platform-tests/wpt/blob/master/animation-worklet/idlharness.any.js#L6

**Comment by tabatkins** [comment]
We have some magic for level-based redirecting, but I don't think we do for just straight renaming. @plinss?

**Comment by plinss** [comment]
The draft server also has support for redirecting based on an old name. For some cases it's better to simply add a redirect to the web server.

There's also the issue of tests with rel="help" links to the draft if we change the canonical URL for the draft.

**Comment by majido** [comment]
I can manually update the tests rel="help" links.

So given that we have redirect ability  I will go ahead and make the directory rename and then @plinss can add a redirect from the old names:

* https://drafts.css-houdini.org/css-animationworklet -> https://drafts.css-houdini.org/css-animation-worklet
* https://drafts.css-houdini.org/css-animationworklet-1 -> https://drafts.css-houdini.org/css-animation-worklet-1
