### ISSUE TITLE
Should `overflow()` method be required in PaintClass?

### ISSUE THREAD

**Issue by upsuper** [w3c/css-houdini-drafts#97]
It seems to me the current spec requires PaintClass to have `overflow()` method, otherwise `registerPaint` would fail.

However, with this requirement, it seems the Example 1 in the spec is invalid. The example there doesn't have the `overflow()` method.

That makes me wonder, do we really want to force authors to add this method, even if they don't want to change anything?

(BTW, it seems in PaintClass'd declaration, `overflow()` have `void` as its return type, which doesn't seem to make sense.)

**Comment by upsuper** [comment]
(Hmmm, it seems I cannot add labels to issue. It should be in CSS Paint, I suppose)

**Comment by bfgeek** [comment]
Cool thanks. Obsolete as removed overflow in ac7e941e171dd43603d8f0bcad13d13ca42a16cc , as per F2F discussion.
