### ISSUE TITLE
[worklet] API of CSS.paintWorklet.addModule(url) produces network requests

### ISSUE THREAD

**Issue by andriytyurnikov** [w3c/css-houdini-drafts#979]
Current API design forces extra network request for getting paintWorklets,
which might be suboptimal is a context of modern bundling and code splitting tools.

Assumption of low overhead of extra network requests doesn't seem viable in context of modern mobile-friendly web development practices.

Having API method somewhat like:
```
const workletClass = class {paint(ctx, geom, properties){}};
CSS.paintWorklet.registerModule({'name-for-registerPaint': workletClass }) 
```
May be a good option, maybe?

**Comment by nhiroki** [comment]
IIUC, this requires to make the class definition copyable/transferable to send it from the page to the worklet context. I guess it's not so easy.

Instead, how about using blob URL like this? This is already available, and doesn't produce an actual network request.

```js
const kBlob = new Blob(["// your worklet code"], {type: 'text/javascript'});
const kBlobURL = URL.createObjectURL(kBlob);
CSS.paintWorklet.addModule(kBlobURL);
```

**Comment by andriytyurnikov** [comment]
@nhiroki , I am not sure that easiness of implementation is a right goal here. Just highlighting that outcome of current choice is a network overhead, which doesn't seems unavoidable or even simple.

**Comment by nhiroki** [comment]
I got your point. ```registerModule()``` looks simpler and better, too.

Just to clarify, I meant implementation **and spec changes** wouldn't be so easy. To add the feature, we might have to make the class copyable in the ECMAScript spec first, and I think it won't be available soon [*]. That's the reason why I suggested the workaround.

[*] One [promising proposal](https://github.com/domenic/proposal-blocks) was recently withdrawn.

**Comment by andriytyurnikov** [comment]
@nhiroki , well, sounds like you are aware of a lot of nuances.

As a software developer quite often I find myself to busy dealing with consequences of trade-offs that I've made. And in such circumstances it is not unusual to see (obviously flawed) choice as acceptable one for wrong reasons.

As current spec is a working draft, it seems like it is a proper time for being vocal about issues with current version of the spec. I thought the very idea behind "Working Draft" is to avoid obviously suboptimal choices.

While I am obviously unaware of rationale behind current solution, I have to highlight that API and implemented lifecycle mechanics seems overcomplicated when compared to plain function call. And perhaps it is worth to discuss rationale behind current mechanics of worklet initialisation/lifecycle.

And as there is no shortage of suboptimal design choices in history of web standards, I see need of being vocal.

While I don't see easiness of implementation and spec change as a right goal here as present mechanics doesn't looks simple (how all this worklet registration dance could be simpler then function call?) and if we would be silent, web developers of the future will pay the price. 

If there is a need to do something to avoid problems of present draft solution - your input/ideas are very welcome, please know that you are very welcome to share your thoughts via public or private channels.

P.S. I honestly don't understand how current mechanics of `registerPaint` and `CSS.paintWorklet.addModule()` may be perceived as 'simple'. To me it looks like people got lost in trade-offs, and we should help them by being vocal about obviously trivial options.

**Comment by domenic** [comment]
Let's consolidate this and the other related issues into https://github.com/whatwg/html/issues/6073.
