### ISSUE TITLE
[css-properties-values-api] Remove CSSRule.PROPERTY_RULE

### ISSUE THREAD

**Issue by andruud** [w3c/css-houdini-drafts#991]
Since [cssom-constants](https://wiki.csswg.org/spec/cssom-constants) is deprecated, and cssom [doesn't list](https://drafts.csswg.org/cssom/#dom-cssrule-type) CSSPropertyRule in the relevant place, shall we just remove CSSRule.PROPERTY_RULE, and have the type attribute return 0?

Alternatively add a CSSPropertyRule case to cssom, but I'd rather just remove PROPERTY_RULE.

cc @tabatkins

**Comment by tabatkins** [comment]
Yes, we should just remove PROPERTY_RULE

**Comment by tabatkins** [comment]
Removed in aa67c0f
