### ISSUE TITLE
[css-typed-om] el.attributeStyleMap.set('display', 'block') does not trigger attributeChangedCallback although style attribute changed.

### ISSUE THREAD

**Issue by trusktr** [w3c/css-houdini-drafts#996]
If I have a custom element like

```js
class MyEl extends HTMLElement {
  static observedAttributes = ['style']
  attributeChangedCallback(attr, oldVal, newVal) { console.log(attr, oldVal, newVal) }
}
customElements.define('my-el', MyEl)
```

I noticed that, in Chrome for example, if I run 

```js
el.setAttribute('style', 'block')
```

`attributeChangedCallback` is called and I see console output.

However if I run

```js
el.attributeStyleMap.set('display', new CSSKeywordValue('block'))
```

then `attributeChangedCallback` is not fired and I see no output. However, I can see the attribute is updated in the element inspector and I can call `el.getAttribute('style')` and see the new value.

Is this expected?

**Comment by tabatkins** [comment]
If the `style` attribute is actually changing its value, but your observer isn't firing for the change, that sounds like a bug.

**Comment by trusktr** [comment]
This is what I observe:

```js
el.style.setProperty('display', 'none') // triggers attributeChangedCallback
el.attributeStyleMap.set('display', new CSSKeywordValue('block')) // does not trigger attributeChangedCallback
```

Is the `style` attribute officially supposed to change in the latter case? (I do see the style attribute change in Chrome element inspector)

Here's a full working code snippet to paste in console:

```js
class MyEl extends HTMLElement {
  static observedAttributes = ['style']
  attributeChangedCallback(attr, oldVal, newVal) { console.log(attr, oldVal, newVal) }
}

customElements.define('my-el', MyEl)

const el = document.createElement('my-el')
document.body.append(el)

console.log('--------------------')
el.style.setProperty('display', 'none')

console.log('--------------------')
el.attributeStyleMap.set('display', new CSSKeywordValue('block')) // no log

console.log('--------------------')
el.style.setProperty('display', 'none')

console.log('--------------------')
```

Output:

```
--------------------
style null display: none;
--------------------
--------------------
style display: block; display: none;
--------------------
```

**Comment by tabatkins** [comment]
Yes, that is meant to fire the observer. Something about the typed-om setter isn't kicking the attribute-changed callback properly. Definitely a bug.

**Comment by tabatkins** [comment]
I'll go ahead and close this as "question answered", please report this to Chrome. ^_^

**Comment by Danny-Engelman** [comment]
Never seen the notation:

 `` static observedAttributes = ['style']``

shouldn't that be: 

````
static get observedAttributes() {
        return ["style"];
}
````

**Comment by trusktr** [comment]
@Danny-Engelman  The custom elements API simply reads the property off of the class (constructor). It doesn't matter if it is a getter or not. 

In the past, there was a time when `static observedAttributes = ['style']` was not yet legal JavaScript syntax, and the only options were to use a getter in the class definition (like your second example), or to define it after the class definition like so:

```js
class MyEl extends HTMLElement { /* ... */ }

// This is also another way to define a "static" property on a class.
MyEl.observedAttribute = ['style']

customElements.define('my-el', MyEl)
```

All three methods works. The browser only needs to read the property, but it doesn't matter how it gets there in the first place.

Even this works:

```js

class MyEl extends HTMLElement { /* ... */ }

// This is even another way to define a "static" property on a class.
Object.defineProperty(MyEl, 'observedAttribute', {
  value: ['style'],
  writable: true,
  enumerable: true,
  configurable: true,
})

customElements.define('my-el', MyEl)
```

Eventually static class properties landed (for non-methods). So then it became simpler:


```js
class MyEl extends HTMLElement {
  static observedAttribute = ['style']
}

console.log(MyEl.observedAttributes) // ['style']

customElements.define('my-el', MyEl)
```

**Comment by trusktr** [comment]
Chrome issue filed at https://bugs.chromium.org/p/chromium/issues/detail?id=1113410

**Comment by trusktr** [comment]
@Danny-Engelman Seems you've got access to Safari. :) Can you try the following code to see if it works in Safari (without static class properties)?

```js
class MyEl extends HTMLElement {
  static get observedAttributes() { return ['style'] }
  attributeChangedCallback(attr, oldVal, newVal) { console.log(attr, oldVal, newVal) }
}

customElements.define('my-el', MyEl)

const el = document.createElement('my-el')
document.body.append(el)

console.log('--------------------')
el.style.setProperty('display', 'none')

console.log('--------------------')
el.attributeStyleMap.set('display', new CSSKeywordValue('block')) // no log

console.log('--------------------')
el.style.setProperty('display', 'none')

console.log('--------------------')
```

**Comment by Danny-Engelman** [comment]
> @Danny-Engelman Seems you have access to Safari. :) Can you try the following code to see if it works in Safari (without static class properties)?

Nope

The link I posted was: https://kangax.github.io/compat-table/esnext/#test-static_class_fields

![image](https://user-images.githubusercontent.com/3382713/89512048-f6169300-d7d2-11ea-87b7-448b5b5249a8.png)

**Comment by trusktr** [comment]
Yeah, that API isn't in Firefox yet. Although MDN doesn't have a page on the `attributeStyleMap` property, it does have pages for the CSS Typed OM interfaces, including [`StylePropertyMap`](https://developer.mozilla.org/en-US/docs/Web/API/StylePropertyMap). So I suppose it's coming! The [Mozilla Platform Status](https://platform-status.mozilla.org/) page seems outdated, as it still shows the pre-Chredge landscape.
