### ISSUE TITLE
[css-typed-om] Prevent CSS Typed OM updates via `attributeStyleMap` from updating DOM `style` attributes

### ISSUE THREAD

**Issue by trusktr** [w3c/css-houdini-drafts#997]
Continuing from https://github.com/w3c/css-houdini-drafts/issues/996, personally I was hoping that modifying `el.attributeStyleMap` would not be reflected back to the DOM `style` attribute, for performance gains.

Seems half of that desire is already met in that `attributeChangedCallback` is not triggered.

Can we prevent dynamic modification of the CSS Typed OM from modifying the DOM `style` attributes?

Here's a test I made, [Bunnymark DOM V1 (CSS Typed OM via attributeStyleMap)](https://codepen.io/trusktr/pen/BajbvXr), in which I was hoping to reduce performance cost by updating continually-held references to the CSS Typed OM `CSSTransformValue`s of each bunny, then setting them with `bunny.attributeStyleMap.set('transform', transform)`.

The more bunnies there are, the more DOM elements there are that will have updated `style` attributes.

I'm not sure how much of a performance improvement not updating `style` attribute would have.

At the moment, I see in Chrome's devtools Performance tab that most time is spent in `Recalculate Style` and `Update Layer Tree`. (I'm curious why those take so long.)

**Comment by trusktr** [comment]
I forgot to put a title and I changed it to `Prevent CSS Typed OM updates via `attributeStyleMap` from updating DOM `style` attributes`

**Comment by trusktr** [comment]
Alright, here's [Bunnymark DOM V2 (CSS Typed OM via <style> element)](https://codepen.io/trusktr/pen/OJMqGYz) which is setting individual classes for each bunny in a `<style>` element, but it is _much_ slower.

**Comment by tabatkins** [comment]
Closing as No Change. This is definitely meant to update the style attribute, but browsers should definitely *also* be optimizing and only creating the value when necessary: when you have the Inspector open, when you have an attributeChanged callback, when you have a `[style="foo"]` selector, etc.

So if you're observing a slowdown you think is due to stringification occurring even when it's not being observed (a little hard to tell, but I guess similar timing between "definitely observing" and "not observing" cases would probably show it), that's a browser quality-of-implementation bug.

**Comment by trusktr** [comment]
I made two tests. For each test,

- let it run without opening devtools for 10 seconds or so (to ensure no deoptimization from devtools),
- and make sure the window size for the drawing area is the same for both in case that makes any difference.

These are the tests:

- Test 1: https://codepen.io/trusktr/pen/f3194e541c2088d46a7eab72f3e58cbe?editors=1010
  - This test does not read the style attribute value (see line 84), but instead creates a dummy string and pushes it into an array of strings.
- Test 2: https://codepen.io/trusktr/pen/9e2f452d26eb035055922dad91e9f436?editors=1010
  - This test actually reads the style attribute value, and pushes the result into an array of strings exactly the same way.

After you wait for a while (f.e. 10 seconds), open devtools for each test, and you'll see the average results outputted for every 100 animation frames.

What I found is that the average speed for the first one is almost 4 times faster. I suppose this means that in the second test the reading of the style attribute value does in fact de-optimize (as expected), so this means Chrome seems to have the above optimization in place.

I'm in Linux, so I can't test in Safari. Firefox doesn't have `attributeStyleMap` yet, so I didn't test there.

**Comment by trusktr** [comment]
I believe one of the key premises of CSS Typed OM is performance. I'm surprised how horrible the Bunnymark DOM V2 example from above still is:

https://codepen.io/trusktr/pen/OJMqGYz

(try it in Safari, it is broken in Chrome and Edge, they both fail to keep updating the rendering despite that you can see in devtools CSS inspector that the values are updating).
